"""AI SDE interview prep bank — an interactive, detailed study bank for a
new-grad targeting AI/ML Software Development Engineer roles (Amazon /
Google). Companion to AI_SDE_INTERVIEW_PLAN.md, but structured so each
topic is browsable, searchable, tagged, and explained in depth (with
worked code, complexity, pitfalls, and follow-ups) so a beginner can
actually learn from it.

Served read-only by routes/interview_prep.py at /api/ai-sde.
Fields: title (the question/topic), answer (detailed reasoning), code
(worked solution, monospace), example, complexity, pitfalls, followups,
tags. Optional fields are "" when unused.
"""

CATEGORIES = {
    "mindset": "Mindset & Strategy",
    "glossary": "Key Terms & Definitions",
    "conceptual": "Thought-Provoking Questions",
    "dsa": "Coding & DSA",
    "ml_concepts": "ML & AI Concepts",
    "ml_coding": "ML Coding (from scratch)",
    "ml_system_design": "ML System Design",
    "cs_fundamentals": "CS Fundamentals",
    "behavioral": "Behavioral (student)",
    "company": "Amazon & Google Process",
}

_CATEGORY_TAGS = {
    "mindset": ["mindset"], "dsa": ["dsa", "coding"], "ml_concepts": ["ml"],
    "ml_coding": ["ml", "coding"], "ml_system_design": ["ml", "system-design"],
    "cs_fundamentals": ["cs"], "behavioral": ["behavioral"], "company": ["process"],
    "glossary": ["glossary", "definition"], "conceptual": ["concept", "why"],
}


def Q(cat, title, answer, tags, code="", example="", complexity="", pitfalls="", followups=""):
    return {"cat": cat, "title": title, "answer": answer, "code": code,
            "example": example, "complexity": complexity, "pitfalls": pitfalls,
            "followups": followups, "tags": tags}


ENTRIES = [
    # ─────────── Mindset & Strategy ───────────
    Q("mindset", "How should I approach a coding interview (out loud)?",
      "Interviewers score HOW you think, not just the final code. Follow a repeatable script every single time: (1) Clarify — restate the problem in your own words and ask about input size, ranges, duplicates, empty inputs. (2) Examples — walk through a small example by hand. (3) Brute force first — say the obvious O(n^2) idea so you have something correct, then say 'can we do better?'. (4) Optimize — name the pattern (sliding window, hashing, etc.) and explain WHY it helps. (5) Code — narrate as you type, using clear names. (6) Test — trace an example and check edge cases. Silence is the enemy: a wrong-but-explained approach scores far better than a right-but-silent one.",
      ["mindset", "coding", "communication", "framework"],
      pitfalls="Jumping straight to code without clarifying; going silent when stuck; not stating time/space complexity; not testing edge cases.",
      followups="What if you get stuck? Say what you've tried, restate the goal, try a smaller example — a structured struggle still scores."),
    Q("mindset", "A realistic study plan and the '70% rule'",
      "Consistency beats cramming: 2-3 focused hours daily for ~12-16 weeks (~300h) beats panicked weekends. Practice by PATTERN, never random — after each problem write a one-line 'recognition note' ('saw contiguous + longest -> sliding window') because recognizing the pattern from the prompt is the real skill. Attack your WEAKEST area first each week (it feels bad, that's the point). The '70% rule': in interviews you decide with ~70% certainty and a plan to close the rest — perfectionism freezes you. Do a timed mock every week from week 3; you cannot get good at interviews without doing interviews.",
      ["mindset", "study-plan", "patterns", "mock"],
      followups="How many problems? Quality over quantity — ~150 pattern-organized problems solved OUT LOUD beats 500 skimmed."),

    # ─────────── Coding & DSA ───────────
    Q("dsa", "Two Pointers — recognize & apply",
      "Trigger words: a SORTED array, finding a pair/triplet, comparing from both ends, or in-place work. Idea: use two indices moving toward each other (or one fast, one slow) so you scan in O(n) instead of checking all O(n^2) pairs. Because the array is sorted, if the current pair's sum is too small you move the LEFT pointer right (increase), too big you move the RIGHT pointer left (decrease) — each element is visited once.",
      ["two-pointers", "array", "sorted"],
      code="# Find two numbers in the SORTED list `a` that add up to `target`.\n# Returns their two positions, or [] if no such pair exists.\ndef two_sum_sorted(a, target):\n    i, j = 0, len(a) - 1         # i starts at the left end, j at the right end\n    while i < j:                 # keep going until the two pointers meet\n        s = a[i] + a[j]          # sum of the current pair\n        if s == target:          # found a matching pair\n            return [i, j]\n        if s < target:           # sum too small -> we need a bigger number\n            i += 1               #   move the LEFT pointer right (values go up)\n        else:                    # sum too big -> we need a smaller number\n            j -= 1               #   move the RIGHT pointer left (values go down)\n    return []                    # pointers crossed with no match found",
      complexity="Time O(n), space O(1).",
      pitfalls="Only works on sorted data (or sort first, O(n log n)); watch i<j bounds to avoid using the same element twice.",
      followups="Three-sum? Fix one element, two-pointer the rest. Container with most water? Move the shorter wall inward."),
    Q("dsa", "Sliding Window — recognize & apply",
      "Trigger words: 'contiguous subarray/substring' + 'longest/shortest/at-most-k' with a condition. Idea: expand a window by moving RIGHT; when the window violates the condition, shrink from the LEFT until valid again, tracking the best window. Each element enters and leaves the window at most once, so it's O(n) instead of checking every subarray O(n^2).",
      ["sliding-window", "string", "array"],
      code="# Length of the longest substring of `s` with all-unique characters.\ndef longest_unique(s):\n    seen = {}                    # remembers the last index where each char appeared\n    left = 0                     # left edge of the current window\n    best = 0                     # longest valid window length found so far\n    for right, ch in enumerate(s):   # `right` grows the window one char at a time\n        # If `ch` is already inside the current window, jump `left` past it:\n        if ch in seen and seen[ch] >= left:\n            left = seen[ch] + 1\n        seen[ch] = right                    # record where we just saw this char\n        best = max(best, right - left + 1)  # window length = right - left + 1\n    return best",
      complexity="Time O(n), space O(min(n, alphabet)).",
      pitfalls="Forgetting to only shrink while invalid; off-by-one in window length (right-left+1).",
      followups="At most K distinct chars? Same skeleton, condition becomes len(window_counts) > K -> shrink."),
    Q("dsa", "Binary Search — including 'search on the answer'",
      "Trigger: a SORTED array, OR a problem asking to 'minimize the maximum / maximize the minimum' where you can check 'is X feasible?'. Idea: halve the search space each step -> O(log n). The powerful variant is binary-searching the ANSWER: if feasible(mid) is monotonic (true past some threshold), binary-search the smallest feasible value.",
      ["binary-search", "sorted", "search-on-answer"],
      code="# Return the index of `target` in the SORTED list `a`, or -1 if absent.\ndef search(a, target):\n    lo, hi = 0, len(a) - 1       # we are searching the range [lo, hi]\n    while lo <= hi:              # while the range still has elements\n        mid = (lo + hi) // 2     # look at the middle element\n        if a[mid] == target:     # found it\n            return mid\n        if a[mid] < target:      # target is bigger -> search the RIGHT half\n            lo = mid + 1\n        else:                    # target is smaller -> search the LEFT half\n            hi = mid - 1\n    return -1                    # target is not in the list",
      complexity="Time O(log n), space O(1).",
      pitfalls="Overflow in mid (use lo+(hi-lo)//2 in C++/Java); infinite loops from wrong lo/hi updates; boundary (<= vs <).",
      followups="Rotated sorted array? One half is always sorted — decide which side to search. Koko eating bananas? Binary search the eating speed."),
    Q("dsa", "Trees — BFS vs DFS",
      "Rule of thumb: LEVELS -> BFS (a queue); PATHS or SUBTREE work -> DFS (recursion/stack). DFS has three orders (preorder root-first, inorder left-root-right which yields sorted order for a BST, postorder children-first). Most tree problems are 'do something at each node and combine children's results' — that's postorder recursion.",
      ["tree", "bfs", "dfs", "recursion"],
      code="from collections import deque   # deque = a fast double-ended queue\n\n# Return the tree values grouped by level (top to bottom) using BFS.\ndef level_order(root):\n    if not root:                 # empty tree -> nothing to return\n        return []\n    q = deque([root])            # queue of nodes waiting to be visited\n    out = []                     # final list of levels\n    while q:                     # keep going while nodes remain\n        level = []               # values for THIS level\n        for _ in range(len(q)):  # len(q) = exactly the nodes on the current level\n            n = q.popleft()      # take the next node from the front\n            level.append(n.val)  # record its value\n            if n.left:  q.append(n.left)    # queue its children for the next level\n            if n.right: q.append(n.right)\n        out.append(level)        # this level is done\n    return out",
      complexity="Time O(n) nodes, space O(width) for BFS / O(height) for DFS.",
      pitfalls="Recursion depth on skewed trees (use an explicit stack); forgetting the base case (None).",
      followups="Validate a BST? Track (min,max) bounds down the recursion. Lowest common ancestor? Recurse and bubble up where both sides are found."),
    Q("dsa", "Graphs — BFS, DFS, and when to use each",
      "A grid or network of connectivity -> graph traversal. BFS (queue) finds the SHORTEST path in an UNWEIGHTED graph and explores level by level; DFS (stack/recursion) explores deep, good for connectivity/components/cycles. Mark nodes visited to avoid infinite loops. For a grid, neighbors are up/down/left/right.",
      ["graph", "bfs", "dfs", "grid"],
      code="# Count groups of connected land cells (islands) in a grid where\n# '1' is land and '0' is water.\ndef num_islands(grid):\n    if not grid:                 # empty grid -> zero islands\n        return 0\n    R, C = len(grid), len(grid[0])   # number of rows and columns\n    count = 0                    # islands found so far\n\n    # Flood-fill: sink this land cell and every land cell touching it.\n    def sink(r, c):\n        # Stop if we are off the grid OR this cell is not land ('1'):\n        if r < 0 or c < 0 or r >= R or c >= C or grid[r][c] != '1':\n            return\n        grid[r][c] = '0'         # mark visited by turning land into water\n        sink(r+1, c); sink(r-1, c); sink(r, c+1); sink(r, c-1)  # 4 neighbors\n\n    for r in range(R):           # scan every cell\n        for c in range(C):\n            if grid[r][c] == '1':    # found a new, unvisited island\n                count += 1           #   count it\n                sink(r, c)           #   sink the whole island so we do not recount it\n    return count",
      complexity="Time O(V+E) (or O(rows*cols) for a grid), space O(V).",
      pitfalls="Forgetting visited-marking -> infinite loop; DFS stack overflow on huge grids (use BFS/iterative).",
      followups="Shortest path unweighted? BFS. With prerequisites/ordering? Topological sort. Weighted shortest path? Dijkstra."),
    Q("dsa", "Dynamic Programming — the 4-question method",
      "DP fits problems with OVERLAPPING subproblems and OPTIMAL substructure — usually phrased 'number of ways', 'min/max cost', 'can we reach'. Don't panic: always say four things out loud — (1) STATE: what does dp[i] mean? (2) TRANSITION: how does dp[i] use smaller states? (3) BASE CASE. (4) ANSWER: which dp value. If you can state those, you've solved it. Start top-down (recursion + memo) to find the recurrence, then convert to bottom-up (a table) to avoid recursion limits.",
      ["dp", "dynamic-programming", "memoization"],
      code="# Fewest coins from `coins` that add up to `amount` (or -1 if impossible).\ndef coin_change(coins, amount):\n    INF = amount + 1             # a stand-in for 'infinity' / impossible\n    # dp[a] = fewest coins needed to make amount `a`.\n    dp = [0] + [INF] * amount    # BASE CASE: dp[0] = 0 (no coins make amount 0)\n    for a in range(1, amount + 1):   # solve every amount from 1 up to `amount`\n        for c in coins:              # try each coin\n            if c <= a:               # only if the coin fits into amount `a`\n                # TRANSITION: one coin `c` plus the best way to make (a - c)\n                dp[a] = min(dp[a], dp[a - c] + 1)\n    # ANSWER: dp[amount], or -1 if it is still 'infinite' (unreachable)\n    return dp[amount] if dp[amount] != INF else -1",
      complexity="Time O(amount * #coins), space O(amount).",
      pitfalls="Wrong state definition (the #1 cause of failure); wrong iteration order; forgetting the base case.",
      followups="Grid paths? dp[r][c]=dp[r-1][c]+dp[r][c-1]. Edit distance / LCS? 2D DP on two strings."),
    Q("dsa", "Hashing — the 'have I seen this?' pattern",
      "Whenever you find yourself asking 'have I seen X before?', 'what's the count of X?', or 'does the complement exist?', reach for a hash map/set — it turns an O(n) inner search into O(1) average, dropping many O(n^2) solutions to O(n). Classic: Two Sum in one pass — for each number, check if (target - number) is already in the map.",
      ["hashing", "hashmap", "set"],
      code="# Return the indices of the two numbers in `nums` that add up to `target`.\ndef two_sum(nums, target):\n    seen = {}                    # maps a value we have passed -> its index\n    for i, x in enumerate(nums): # walk the list once (i = index, x = value)\n        # Have we already seen the number that completes the pair?\n        if target - x in seen:\n            return [seen[target - x], i]   # yes -> return both indices\n        seen[x] = i              # otherwise remember x for future lookups\n    return []                    # no pair found",
      complexity="Time O(n), space O(n).",
      pitfalls="Hash lookups are O(1) AVERAGE (worst case O(n) with collisions); can't rely on ordering.",
      followups="Group anagrams? Key by the sorted string. Longest consecutive sequence? Use a set to check x-1 existence."),
    Q("dsa", "Heap / Top-K — when 'K largest/most frequent' appears",
      "Trigger: 'K largest / smallest / most frequent', or streaming data where you can't sort everything. A heap (priority queue) gives O(log k) insert/extract. For 'K largest', keep a MIN-heap of size k: if a new value beats the smallest, replace it — you keep only the top k in memory. Sorting everything is O(n log n); the heap approach is O(n log k), better when k << n.",
      ["heap", "priority-queue", "top-k"],
      code="import heapq                    # heapq is a MIN-heap (smallest item sits on top)\n\n# Return the k largest numbers in `nums`, biggest first.\ndef k_largest(nums, k):\n    h = []                       # a min-heap that keeps only the top k so far\n    for x in nums:\n        heapq.heappush(h, x)     # add the new number\n        if len(h) > k:           # if we now hold more than k numbers...\n            heapq.heappop(h)     #   ...drop the SMALLEST (it cannot be in the top k)\n    return sorted(h, reverse=True)   # the k survivors, largest first",
      complexity="Time O(n log k), space O(k).",
      pitfalls="Python's heapq is a MIN-heap; negate values for a max-heap. Don't sort the whole array if k is small.",
      followups="Top K frequent? Count with a hash map, then heap by count. Merge K sorted lists? Heap of the list heads."),

    # ─────────── ML & AI Concepts ───────────
    Q("ml_concepts", "Bias-Variance trade-off (explained simply)",
      "Think of two failure modes. BIAS = the model is too simple and misses the real pattern (e.g., a straight line through curvy data) — it does badly on BOTH training and test data (underfitting). VARIANCE = the model is too complex and memorizes noise in the training data — great on training, bad on test (overfitting). Total error is roughly bias^2 + variance + irreducible noise. As you add complexity, bias drops but variance rises; the goal is the sweet spot with the lowest TEST error. To fix high bias: richer model / better features. To fix high variance: more data / regularization / simpler model.",
      ["bias-variance", "overfitting", "underfitting", "fundamentals"],
      example="A degree-1 polynomial on wavy data = high bias. A degree-15 polynomial = high variance (wiggles through every point). Degree-3 might be just right.",
      pitfalls="Confusing the two; only looking at training accuracy (always check the train-vs-validation gap).",
      followups="How do ensembles help? Bagging (Random Forest) reduces variance; boosting reduces bias."),
    Q("ml_concepts", "Overfitting — what it is and how to prevent it",
      "Overfitting = the model learns the training data's noise, so it performs great on training but poorly on new/validation data (a big gap between the two curves is the tell). Prevention toolkit, in rough order: (1) more or augmented data; (2) regularization (L1/L2, dropout); (3) a simpler model / fewer parameters; (4) early stopping (stop when validation loss starts rising); (5) cross-validation to detect it; (6) for trees, pruning / limiting depth. Always diagnose by plotting training vs validation performance.",
      ["overfitting", "regularization", "dropout", "early-stopping"],
      pitfalls="Tuning on the test set (leakage) — use a separate validation set; assuming more epochs are always better.",
      followups="What's underfitting? The opposite — too simple; fix with a more expressive model or better features."),
    Q("ml_concepts", "L1 vs L2 regularization",
      "Both add a penalty on the weights to the loss to discourage complexity. L2 (Ridge) penalizes the SQUARE of the weights -> shrinks them smoothly toward (but not exactly) zero; handles correlated features well; the default. L1 (Lasso) penalizes the ABSOLUTE value -> drives some weights EXACTLY to zero, giving automatic feature selection / sparsity. Rule of thumb: L1 when you suspect many useless features and want a sparse model; L2 as a general smoother. Elastic Net combines both.",
      ["regularization", "l1", "l2", "lasso", "ridge", "feature-selection"],
      followups="Why does L1 give sparsity? Its diamond-shaped constraint region has corners on the axes, so the optimum often lands where some weights are exactly 0."),
    Q("ml_concepts", "How gradient descent works (batch vs SGD vs mini-batch)",
      "Gradient descent minimizes a loss by repeatedly stepping the parameters in the direction that most reduces error — the NEGATIVE gradient: w <- w - lr * gradient. The learning rate (lr) sets the step size: too big -> it overshoots/diverges; too small -> it crawls. Variants differ by how much data each step uses: BATCH uses the whole dataset (stable, slow, memory-heavy); STOCHASTIC (SGD) uses one example (noisy, fast, can escape shallow minima); MINI-BATCH uses ~32-256 examples — the practical default. Momentum, RMSProp, and Adam adapt the step per-parameter and speed convergence.",
      ["gradient-descent", "sgd", "optimizer", "learning-rate", "adam"],
      pitfalls="Picking a bad learning rate; not normalizing features (makes the loss surface skewed and slow).",
      followups="What is Adam? Adaptive per-parameter learning rates using running averages of the gradient and its square — a strong default optimizer."),
    Q("ml_concepts", "Precision vs Recall (and the 95%-accuracy trap)",
      "From the confusion matrix: Precision = TP/(TP+FP) = 'of the ones I flagged positive, how many were right?'. Recall = TP/(TP+FN) = 'of all the actual positives, how many did I catch?'. Choose by the COST of each error: a spam filter favors PRECISION (don't trash real email); cancer screening / fraud favors RECALL (don't miss a real case). F1 is their harmonic mean when you want balance. The classic trap: a model with 95% accuracy can be useless if 95% of data is one class — it just predicts the majority. For imbalanced data, use precision/recall/F1 and PR-AUC, not accuracy.",
      ["precision", "recall", "f1", "metrics", "imbalance", "confusion-matrix"],
      example="1000 emails, 50 spam. 'Never spam' scores 95% accuracy but catches 0 spam (recall 0). Useless.",
      followups="How to fix class imbalance? Resample (SMOTE/undersample), class weights in the loss, and pick a threshold from the PR curve."),
    Q("ml_concepts", "The Transformer & self-attention (the big one)",
      "A Transformer processes a whole sequence IN PARALLEL and models relationships between all tokens using SELF-ATTENTION. Each token is projected into three vectors: Query, Key, Value. The attention weight between two tokens = softmax(Q . K^T / sqrt(d)) — i.e., each token 'looks at' every other token and weights them by relevance; the output is the weighted sum of Values. MULTI-HEAD attention does this in several subspaces at once (capturing syntax, meaning, etc.). Because there's no recurrence, POSITIONAL ENCODINGS inject word order. Why it won over RNNs: it's parallelizable (fast on GPUs) AND captures long-range dependencies far better. It's the foundation of BERT (encoder) and GPT (decoder).",
      ["transformer", "attention", "self-attention", "nlp", "llm", "deep-learning"],
      pitfalls="Saying 'it's just attention' without Q/K/V; forgetting positional encodings (order would be lost).",
      followups="Why divide by sqrt(d)? To keep the dot products from getting huge and saturating the softmax. Encoder vs decoder? BERT understands (encoder), GPT generates (decoder)."),
    Q("ml_concepts", "CNN vs RNN vs Transformer — when to use which",
      "CNNs exploit SPATIAL locality with shared filters -> images and grid/local-pattern data; parameter-efficient and parallel. RNNs/LSTMs process SEQUENCES with a hidden state carrying memory -> older NLP and time series; but they're sequential (slow) and struggle with long-range dependencies (vanishing gradients), which LSTMs' gates partly fix. TRANSFORMERS have largely replaced RNNs for sequence tasks because self-attention captures long dependencies and parallelizes. Quick pick: images -> CNN; sequences today -> Transformer; simple/tiny time series -> maybe an RNN/LSTM.",
      ["cnn", "rnn", "lstm", "transformer", "deep-learning"],
      followups="Why do RNNs struggle with long sequences? Gradients shrink across many steps (vanishing gradient); LSTMs add gates to remember/forget."),
    Q("ml_concepts", "What is an embedding?",
      "An embedding is a dense, low-dimensional vector that represents a discrete item (a word, user, or product) so that SEMANTIC similarity becomes GEOMETRIC closeness — similar items sit near each other. They're learned from data (e.g., word2vec, or jointly inside a network). They let models generalize (the famous 'king - man + woman ~ queen') and power search, recommendations, and all modern NLP. In practice you embed items, then use nearest-neighbor search to find similar ones.",
      ["embeddings", "vectors", "nlp", "similarity"],
      followups="How do you find similar embeddings fast at scale? Approximate nearest neighbor (ANN) indexes like HNSW / FAISS."),
    Q("ml_concepts", "Cross-validation — what and why",
      "Instead of a single train/test split (which can be lucky or unlucky), K-FOLD cross-validation splits the data into k parts, trains on k-1 and validates on the held-out fold, rotating k times and averaging the scores. This gives a more RELIABLE, lower-variance estimate of how the model generalizes, and uses the data efficiently — essential for hyperparameter tuning and small datasets. Use STRATIFIED k-fold for imbalanced classes so each fold keeps the class ratio.",
      ["cross-validation", "validation", "evaluation"],
      pitfalls="Leaking information across folds (e.g., scaling using the whole dataset before splitting)."),

    # ─────────── ML Coding (from scratch) ───────────
    Q("ml_coding", "Implement Logistic Regression with gradient descent",
      "They love 'code it from scratch' because it proves you understand the math under the library. Logistic regression predicts a probability with the sigmoid of a linear combination, and learns weights by gradient descent on the log-loss. The gradient of the log-loss w.r.t. weights is beautifully simple: X^T (predictions - y) / n.",
      ["logistic-regression", "gradient-descent", "from-scratch", "ml-coding"],
      code="import numpy as np\n\n# Sigmoid squashes any number into a probability between 0 and 1.\ndef sigmoid(z):\n    return 1 / (1 + np.exp(-z))\n\n# Learn logistic-regression weights `w` and bias `b` by gradient descent.\n#   X = features (n rows x d columns), y = 0/1 labels, lr = learning rate.\ndef train(X, y, lr=0.1, epochs=1000):\n    n, d = X.shape               # n = number of examples, d = number of features\n    w = np.zeros(d)              # start every weight at 0\n    b = 0.0                      # start the bias at 0\n    for _ in range(epochs):      # repeat the learning step many times\n        p = sigmoid(X @ w + b)   # predicted probability for every example\n        error = p - y            # how far each prediction is from the true label\n        # Gradient-descent step: nudge params opposite the error's gradient.\n        w -= lr * (X.T @ error) / n     # (X.T @ error) is the log-loss gradient\n        b -= lr * error.mean()\n    return w, b                  # the learned parameters",
      complexity="Time O(epochs * n * d).",
      pitfalls="Not normalizing features; exp overflow in sigmoid (clip z); forgetting the bias term.",
      followups="Linear regression? Same loop with predictions = X@w+b and MSE loss (same gradient form)."),
    Q("ml_coding", "Implement K-Means clustering",
      "K-Means groups points into k clusters by repeating two steps until stable: (1) ASSIGN each point to its nearest centroid; (2) UPDATE each centroid to the mean of its assigned points. It minimizes within-cluster variance. It's simple and fast but sensitive to the initial centroids (use k-means++ init) and you must choose k (elbow method).",
      ["k-means", "clustering", "unsupervised", "from-scratch"],
      code="import numpy as np\n\n# Group the points in `X` into `k` clusters. Returns each point's cluster\n# label and the final cluster centers (centroids).\ndef kmeans(X, k, iters=100):\n    # Start by picking k random points to be the initial centroids.\n    centroids = X[np.random.choice(len(X), k, replace=False)]\n    for _ in range(iters):\n        # STEP 1 (assign): squared distance from each point to each centroid,\n        # then every point picks its nearest centroid.\n        d = ((X[:, None, :] - centroids[None, :, :]) ** 2).sum(2)\n        labels = d.argmin(1)             # index of the nearest centroid per point\n        # STEP 2 (update): move each centroid to the mean of its points.\n        new = np.array([X[labels == j].mean(0) for j in range(k)])\n        if np.allclose(new, centroids):  # centroids stopped moving -> converged\n            break\n        centroids = new\n    return labels, centroids",
      complexity="Time O(iters * n * k * d).",
      pitfalls="Bad init -> poor clusters (use k-means++); empty clusters; assumes spherical clusters.",
      followups="How to choose k? Elbow method (plot inertia vs k) or silhouette score."),

    # ─────────── ML System Design ───────────
    Q("ml_system_design", "The ML system design framework (6 steps)",
      "New-grad ML design is lighter but shows maturity. Use one spine for any prompt ('design recommendations / feed ranking / spam detection'): (1) CLARIFY & scope — the goal, the BUSINESS metric (engagement? revenue?), scale, latency, online vs batch. (2) FRAME as ML — what's the label and task (classification/ranking/regression/retrieval)? (3) DATA & features — sources, labels (implicit clicks vs explicit), features, and leakage traps. (4) MODEL — start simple (logistic regression / gradient-boosted trees baseline) then go deep; justify. (5) SERVING — the two-stage funnel: candidate generation (fast, high recall) -> ranking (heavier, high precision) -> re-rank (business rules/diversity). (6) EVALUATION — offline metrics (AUC, NDCG) AND online A/B tests on the business metric; monitor drift.",
      ["ml-system-design", "framework", "recommendation", "ranking"],
      followups="Why two stages? Millions of items are too many to score with a heavy model, so cheaply retrieve hundreds, then rank precisely."),
    Q("ml_system_design", "Design a recommendation system (worked example)",
      "Pick the metric first: long-term WATCH-TIME/engagement (not just clicks, to avoid clickbait). Two-stage funnel: (a) CANDIDATE GENERATION — a two-tower model (a user tower and an item tower) produces embeddings; retrieve the nearest few hundred items via ANN over millions — fast, recall-oriented. (b) RANKING — a deeper model scores those candidates on rich features (watch history, freshness, context) to predict engagement — precision-oriented. (c) RE-RANK for diversity, freshness, and business rules. Train offline, serve online, and evaluate with an A/B test; watch for feedback loops (popularity bias) and data drift.",
      ["recommendation", "two-tower", "ann", "ranking", "ml-system-design"],
      pitfalls="Optimizing clicks -> clickbait; cold start for new users/items; feedback loops amplifying popular items.",
      followups="Cold start? Use content features / popularity for new users; explore-exploit. Evaluate offline? NDCG, recall@k, then confirm with an online A/B test."),

    # ─────────── CS Fundamentals ───────────
    Q("cs_fundamentals", "Process vs Thread (and why it matters)",
      "A PROCESS is an independent running program with its OWN memory space; a THREAD is a lightweight unit of execution WITHIN a process that SHARES the process's memory. Threads are cheaper to create and switch between and can communicate via shared memory, but that sharing needs synchronization (locks) to avoid race conditions. Processes are isolated (a crash in one doesn't kill another) but heavier and communicate via IPC. Rule: use threads for shared-memory concurrency within an app; processes for isolation.",
      ["process", "thread", "concurrency", "os"],
      followups="What's a deadlock? Four conditions (mutual exclusion, hold-and-wait, no preemption, circular wait) — break any one to prevent it."),
    Q("cs_fundamentals", "SQL vs NoSQL — how to choose",
      "SQL databases (Postgres, MySQL) have a fixed SCHEMA, support relations/JOINs, give ACID transactions and strong consistency, and scale vertically — great for structured data and complex queries (orders, payments). NoSQL (key-value, document, wide-column, graph) has a flexible schema, scales horizontally, and often trades strong consistency for availability — great for massive scale, high write throughput, or flexible/denormalized data. Choose by your data shape, scale, query patterns, and consistency needs — many systems use both.",
      ["sql", "nosql", "database", "acid", "cs"],
      followups="What is ACID? Atomicity, Consistency, Isolation, Durability — the guarantees of a reliable transaction. What's an index? A structure (usually B-tree) that speeds reads at the cost of write speed/storage."),

    # ─────────── Behavioral (student) ───────────
    Q("behavioral", "STAR method + a strong student example",
      "Behavioral answers use STAR: Situation (context), Task (your responsibility), Action (spend MOST of your time here, use 'I' not 'we'), Result (quantify!). As a student your stories come from projects, hackathons, internships, research, teaching, clubs — impact matters more than title. Example (Ownership/Deliver Results): 'In my final-year capstone (S), our disease-classification model was stuck at 72% two weeks before the deadline (T). I dove into the errors, found class imbalance and overfitting, applied augmentation + class weights + dropout, and switched to transfer learning with a pretrained ResNet suited to our small dataset (A). Accuracy jumped to 93%, we demoed two days early, and it was graded the top capstone (R).' Note: specific root-cause, personal 'I', real ML depth, quantified result.",
      ["behavioral", "star", "student", "leadership-principles"],
      pitfalls="Saying 'we' instead of 'I'; no numbers; rambling past ~2 minutes; a vague action section.",
      followups="Prepare STAR stories for: a failure, a conflict, learning fast, tight deadline, and 'most proud'. For Amazon, map each to a Leadership Principle."),
    Q("behavioral", "'Why this company / why you?'",
      "Be specific and genuine — generic answers hurt. WHY THE COMPANY: connect their scale/mission/products to what you want to work on (e.g., 'Google's ML infrastructure lets me work on models at planet scale'; 'Amazon's ownership culture fits how I like to drive projects end-to-end'). WHY YOU: 3 concrete strengths tied to the role, each backed by a quick proof point from a project. Do your homework on the team/products so it doesn't sound templated. Close with authentic enthusiasm.",
      ["behavioral", "why-company", "motivation"],
      followups="For Amazon, weave in a Leadership Principle you embody; for Google, emphasize collaboration, humility, and comfort with ambiguity ('Googleyness')."),

    # ─────────── Amazon & Google Process ───────────
    Q("company", "Amazon: Leadership Principles & the Loop",
      "Amazon worships its 16 LEADERSHIP PRINCIPLES — roughly HALF of the loop is behavioral, and every behavioral answer should map to an LP. A trained 'Bar Raiser' in the loop keeps standards high and WILL dig with follow-ups. Prepare 12-15 STAR stories mapped to the heavy hitters: Customer Obsession, Ownership, Dive Deep, Deliver Results, Bias for Action, Invent and Simplify, Learn and Be Curious, Earn Trust. Coding is typically 2 mediums. Flow: Online Assessment -> phone/virtual -> the Loop (3-4 rounds mixing coding + LP behavioral).",
      ["amazon", "leadership-principles", "bar-raiser", "behavioral", "process"],
      followups="What is a Bar Raiser? A trained interviewer from another team whose job is to keep the hiring bar high; expect deep follow-ups."),
    Q("company", "Google: process, Googleyness & the committee",
      "Google weights raw DSA problem-solving and analytical CLARITY more heavily — expect harder algorithmic questions with escalating follow-ups, plus strong focus on communication and 'Googleyness' (humility, collaboration, comfort with ambiguity). Crucially, hiring is COMMITTEE-based: you're not hired by one interviewer — a packet of all your feedback goes to a hiring committee, so CONSISTENCY across every round matters. Then team matching. The process can be slow; keep other options warm.",
      ["google", "googleyness", "hiring-committee", "dsa", "process"],
      followups="What is 'Googleyness'? Comfort with ambiguity, collaboration, humility, and intellectual curiosity — demonstrated through how you communicate and handle hints."),
    Q('dsa', 'Backtracking — subsets, permutations, combinations',
      "Backtracking builds a solution one step at a time and abandons ('backtracks' from) any partial solution that cannot lead to a valid answer. It is the go-to pattern whenever a problem says 'generate ALL combinations / permutations / subsets' or has constraints to satisfy (N-Queens, Sudoku, word search).\n\nThe mental model is a DECISION TREE: at each step you make a choice, recurse deeper, then UNDO the choice to try the next option. That undo step is what makes it 'backtracking'.\n\nThe template is always the same: (1) if the current state is a complete solution, record it; (2) otherwise, for each valid next choice: make the choice, recurse, then undo it. Complexity is usually exponential (there are exponentially many combinations) — that's expected and fine for these problems.",
      ['backtracking', 'recursion', 'subsets', 'permutations', 'dsa'],
      code="# Generate every subset of nums (the 'power set').\ndef subsets(nums):\n    result = []                  # all subsets collected here\n    path = []                    # the subset we are currently building\n\n    def backtrack(start):\n        result.append(path[:])   # every state is a valid subset -> record a COPY\n        for i in range(start, len(nums)):   # choices: each remaining number\n            path.append(nums[i])            # 1) make the choice\n            backtrack(i + 1)                # 2) recurse on the rest\n            path.pop()                      # 3) UNDO the choice (backtrack)\n\n    backtrack(0)\n    return result",
      complexity='Time O(n * 2^n) (2^n subsets, each up to n long); space O(n) recursion depth.',
      pitfalls='Appending path itself instead of a COPY path[:] (it keeps mutating); forgetting the pop() undo.',
      followups="Permutations? Track a 'used' set and pick any unused element. Combinations of size k? Stop when len(path)==k. Skip duplicates? Sort then skip equal siblings."),
    Q('dsa', 'Intervals — merge, insert, overlap',
      "Interval problems ('merge overlapping meetings', 'can a person attend all meetings', 'minimum rooms needed') almost always begin the same way: SORT the intervals by start time. Once sorted, any overlaps are adjacent, so you can sweep left-to-right in a single pass.\n\nTwo intervals [a,b] and [c,d] OVERLAP when c <= b (the next one starts before the current one ends). To MERGE them, extend the current interval's end to max(b,d); if they don't overlap, start a new interval. This 'sort then sweep' pattern solves most interval questions in O(n log n).",
      ['intervals', 'sorting', 'sweep', 'dsa'],
      code='# Merge overlapping intervals. e.g. [[1,3],[2,6],[8,10]] -> [[1,6],[8,10]]\ndef merge(intervals):\n    intervals.sort(key=lambda x: x[0])   # sort by start -> overlaps become adjacent\n    merged = [intervals[0]]              # start with the first interval\n    for start, end in intervals[1:]:\n        last = merged[-1]                # the interval we might extend\n        if start <= last[1]:             # overlaps? (starts before last ends)\n            last[1] = max(last[1], end)  #   extend the end\n        else:\n            merged.append([start, end])  # no overlap -> a new interval\n    return merged',
      complexity='Time O(n log n) (the sort dominates); space O(n).',
      pitfalls='Forgetting to sort first; off-by-one on the overlap test (<= vs <).',
      followups='Min meeting rooms? Sweep starts/ends or a min-heap of end times. Insert one interval into a sorted list? Merge in place.'),
    Q('dsa', 'Linked Lists — reversal & fast/slow pointers',
      "Linked-list questions test careful pointer manipulation. Two techniques cover most of them.\n\n(1) REVERSAL: walk the list keeping three pointers — prev, curr, next — and flip each node's .next to point backwards. Always save the next node BEFORE you overwrite the pointer, or you lose the rest of the list.\n\n(2) FAST & SLOW pointers (Floyd's): move one pointer 1 step and another 2 steps. When fast reaches the end, slow is at the MIDDLE. If the list has a CYCLE, fast eventually laps slow and they meet. A 'dummy head' node often simplifies edge cases when the head itself might change.",
      ['linked-list', 'two-pointers', 'reversal', 'fast-slow', 'dsa'],
      code='# Reverse a singly linked list; return the new head.\ndef reverse(head):\n    prev = None                  # the part already reversed (behind curr)\n    curr = head\n    while curr:\n        nxt = curr.next          # save the rest BEFORE we overwrite the pointer\n        curr.next = prev         # flip this node to face backwards\n        prev = curr              # advance both pointers forward\n        curr = nxt\n    return prev                  # prev is the new head (old tail)',
      complexity='Time O(n); space O(1).',
      pitfalls='Overwriting .next before saving it; not handling an empty list (head is None).',
      followups='Detect a cycle? Fast/slow meet inside the loop. Find the middle? Slow when fast hits the end. Merge two sorted lists? Dummy head + splice.'),
    Q('dsa', 'Union-Find (Disjoint Set Union)',
      "Union-Find answers two questions very fast: 'are these two things in the same group?' and 'merge these two groups'. It's perfect for connectivity problems — number of connected components, detecting a cycle in an UNDIRECTED graph, Kruskal's minimum spanning tree, 'accounts merge'.\n\nEach element points to a 'parent'; following parents to the ROOT identifies the group. FIND walks to the root; UNION points one root at the other. Two optimizations make each operation almost O(1): PATH COMPRESSION (point nodes straight at the root during find) and UNION BY SIZE/RANK (attach the smaller tree under the larger).",
      ['union-find', 'dsu', 'graph', 'connectivity', 'dsa'],
      code="# Union-Find with path compression + union by size.\nclass UnionFind:\n    def __init__(self, n):\n        self.parent = list(range(n))   # each node starts as its own root\n        self.size = [1] * n            # group sizes (for union by size)\n\n    def find(self, x):                 # return the root of x's group\n        while self.parent[x] != x:\n            self.parent[x] = self.parent[self.parent[x]]  # path compression\n            x = self.parent[x]\n        return x\n\n    def union(self, a, b):             # merge the groups of a and b\n        ra, rb = self.find(a), self.find(b)\n        if ra == rb:                   # already the same group\n            return False\n        if self.size[ra] < self.size[rb]:   # attach smaller under larger\n            ra, rb = rb, ra\n        self.parent[rb] = ra\n        self.size[ra] += self.size[rb]\n        return True",
      complexity='Almost O(1) per operation (inverse-Ackermann); O(n) space.',
      pitfalls="Skipping the optimizations (find degrades to O(n)); using it for DIRECTED-graph cycles (it's for undirected).",
      followups="Count components? Count distinct roots. Kruskal's MST? Union edges in increasing weight, skip already-connected ones."),
    Q('dsa', 'Trie (Prefix Tree)',
      "A Trie stores strings along tree edges by their characters, so words sharing a prefix share a path. This makes prefix operations fast: insert and search take O(word length) regardless of how many words are stored — ideal for autocomplete, spell-check, and 'does any word start with this prefix?'.\n\nEach node holds a map of child characters plus a flag marking the end of a complete word (so you can tell a stored word apart from a mere prefix).",
      ['trie', 'prefix-tree', 'string', 'autocomplete', 'dsa'],
      code='# A Trie supporting insert, whole-word search, and prefix search.\nclass Trie:\n    def __init__(self):\n        self.children = {}       # char -> child Trie node\n        self.is_word = False     # True if a word ends exactly here\n\n    def insert(self, word):\n        node = self\n        for ch in word:                      # walk/create a path per character\n            node = node.children.setdefault(ch, Trie())\n        node.is_word = True                  # mark the final node as a word\n\n    def _find(self, prefix):                 # node at end of prefix, or None\n        node = self\n        for ch in prefix:\n            if ch not in node.children:\n                return None\n            node = node.children[ch]\n        return node\n\n    def search(self, word):                  # is `word` a stored word?\n        node = self._find(word)\n        return node is not None and node.is_word\n\n    def starts_with(self, prefix):           # does any word start with `prefix`?\n        return self._find(prefix) is not None',
      complexity='Insert/search O(word length); space O(total characters stored).',
      pitfalls="Confusing 'is a word' with 'is a prefix' (the is_word flag distinguishes them); memory overhead for many short words.",
      followups="Autocomplete? Cache top-k completions per node. Wildcard '.'? DFS across all children at the dot."),
    Q('ml_concepts', 'Decision Trees & Random Forests',
      "A DECISION TREE splits the data by asking yes/no questions on features, choosing at each node the split that best separates the classes (measured by Gini impurity or entropy / information gain). It's easy to read and needs no feature scaling, but a deep tree OVERFITS — it memorizes quirks of the training data.\n\nA RANDOM FOREST fixes this by training MANY trees, each on a random bootstrap sample of the rows and a random subset of the features, then averaging their votes. This 'bagging' cancels out individual trees' noise and reduces variance dramatically, giving a robust, high-accuracy model that's a strong default for tabular data. Forests also produce feature-importance scores for free.",
      ['decision-tree', 'random-forest', 'bagging', 'tabular', 'ml'],
      example='Loan-default prediction: one deep tree overfits to noise; a 100-tree forest averages them and generalizes.',
      pitfalls='A single deep tree overfits (limit depth / prune); forests are slower and less interpretable than one tree.',
      followups='Gini vs entropy? Both measure impurity; nearly interchangeable. Forest vs Gradient Boosting? Forest averages independent trees (cuts variance); boosting builds trees sequentially to fix errors (cuts bias, often higher accuracy).'),
    Q('ml_concepts', 'Ensembles — Bagging vs Boosting',
      "An ensemble combines many 'weak' models into one strong model. There are two core strategies.\n\nBAGGING (Bootstrap Aggregating) trains models in PARALLEL, each on a random resample of the data, and averages them. Because it averages independent noisy models, it mainly reduces VARIANCE (overfitting). Random Forest is the classic example.\n\nBOOSTING trains models SEQUENTIALLY: each new model focuses on the examples the previous ones got WRONG, and they're combined with weights. This mainly reduces BIAS and often gives the best accuracy on tabular data (AdaBoost, Gradient Boosting, XGBoost, LightGBM). The trade-off: boosting can overfit with too many rounds and is harder to parallelize.\n\nRule of thumb: bagging for variance, boosting for accuracy.",
      ['ensembles', 'bagging', 'boosting', 'xgboost', 'random-forest', 'ml'],
      pitfalls="Boosting overfits with too many rounds / no regularization; it's sequential, so slower to train.",
      followups='Why does bagging cut variance? Averaging independent estimates cancels noise. When XGBoost? Structured/tabular data — a Kaggle workhorse.'),
    Q('ml_concepts', 'ROC curve, AUC & choosing a threshold',
      "A classifier usually outputs a PROBABILITY; you turn it into yes/no by picking a THRESHOLD. The default 0.5 is rarely optimal, so we study how performance changes as the threshold sweeps from 0 to 1.\n\nThe ROC curve plots True Positive Rate (recall) against False Positive Rate across all thresholds. AUC (Area Under the Curve) summarizes it in one number: the probability that the model ranks a random positive above a random negative. AUC = 1.0 is perfect, 0.5 is random guessing. AUC is threshold-independent and measures ranking quality, which is why it's a favourite.\n\nFor heavily IMBALANCED data, the Precision-Recall curve (and PR-AUC) is more informative than ROC because it focuses on the rare positive class. Pick your operating threshold from the business cost of false positives vs false negatives (or by maximizing F1).",
      ['roc', 'auc', 'threshold', 'metrics', 'evaluation', 'ml'],
      pitfalls="Reading AUC as 'accuracy'; using ROC-AUC when positives are extremely rare (prefer PR-AUC).",
      followups='PR vs ROC? PR focuses on the positive class — better under heavy imbalance. Pick a threshold? Maximize F1 or hit a target precision/recall.'),
    Q('ml_concepts', 'Feature engineering, scaling & encoding',
      "Models are only as good as their features. The essentials:\n\n1) SCALING — models that use distances or gradients (logistic/linear regression, SVM, KNN, k-means, neural nets) are sensitive to feature magnitude, so standardize (subtract mean, divide by std) or min-max normalize. Tree-based models don't need scaling (they split on thresholds).\n\n2) ENCODING categoricals — one-hot encode low-cardinality categories; use target/frequency encoding or embeddings for high-cardinality ones (label-encoding is fine for trees).\n\n3) MISSING values — impute (mean/median/model-based) and optionally add a 'was-missing' indicator column.\n\n4) CREATING features — ratios, interactions, date parts, binning, and log-transforms for skewed data.\n\nGolden rule: fit every transformation on the TRAINING set only, then apply it to validation/test — otherwise you LEAK information and overestimate performance.",
      ['feature-engineering', 'scaling', 'encoding', 'preprocessing', 'leakage', 'ml'],
      pitfalls='Data leakage — scaling/encoding using the whole dataset before the split; one-hot exploding high-cardinality columns.',
      followups="Why don't trees need scaling? They split on thresholds, so magnitude is irrelevant. High-cardinality categorical? Target encoding or an embedding."),
    Q('ml_concepts', 'LLMs & RAG (Retrieval-Augmented Generation)',
      "A Large Language Model (LLM) is a Transformer trained to predict the next token. It's excellent at language but 'knows' only what was in its training data, and it can HALLUCINATE — state false things confidently.\n\nRAG fixes both for your own/current data WITHOUT retraining. Offline: chunk your documents, turn each chunk into an embedding, and store them in a vector database. At query time: embed the question, RETRIEVE the most similar chunks (semantic search), stuff them into the prompt as context, and let the LLM answer grounded in them (ideally with citations).\n\nWays to specialize an LLM, cheapest first: prompt engineering / few-shot -> RAG (for private or fresh knowledge) -> fine-tuning / LoRA (for a specific behaviour, tone, or format). RAG is the most common production pattern because it's cheap, easy to update, and reduces hallucination.",
      ['llm', 'rag', 'genai', 'embeddings', 'vector-db', 'hallucination', 'ml'],
      example='Internal support bot: policies embedded in a vector DB; a question retrieves the relevant passages and the LLM answers using only those.',
      pitfalls='Retrieval quality caps answer quality; bad chunk size hurts; the model can still hallucinate if the retrieved context is weak.',
      followups='Fine-tune vs RAG? Fine-tune bakes in behaviour/style; RAG injects knowledge. Vector DB? A store for embeddings with fast nearest-neighbour (ANN) search (Pinecone, FAISS, pgvector).'),
    Q('ml_coding', 'Implement K-Nearest-Neighbors (from scratch)',
      "KNN is the simplest classifier: to predict a new point's label, find the k closest training points (by Euclidean distance) and take a majority vote. There is no real 'training' — it just stores the data, so it's called a 'lazy learner'. It's intuitive and works well on small datasets, but prediction is slow (it compares against every training point) and it REQUIRES feature scaling, or large-magnitude features dominate the distance.",
      ['knn', 'classification', 'from-scratch', 'distance', 'ml-coding'],
      code="import numpy as np\nfrom collections import Counter\n\n# Predict x's label by majority vote of its k nearest training points.\ndef knn_predict(X_train, y_train, x, k=3):\n    # Euclidean distance from x to every training point:\n    dists = np.sqrt(((X_train - x) ** 2).sum(axis=1))\n    nearest = dists.argsort()[:k]        # indices of the k smallest distances\n    votes = Counter(y_train[i] for i in nearest)   # tally their labels\n    return votes.most_common(1)[0][0]    # the most common label wins",
      complexity='Predict O(n * d) per query (compares against all n points); no training time.',
      pitfalls='Not scaling features; slow at scale (use KD-trees / ANN); choosing k (small = noisy, large = over-smoothed).',
      followups="Speed it up? KD-tree/Ball-tree or approximate nearest neighbour. Regression version? Average the neighbours' values instead of voting."),
    Q('cs_fundamentals', 'What happens when you type a URL and press Enter?',
      'A favourite warm-up that checks breadth. Walk it end to end:\n\n1) DNS resolution — the browser resolves the domain to an IP address (checking caches, then a DNS resolver).\n2) TCP connection — a TCP handshake (SYN, SYN-ACK, ACK) opens a connection to the server (port 80/443).\n3) TLS handshake — for HTTPS, certificates are exchanged and an encrypted channel is established.\n4) HTTP request — the browser sends an HTTP GET for the page.\n5) Server processing — a load balancer routes to a server, which may hit caches, databases, and other services, then returns an HTML response.\n6) Rendering — the browser parses HTML, fetches CSS/JS/images (often from a CDN), builds the DOM, and paints the page.\n\nBe ready to go deep on ANY step — interviewers use this to probe networking, security, or systems knowledge.',
      ['networking', 'dns', 'tcp', 'http', 'tls', 'cs'],
      followups='TCP vs UDP? TCP is reliable/ordered (web); UDP is fast/connectionless (video, games). What does a CDN do here? Serves static assets from an edge near the user.'),
    Q('conceptual', 'Why can a model with 99% accuracy be useless?',
      "Because accuracy hides WHAT the model gets right. If 99% of emails are 'not spam', a model that ALWAYS predicts 'not spam' scores 99% accuracy while catching zero spam — completely useless. This is the class-imbalance trap.\n\nAccuracy treats every error equally, but in the real world a false negative (missing fraud or cancer) and a false positive (blocking a legit transaction) have very different costs. That is why for imbalanced or high-stakes problems we look at precision, recall, F1, and the ROC/PR curves instead of accuracy.\n\nLesson: before trusting a single number, always ask 'what is the base rate?' and 'what does each kind of mistake cost?'.",
      ['accuracy', 'imbalance', 'metrics', 'why']),
    Q('conceptual', 'Why split data into train / validation / test — why not just train and test?',
      "The test set is your ONE honest estimate of performance on data the model has never seen — so you are only allowed to look at it once, at the very end.\n\nBut while building the model you make hundreds of choices (which algorithm, which hyperparameters). If you tuned those against the test set, you would secretly be 'learning' the test set, and your final number would be a lie (too optimistic). So we use a THIRD split — the validation set — to make all those choices, keeping the test set sealed.\n\nAnalogy: the validation set is your practice exams; the test set is the real final you sit exactly once.",
      ['validation', 'test-set', 'overfitting', 'evaluation', 'why']),
    Q('conceptual', 'Why does more data usually beat a cleverer algorithm?',
      "Most model error comes from not having seen enough of the world, not from the algorithm being too simple. More — and more varied — data reduces variance, covers edge cases, and lets even simple models generalize. Famously, 'more data often beats a better algorithm'.\n\nThat is why companies obsess over data collection and labeling. The caveat: the data must be RELEVANT and clean; more noisy or biased data can hurt. But given the choice, doubling your good data often beats months of algorithm tweaking.",
      ['data', 'generalization', 'variance', 'why']),
    Q('conceptual', 'Why might adding more features hurt performance?',
      "Each extra feature adds a dimension the model must learn about. With limited data, more dimensions make the data sparser (the 'curse of dimensionality'), so the model can latch onto spurious patterns and OVERFIT. Irrelevant or redundant features also add noise that can drown out the real signal.\n\nThat is why feature selection, regularization (L1 zeroes out useless features), and dimensionality reduction (PCA) exist. Lesson: features must earn their place — more is not automatically better.",
      ['features', 'overfitting', 'curse-of-dimensionality', 'why']),
    Q('conceptual', 'If deep learning is so powerful, why do gradient-boosted trees still win on tabular data?',
      "Deep learning shines on UNSTRUCTURED data (images, text, audio) where it learns features automatically from huge datasets. But most business data is TABULAR — rows and columns of mixed types, often smaller — where tree ensembles like XGBoost capture the structure better, train faster, need less tuning, and are more interpretable.\n\nNeural nets need lots of data and careful engineering to match them on tables. The deeper lesson is the 'No Free Lunch' theorem: no single model is best for every problem — match the tool to the data.",
      ['deep-learning', 'xgboost', 'tabular', 'no-free-lunch', 'why']),
    Q('conceptual', 'Why do we need a learning rate — why not jump straight to the minimum?',
      'Because we usually do not KNOW where the minimum is. The loss is a high-dimensional surface we can only feel LOCALLY through the gradient (which way is downhill from right here). We cannot leap to the bottom because we only know the local slope, not the global shape.\n\nSo gradient descent takes small steps downhill, and the learning rate is the step size. Too big and it overshoots and bounces around or diverges; too small and training crawls. Adaptive optimizers like Adam adjust the step size automatically to speed this up.',
      ['learning-rate', 'gradient-descent', 'optimization', 'why']),
    Q('conceptual', 'Why is O(n log n) the limit for comparison sorting — can we beat it?',
      'Any sort that works by COMPARING pairs of elements must, in the worst case, make at least about n log n comparisons. There are n! possible orderings, and each comparison only splits the remaining possibilities in two, so you need roughly log2(n!) which is about n log n comparisons to pin down the right order. That is a mathematical lower bound, not a coding limitation.\n\nYou CAN beat it — but only by NOT comparing. Counting, radix, and bucket sort run in O(n) by using the values themselves as indices, at the cost of assumptions about the data (e.g., small integer range).',
      ['sorting', 'big-o', 'lower-bound', 'why']),
    Q('conceptual', 'Why does a hash table give O(1) lookup — and when does it fail?',
      'A hash function turns a key into an array index directly, so you jump straight to the slot instead of scanning — that is the O(1) AVERAGE case.\n\nIt fails when many keys hash to the SAME slot (a collision). In the worst case everything collides and lookup degrades to O(n) — a linear scan of one bucket. Good hash functions spread keys evenly, and resizing keeps the table from getting too full, so collisions stay rare. Lesson: O(1) is average-case; a bad hash or adversarial input can break it.',
      ['hash-table', 'collision', 'big-o', 'why']),
    Q('conceptual', 'Why is recursion elegant but sometimes dangerous?',
      "Recursion expresses 'solve a big problem using smaller copies of itself', which matches trees, divide-and-conquer, and backtracking beautifully — the code mirrors the structure.\n\nThe danger: every recursive call uses STACK memory, so deep or infinite recursion causes a stack overflow, and naive recursion can recompute the same subproblem exponentially many times (which is exactly why we add memoization or convert to iteration). Lesson: recursion is a thinking tool — watch the depth and watch for overlapping subproblems.",
      ['recursion', 'stack', 'memoization', 'why']),
    Q('conceptual', 'Why do we distinguish latency from throughput?',
      'Latency is how long ONE request takes (speed for a single user); throughput is how MANY requests you handle per second (total capacity). They are different and can trade off: batching requests raises throughput but adds latency; adding servers raises throughput but not single-request latency.\n\nA system can have great throughput yet feel slow, or feel snappy yet fall over under load. Designing well means knowing which one matters for THIS feature — a checkout wants low latency, a nightly report wants high throughput.',
      ['latency', 'throughput', 'systems', 'why']),
    Q('glossary', 'Overfitting',
      'When a model learns the training data TOO well — including its random noise — so it scores high on training data but poorly on new data. Like a student who memorizes the exact practice questions instead of understanding the topic, then fails when the real exam is worded differently. Fixes: more data, regularization, or a simpler model.',
      ['overfitting', 'fundamentals']),
    Q('glossary', 'Underfitting',
      'The opposite of overfitting: the model is too simple to capture the real pattern, so it does badly on BOTH training and new data — like fitting a straight line to clearly curved data. Fix: a more expressive model or better features.',
      ['underfitting', 'fundamentals']),
    Q('glossary', 'Regularization',
      "A technique that PENALIZES complexity to prevent overfitting. You add a term to the loss that grows with the size of the model's weights, nudging it toward simpler solutions that generalize better. L2 shrinks weights smoothly; L1 pushes some to exactly zero (feature selection); dropout randomly disables neurons during training.",
      ['regularization', 'overfitting']),
    Q('glossary', 'Gradient',
      'The direction of STEEPEST INCREASE of a function, whose size says how steep it is. In ML we take the gradient of the loss with respect to the weights, then step the OPPOSITE (downhill) way to reduce error. Picture standing on a foggy hill: the gradient points uphill, so you walk the other way to reach the valley (minimum loss).',
      ['gradient', 'optimization']),
    Q('glossary', 'Gradient Descent',
      'The core training algorithm: repeatedly compute the gradient of the loss and nudge the weights a small step downhill (w = w - learning_rate * gradient) until the loss stops improving. Variants differ by how much data each step uses: batch (all), stochastic (one example), mini-batch (a small group — the default).',
      ['gradient-descent', 'training', 'optimization']),
    Q('glossary', 'Learning rate',
      'A hyperparameter that sets how big a step gradient descent takes each update. Too large and training overshoots or diverges; too small and it takes forever. One of the most important knobs to tune.',
      ['learning-rate', 'hyperparameter']),
    Q('glossary', 'Epoch',
      'One full pass through the ENTIRE training dataset during training. Models usually train for many epochs; too few underfits, too many can overfit (watch the validation loss to decide when to stop).',
      ['epoch', 'training']),
    Q('glossary', 'Batch (mini-batch)',
      'The small group of training examples processed together in one gradient-descent step (e.g., 32 or 128). Mini-batches balance the stability of using all the data with the speed and low memory of using one example at a time.',
      ['batch', 'training']),
    Q('glossary', 'Hyperparameter vs Parameter',
      'PARAMETERS are what the model LEARNS from data (the weights). HYPERPARAMETERS are settings YOU choose before training that control HOW it learns — learning rate, number of layers, tree depth, k in KNN. You tune hyperparameters on the validation set.',
      ['hyperparameter', 'parameter']),
    Q('glossary', 'Loss (cost) function',
      "A single number measuring how WRONG the model's predictions are; training minimizes it. Examples: mean squared error for regression, cross-entropy (log-loss) for classification. The choice of loss defines what 'good' means for the model.",
      ['loss', 'training']),
    Q('glossary', 'Feature vs Label',
      "A FEATURE is an input variable the model uses to predict (a house's size, location). The LABEL is the correct answer we want to predict (the house's price). Supervised learning learns the mapping from features to labels.",
      ['feature', 'label', 'supervised']),
    Q('glossary', 'Embedding',
      "A dense vector of numbers representing a discrete thing (a word, user, product) so that similar things sit CLOSE together in that vector space. Embeddings let models measure similarity ('king' near 'queen') and power search, recommendations, and modern NLP.",
      ['embedding', 'vectors', 'nlp']),
    Q('glossary', 'Tensor',
      'A multi-dimensional array of numbers — the basic data container in deep learning. A single number is a scalar (0-D), a list is a vector (1-D), a table is a matrix (2-D), and higher dimensions (e.g., a batch of colour images) are tensors. PyTorch/TensorFlow operate on tensors.',
      ['tensor', 'deep-learning']),
    Q('glossary', 'Neural network',
      "A model built from layers of simple units ('neurons'), each computing a weighted sum of its inputs followed by a non-linear activation. Stacking layers lets it learn increasingly complex patterns; it is trained by gradient descent + backpropagation. Deep learning = neural networks with many layers.",
      ['neural-network', 'deep-learning']),
    Q('glossary', 'Activation function',
      "A non-linear function applied to each neuron's output (ReLU, sigmoid, tanh). Without it, stacked layers would collapse into a single linear model; the non-linearity is exactly what lets neural nets learn complex, curvy patterns.",
      ['activation', 'relu', 'deep-learning']),
    Q('glossary', 'Backpropagation',
      'The algorithm that efficiently computes the gradient of the loss for EVERY weight in a neural network by applying the chain rule backwards from output to input. One backward pass yields all the gradients — it is what makes training deep networks feasible.',
      ['backpropagation', 'training', 'deep-learning']),
    Q('glossary', 'Supervised vs Unsupervised vs Reinforcement',
      'SUPERVISED learning trains on labelled examples (features -> known answer), e.g. spam detection. UNSUPERVISED finds structure in UNlabelled data, e.g. clustering customers. REINFORCEMENT learning trains an agent by trial and error using rewards, e.g. game-playing or robotics.',
      ['supervised', 'unsupervised', 'reinforcement']),
    Q('glossary', 'Classification vs Regression',
      'Both are supervised, differing by the OUTPUT. Classification predicts a CATEGORY (spam / not-spam, cat / dog). Regression predicts a CONTINUOUS number (price, temperature). Their losses and metrics differ (cross-entropy + accuracy/F1 vs MSE/MAE + R^2).',
      ['classification', 'regression']),
    Q('glossary', 'Normalization vs Standardization',
      'Both rescale features so no single one dominates by magnitude. NORMALIZATION (min-max) squeezes values into a range like [0,1]. STANDARDIZATION subtracts the mean and divides by the standard deviation (mean 0, std 1). Needed for distance/gradient-based models (KNN, SVM, neural nets), not for trees.',
      ['normalization', 'standardization', 'preprocessing']),
    Q('glossary', 'Big-O notation',
      "A way to describe how an algorithm's running time (or memory) GROWS as the input size n grows, ignoring constants. O(1) constant, O(log n) halving (binary search), O(n) linear, O(n log n) good sorting, O(n^2) nested loops, O(2^n) exponential. It compares algorithms independent of hardware.",
      ['big-o', 'complexity', 'dsa']),
    Q('glossary', 'Time vs Space complexity',
      'TIME complexity is how the number of operations grows with input size; SPACE complexity is how much extra MEMORY grows. There is often a trade-off — spend memory (a hash table, a cache, memoization) to save time. State both in interviews.',
      ['complexity', 'dsa']),
    Q('glossary', 'Data structure',
      'A way of organizing data so certain operations are efficient. Arrays give O(1) index access; hash tables O(1) lookup by key; trees keep data sorted with O(log n) ops; heaps give min/max fast; graphs model relationships. Choosing the right one is half of solving a problem.',
      ['data-structure', 'dsa']),
    Q('glossary', 'Hash table (hash map)',
      "Stores key-value pairs and finds a value by key in O(1) AVERAGE time, using a hash function to jump straight to the key's slot. Backs Python dicts and sets. Catch: worst case O(n) if many keys collide.",
      ['hash-table', 'dsa']),
    Q('glossary', 'Stack vs Queue',
      'A STACK is Last-In-First-Out (a pile of plates) — used for undo, recursion, and bracket matching. A QUEUE is First-In-First-Out (a line at a shop) — used for BFS and scheduling. Both add/remove in O(1).',
      ['stack', 'queue', 'dsa']),
    Q('glossary', 'Recursion',
      'When a function calls itself on a SMALLER version of the problem until it hits a base case. It elegantly expresses trees, divide-and-conquer, and backtracking. Watch out for deep recursion (stack overflow) and recomputation (add memoization).',
      ['recursion', 'dsa']),
    Q('glossary', 'Dynamic programming',
      'Solving a problem by breaking it into OVERLAPPING subproblems, solving each once, and STORING the results to reuse instead of recomputing. Turns exponential brute force into polynomial time. Define the state, the transition, the base case, and the answer.',
      ['dynamic-programming', 'dsa']),
    Q('glossary', 'BFS vs DFS',
      'Two ways to explore a tree/graph. BFS (Breadth-First) visits level by level using a QUEUE — best for shortest paths in unweighted graphs. DFS (Depth-First) goes as deep as possible using recursion / a STACK — best for connectivity, cycles, and exploring all paths.',
      ['bfs', 'dfs', 'graph', 'dsa']),
]

# Fill tags: explicit + category-derived.
for _e in ENTRIES:
    _e["tags"] = sorted(set([t.lower() for t in _e.get("tags", [])] + _CATEGORY_TAGS.get(_e["cat"], [])))
