"""Behavioural pack for the AI SDE bank (Section 6).

The bank already carries a full set of Amazon Leadership Principle prompts with
STAR skeletons. What was missing is the GOOGLE half - Googleyness, general
cognitive ability, collaboration - plus the student-specific questions a
final-year candidate actually gets: group projects, competing deadlines, a
professor you disagreed with, and the two-minute self-introduction that opens
every single loop.

Every entry follows the same shape: what the interviewer is REALLY testing,
how to structure the answer, a worked student-scale example, and the ways
candidates lose the point. Imported by ai_sde_bank.py, which supplies Q(...).
"""


def _c(s):
    return s.strip("\n")


def build(Q):
    entries = []

    entries += [
        Q("behavioral", "What 'Googleyness' actually means, and how to show it",
          "Google does not have Amazon's published list of principles, so candidates guess. The interview rubric has four axes and Googleyness is one of them; the other three are General Cognitive Ability (how you STRUCTURE an unfamiliar problem, which is scored in your coding and design rounds), Role-Related Knowledge, and Leadership - specifically EMERGENT leadership, meaning you step up when your skill is needed and step BACK when someone else's is. Googleyness itself decomposes into things you can actually demonstrate: comfort with ambiguity (you moved forward without complete requirements), bias to action balanced with humility (you tried something, and you changed course when the evidence said to), intellectual curiosity (you dug into WHY, not just what), collaboration (you made other people more effective), and doing the right thing when nobody is checking. HOW TO SHOW IT rather than claim it: in every story, include the moment you did not know something and say what you did about it; name the people you worked with and what THEY contributed; describe a decision you reversed and what changed your mind. THE CONTRAST WITH AMAZON is worth internalising because the same story needs different emphasis. Amazon wants ownership, data and a quantified result, told in the first person singular - 'I saw, I decided, I delivered, here is the number'. Google wants your reasoning process and your effect on the people around you - 'here is how I framed it, here is what I got wrong, here is how the team converged'. Same story, different spotlight. Saying 'we' too much loses points at Amazon; saying only 'I' can read as a poor collaborator at Google.",
          ["googleyness", "google", "behavioral", "star", "culture"],
          difficulty="Easy",
          frequency="Always asked - Googleyness is one of the four scored axes in every Google interview loop.",
          mnemonic="Google scores four things: cognitive ability (how you structure a problem), role knowledge, EMERGENT leadership (step up AND step back), and Googleyness (ambiguity, curiosity, humility, collaboration, doing the right thing). Amazon wants 'I' and a number; Google wants your reasoning and your effect on others.",
          example="Same project, two framings. AMAZON: 'Our model's inference was too slow for the demo, so I profiled it, found the bottleneck was per-request feature computation, added a cache, and cut p95 latency from 900ms to 120ms - which let us demo live.' GOOGLE: 'The obvious fix was a smaller model, but I wanted to know WHERE the time was going before trading accuracy away. Profiling showed it was feature computation, not inference - so caching fixed it without touching the model. I shared the profile with the two teammates who had been optimising the model, and we redirected that work.' Identical facts; the first spotlights ownership and a number, the second spotlights reasoning and the team.",
          examples=[
              "The four scored axes, named, because most candidates only know about two. GENERAL COGNITIVE ABILITY - how you STRUCTURE an unfamiliar problem, scored inside your coding and design rounds, which is why narrating your approach matters as much as the code. ROLE-RELATED KNOWLEDGE - can you actually do the job. LEADERSHIP - specifically EMERGENT leadership: you step up when your skill is needed and step BACK when someone else's is. GOOGLEYNESS - ambiguity, curiosity, humility, collaboration, doing the right thing. Knowing there are four and that leadership means the emergent kind is itself a signal.",
              "Showing rather than claiming, with the sentence pattern that does it. Claiming: 'I'm very collaborative and I love learning.' Showing: 'I didn't know how HNSW indexes worked, so I spent an evening reading the paper and then wrote a one-page summary for the two teammates who'd be using it.' The second contains an admission of not knowing, an unprompted action, and another human who benefited - three Googleyness signals in one sentence, none of them asserted.",
              "The same story, two spotlights. AMAZON: 'Our model's inference was too slow for the demo, so I profiled it, found the bottleneck was per-request feature computation, added a cache, and cut p95 from 900ms to 120ms - which let us demo live.' GOOGLE: 'The obvious fix was a smaller model, but I wanted to know WHERE the time was going before trading accuracy away. Profiling showed it was feature computation, not inference, so caching fixed it without touching the model - and I shared the profile with the two teammates who'd been optimising the model, so we redirected that work.' Identical facts; ownership-and-a-number versus reasoning-and-effect-on-others.",
              "The 'I' versus 'we' calibration, which cuts both ways. At Amazon, 'we decided, we built, we shipped' reads as someone hiding inside a team - they cannot score what YOU did, so say 'I'. At Google, a story with no other humans in it reads as someone who does not work well with people. The fix is not a ratio, it is structure: use 'I' for your decisions and actions, and name others for their contributions. 'I proposed X; Priya pointed out it would break Y, so we did Z' scores at both companies.",
              "Intellectual humility as a scored trait, not a soft skill. Google explicitly looks for people who change their mind when the evidence says to - so 'tell me about a time you were wrong' is a Googleyness probe, not a trap, and the answer 'I can't think of one' is a failing answer. Prepare a real one where you argued for something, went and got the evidence yourself, and reversed - ideally against your own proposal. That combination of backbone and humility is rare enough to be memorable.",
              "What 'doing the right thing' looks like at student scale, since nobody expects a corporate ethics story. Telling your group the benchmark you ran was flawed after they'd already put it in the slides. Flagging that your model's training data had leaked labels rather than reporting the 0.97 AUC. Correcting a teammate's over-claim to a supervisor. These are small, real, and they demonstrate the trait far better than anything grand - and the marker is that doing it cost you something.",
          ],
          pitfalls="Claiming traits instead of demonstrating them ('I'm very collaborative'); telling a story with no other humans in it; presenting yourself as never wrong, which reads as low self-awareness; assuming Googleyness means being nice - it means being effective WITH people.",
          followups="'Tell me about a time you were wrong' - have this ready, because at Google it is a Googleyness probe, not a trap. 'What would you do if you disagreed with your team's technical direction?' - argue with evidence, commit once decided, and say what would make you revisit."),

        Q("behavioral", "Tell me about yourself / walk me through your resume (the two-minute answer)",
          "It opens almost every interview and most candidates waste it by narrating their CV chronologically from school. THE INTERVIEWER IS TESTING three things: can you communicate concisely under no pressure at all (if not, the design round will be painful), what do you choose to emphasise (it tells them what you value), and is there a coherent story leading to THIS role. THE STRUCTURE that works is Present - Past - Why here, in about 90 to 120 seconds. PRESENT (20 seconds): who you are right now, in one sentence - 'I'm a final-year Computer Science student specialising in AI and data science.' PAST (60 seconds): two or three specific things that built toward this role, each with a concrete outcome, not a list of coursework. Pick the projects you WANT to be asked about, because you are steering the next twenty minutes. WHY HERE (20 seconds): a specific, researched reason - a team, a product, a paper, a technology - not 'Google is a great company'. THE RULES: no childhood, no chronological march through every semester, no reciting the resume they are holding, and land on something they will want to pull on. Practise it out loud until it is 90 seconds without notes, then stop practising - over-rehearsed sounds worse than slightly rough. And end with a small hook: 'the part I found most interesting was X' invites the natural follow-up.",
          ["behavioral", "introduction", "star", "communication", "interview-strategy"],
          difficulty="Easy",
          frequency="Always asked - it is the first question in essentially every interview at every company.",
          mnemonic="Present -> Past -> Why here, in 90-120 seconds. Choose the two projects you WANT to be asked about; you are steering the next twenty minutes. End on a hook, not on a full stop.",
          example="'I'm a final-year Computer Science student specialising in AI and data science. Two things shaped what I want to do next. The first was a course project where I built a document question-answering system with retrieval-augmented generation - the model part was straightforward, but making the retrieval reliable took most of the work, and that is where I learned the engineering matters more than the model. The second was a summer internship where I owned a data pipeline that had been failing weekly; I added validation and idempotent retries and it ran unattended for the rest of the summer. Both taught me I like the systems side of ML rather than pure modelling, which is why I'm interested in this team specifically - you're building the serving infrastructure, not just the models.'",
          examples=[
              "The 90-second script, timed. PRESENT (20s): 'I'm a final-year Computer Science student specialising in AI and data science.' PAST (60s): two projects, each with an outcome - the RAG system where the retrieval, not the model, was the hard part; the internship pipeline that had been failing weekly and ran unattended after you added validation and idempotent retries. WHY HERE (20s): one specific, researched reason. Practise it aloud until it lands at 90-120 seconds, then STOP practising - over-rehearsed sounds worse than slightly rough, and interviewers can hear a recitation.",
              "Why you are steering, not just answering. Whatever you name here is what gets probed for the next twenty minutes. So choose the two projects you WANT to defend two levels down, not the two with the most impressive titles. If you mention a Kaggle competition you barely remember, you have just booked yourself twenty minutes of questions about it. Naming the project where you personally made the hard calls is the single highest-leverage decision in the whole interview, and it costs nothing.",
              "The hook, and why it works. End on something slightly unfinished: 'the part I found most interesting was that the model barely mattered'. That is an invitation, and interviewers take it - which means the next question is one you chose and are prepared for. Compare ending on a flat full stop ('...and that's my background'), which forces them to pick the next question from your CV at random.",
              "What a weak version sounds like, so you can hear the difference. 'I was born in Chennai and I've been passionate about computers since I was young. In school I liked maths. I did my BE in CSE with a specialisation in AI and data science, where I studied DBMS, operating systems, machine learning...' - two minutes in, nothing specific has been said, no project has been named, and the interviewer has learned only that you can read your own transcript aloud. Chronology is the trap: start where you are NOW and work backwards only as far as it earns its place.",
              "Tailoring the 'why here' without being obsequious. Weak: 'Google is a great company with brilliant people.' Strong: 'You're building the serving infrastructure rather than the models, which is the part I found hardest in my own projects.' The test is whether the sentence would still be true if you swapped in a different company - if yes, it says nothing. One specific detail about the team, the product or a paper is enough; you do not need to have read their entire engineering blog.",
              "The same answer, adjusted per company. At AMAZON, weight the PAST section toward ownership and a number ('it ran unattended for the rest of the summer' / 'cut p95 from 900ms to 120ms'), because everything there is graded against the Leadership Principles. At GOOGLE, weight it toward how you reasoned and who you worked with ('profiling showed it was the features, not the model, so we redirected two people's work'). Same two projects, same 90 seconds, different emphasis - and preparing both versions takes ten minutes.",
          ],
          pitfalls="Going four minutes; starting at 'I was born in...'; reading the resume aloud; being generic about why this company; mentioning a project you cannot defend in depth (they will ask); no structure, so it wanders.",
          followups="'Tell me more about that RAG project' - which is exactly what you wanted, so have the technical depth ready two levels down. 'Why this team rather than another?' - name something only true of them."),

        Q("behavioral", "Tell me about a time you worked with someone difficult (collaboration)",
          "WHAT THEY ARE REALLY TESTING: not whether you have met a difficult person, but whether you are the kind of person who makes conflict worse. They listen for how you describe the other person - contempt is disqualifying - and for whether you tried to understand their position before trying to change it. THE STRUCTURE: STAR, with the ACTION weighted toward the conversation you had, not the technical outcome. And there is a specific move that scores: describe the moment you found out WHY they were behaving that way. Almost every difficult teammate has a reason (they were overloaded, they had been burned by a previous rewrite, they did not understand the requirement, they were being measured on something you were not), and discovering it is the difference between a mature story and a complaint. THE ARC that works: I noticed friction -> I went to them directly and privately -> I asked before telling -> I found the underlying cause -> we agreed a concrete change -> here is what improved. ESCALATION IS ALLOWED, but only after a direct attempt, and framed as getting help rather than reporting someone. CHOOSING THE STORY: a group project where one member was not contributing is fine and normal for a student - do not feel you need a workplace story. What is NOT fine is picking a story where you were the difficult one and do not notice, or a story where the resolution was 'I just did their part myself' with no attempt to fix the cause.",
          ["behavioral", "collaboration", "conflict", "googleyness", "star", "teamwork"],
          difficulty="Medium",
          frequency="Always asked in some form at both Google and Amazon (at Amazon it maps to Earn Trust and Have Backbone).",
          mnemonic="They are testing whether YOU are the difficult one. Never show contempt. The scoring move is finding out WHY they behaved that way - then a private, direct conversation, a concrete agreement, and a real outcome.",
          example="SITUATION: In a four-person final-year project, one teammate kept rejecting pull requests with one-line comments and the review queue stalled for days. TASK: I owned the integration deadline and we were losing three days a week. ACTION: Rather than escalating to the supervisor, I asked him for fifteen minutes and started by asking what he was seeing in the code. It turned out he had spent the previous term on a project that failed a demo because of an untested edge case, and he did not trust our test coverage - which, honestly, was thin. So instead of arguing about review speed, we agreed a rule: any PR touching the model pipeline includes a test for the failure case, and in exchange reviews get a 24-hour turnaround. I wrote the first three tests myself to make the rule cheap to follow. RESULT: Review time dropped from three days to under one, coverage went from about 30% to 70%, and we shipped on time. What I took from it is that a process complaint is usually a trust problem wearing a costume.",
          examples=[
              "The scoring move is finding out WHY. A teammate kept rejecting pull requests with one-line comments and the review queue stalled for days. The easy story is 'he was obstructive and I escalated'. The real one: I asked for fifteen minutes and started by asking what he was seeing in the code — and he had spent the previous term on a project that failed a demo because of an untested edge case, so he did not trust our coverage, which was genuinely thin. Almost every difficult teammate has a reason. Discovering it is the difference between a mature story and a complaint.",
              "The resolution has to be a concrete agreement, not a truce. We traded: any PR touching the model pipeline includes a test for the failure case, and in exchange reviews get a 24-hour turnaround. I wrote the first three tests myself so the new rule was cheap for him to follow. Review time went from three days to under one and coverage went from about 30% to 70%. A story that ends with 'we talked and things got better' has no mechanism and no number, and reads as wishful.",
              "How you describe the other person is itself the test. Contempt is disqualifying — 'he was lazy', 'she was impossible', 'they didn't understand the code'. Interviewers are listening for whether YOU are the difficult one, and the surest signal is whether you can state the other person's position in a way they would recognise. If you cannot say what they thought they were protecting, you probably never asked.",
              "The two failure modes that bracket a good answer. AVOIDANCE: routing around them, doing their part yourself, or waiting for the project to end — solves nothing and tells the interviewer you will silently absorb an underperformer. ESCALATION FIRST: going to the supervisor before a direct private conversation, which reads as someone who creates political problems. The order that scores is private and direct, then escalate with facts and a proposal only if that fails.",
              "Student-scale material is completely acceptable, and often better. A group project where one member was not contributing, a lab partner who disagreed about the approach, a society committee where two people wanted different things, a part-time job with a difficult shift manager. You do not need a workplace story. What you DO need is genuine friction — a story where the disagreement was mild reads as having no conflict to report, which is its own kind of answer.",
              "The probes. 'What if the conversation had not worked?' — escalate with impact and options, not a complaint: 'here is what it is costing, here are the two paths I see'. 'What would you do differently?' — have a real answer; 'nothing' is the wrong one, and 'I would have asked sooner rather than assuming' is almost always true. 'How did they react?' — a story where the other person never changed at all is either incomplete or was resolved by you accommodating them, which is worth saying honestly if so.",
          ],
          pitfalls="Describing the person as lazy, stupid or toxic; a story where you avoided them entirely; escalating first; no resolution, or a resolution where you did their work; picking a conflict that was genuinely your fault without acknowledging it; a story so trivial it shows no real friction.",
          followups="'What if the conversation had not worked?' Escalate with facts and a proposal, not a complaint - 'here is the impact, here are the two options I see'. 'What would you do differently?' Have a real answer; 'nothing' is the wrong one."),

        Q("behavioral", "Tell me about a time you dealt with ambiguity or unclear requirements",
          "This is a top-scored Googleyness signal and it appears at Amazon too (Bias for Action, Are Right A Lot). WHAT THEY ARE TESTING: whether you freeze without instructions, or whether you can impose enough structure to start moving while staying ready to be wrong. Juniors often think the right answer is 'I asked for clarification', which is only the first half - anyone can ask questions; the signal is what you did when the answer was 'we do not know yet'. THE STRUCTURE THAT SCORES: (1) I identified WHAT specifically was ambiguous, and separated it from what was actually clear - most ambiguity is partial. (2) I asked the two or three questions whose answers would change my approach, not twenty. (3) For what remained unknown, I made an EXPLICIT ASSUMPTION, wrote it down, and told people - that is the whole move, because a stated assumption is reversible and a silent one is a landmine. (4) I built the smallest thing that would test the assumption. (5) I set a checkpoint to revisit. THE SENTENCE THAT LANDS: 'I decided X assuming Y; if Y turned out false the fix would cost about a day, so it was worth starting rather than waiting.' That shows you weighed the cost of being wrong, which is exactly what senior engineers do and what interviewers are checking for. Student-scale examples are completely acceptable: an open-ended capstone brief, a hackathon with a vague theme, an internship task where the person who knew the answer was on holiday.",
          ["behavioral", "ambiguity", "googleyness", "star", "decision-making", "bias-for-action"],
          difficulty="Medium",
          frequency="Very commonly asked at Google (a core Googleyness probe) and at Amazon under Bias for Action.",
          mnemonic="Asking for clarification is only half the answer. The scoring move: state an explicit ASSUMPTION, size the cost of being wrong, build the smallest thing that tests it, set a checkpoint. Ambiguity is a reason to start small, not a reason to wait.",
          example="SITUATION: My internship task was 'make the recommendations better' with no metric and no baseline, and the product owner was away for two weeks. TASK: I had six weeks total, so waiting was not viable. ACTION: I split what was ambiguous (what 'better' means) from what was not (the data, the current model, the serving path). I asked the two engineers on the team what users complained about, and the answer was repetitive recommendations rather than irrelevant ones. So I made an explicit assumption - 'better means more diverse, not more accurate' - wrote it at the top of my design doc, and messaged the product owner so it was on the record. Then I built the smallest test: added a diversity re-ranking step behind a flag and measured both diversity and click-through offline, so if my assumption was wrong I had lost three days, not six weeks. RESULT: When the product owner returned she confirmed diversity was the priority; the re-ranker raised category coverage by 40% with click-through flat, and it shipped behind the flag. The lesson I took is that writing the assumption down is what makes it cheap to be wrong.",
          pitfalls="Stopping at 'I asked my manager'; freezing until instructions arrived; making a big irreversible bet on an unstated assumption; a story with no checkpoint or reversal plan; claiming there was ambiguity when the requirements were actually clear and you just did not read them.",
          followups="'What if your assumption had been wrong?' Have the answer ready with a cost - that is the point of the story. 'How do you decide when to stop asking and start building?' When the next question's answer would not change what you build first."),

        Q("behavioral", "Tell me about a time you helped a teammate succeed",
          "A pure collaboration probe, and a surprisingly discriminating one. WHAT THEY ARE TESTING: whether you see other people's success as part of your job or as a distraction from your own, and whether you can help without taking over. THE ANTI-PATTERN, which is the most common failure: 'my teammate was stuck so I did it for them'. That is not helping, it is absorbing - the person learned nothing and you now own two jobs. The scoring version has you making them MORE capable, not less. THE STRUCTURE: notice the difficulty (often they did not ask - noticing is part of the signal), offer without condescension, teach the approach rather than the answer, then step back and let them finish and take the credit. THE DETAIL THAT LANDS: say what the OTHER PERSON went on to do afterwards. 'She then handled the next two of those herself' is the evidence that you taught rather than rescued, and it is the sentence most candidates leave out. AT AMAZON this maps to Hire and Develop the Best; AT GOOGLE it is emergent leadership plus Googleyness. Student-scale is fine: helping a classmate debug rather than sending your code, running a study session, onboarding a new member into a project's codebase, writing the README that stopped the same question being asked five times.",
          ["behavioral", "collaboration", "mentoring", "googleyness", "star", "teamwork"],
          difficulty="Easy",
          frequency="Commonly asked at Google (collaboration) and at Amazon (Hire and Develop the Best).",
          mnemonic="Helping means making them MORE capable, not doing it for them. Teach the approach, step back, let them finish and take the credit - then say what they went on to do alone. That last sentence is the proof.",
          example="SITUATION: A second-year student joined our robotics team and was assigned the sensor-calibration module. After a week he had not committed anything and had stopped coming to stand-ups. TASK: Nobody had asked me to help, but the module blocked my part of the pipeline. ACTION: I asked him to pair for an hour and quickly saw the problem was not the maths - it was that our repo had no setup instructions and he had spent five days fighting the build, too embarrassed to say so. So I did two things: I sat with him while HE fixed the build on his own machine, narrating what I was checking rather than typing, and then I wrote a ten-line SETUP.md so the next person would not lose a week. I deliberately did not touch his module. RESULT: He shipped calibration that week and went on to own the entire sensor stack for the rest of the year, including two modules nobody helped him with. The README also cut the onboarding time for the two students who joined after him from days to about an hour.",
          pitfalls="Doing the work for them and calling it help; a condescending framing ('I explained it very simply'); taking credit for their outcome; no evidence they became more independent; helping only because you were told to.",
          followups="'How did you know they needed help without them asking?' Describe the signal you noticed - it shows attentiveness. 'How do you help without undermining someone?' Ask before offering, teach the method, and let them own the commit and the credit."),

        Q("behavioral", "Tell me about a time you changed your mind because of evidence",
          "One of the highest-signal questions in the set, and candidates routinely fumble it because they think admitting a wrong belief is weakness. It is the opposite: at Google it demonstrates intellectual humility, at Amazon it hits Are Right A Lot (which is explicitly about SEEKING to disconfirm your own beliefs) and Disagree and Commit. WHAT THEY ARE TESTING: do you hold opinions loosely enough to update, and do you go looking for evidence or wait to be corrected? THE STRUCTURE, which has a specific requirement: you must state what you originally believed AND WHY it was reasonable - 'I thought the bottleneck was the model, because inference was the slowest single call in the trace' - because a belief that was never reasonable makes the story about carelessness, not about updating. Then the evidence that changed it, ideally evidence YOU went and got. Then the change, and what it cost. Then, if you can, the habit you built afterwards ('now I profile before I optimise anything'). THE STRONGEST VERSION has you changing your mind against your own interest - abandoning your own design, or conceding a teammate's approach was better after arguing for yours. That combination of backbone and humility is exactly what both companies are looking for, and it is rare enough that a good answer is memorable.",
          ["behavioral", "humility", "data-driven", "googleyness", "star", "are-right-a-lot"],
          difficulty="Medium",
          frequency="Commonly asked at Google as a Googleyness probe and at Amazon under Are Right A Lot / Disagree and Commit.",
          mnemonic="Say what you believed AND why it was reasonable, then the evidence YOU went and got, then the reversal, then the habit it created. Strongest version: you changed your mind against your own proposal.",
          example="SITUATION: In our final-year project I argued hard for a transformer-based classifier over the team's suggestion of gradient-boosted trees, on the grounds that our text features were rich. TASK: I had convinced two teammates, so I owned the decision. ACTION: Before committing three weeks to it, I insisted we spend two days on a fair comparison rather than assuming - a tuned LightGBM baseline against a fine-tuned small transformer, on the same time-based split. The trees came out one point of F1 ahead, trained in 40 seconds against 25 minutes, and ran on a laptop instead of needing a GPU we did not have reliable access to. I had been wrong about where the signal was: most of it came from four numeric columns, not the text. I said so in the next stand-up and we went with trees. RESULT: We shipped two weeks earlier than planned and used the saved time on evaluation, which is what the examiners actually asked about. What stuck with me is that I only found out because I built the baseline - if I had trusted my own argument we would have spent three weeks proving it the expensive way.",
          pitfalls="A story where changing your mind cost nothing; a belief that was never defensible, which makes it a carelessness story; being corrected by someone else rather than seeking evidence; refusing to name what you got wrong; 'I changed my mind because my manager told me to', which is compliance, not updating.",
          followups="'How do you decide when evidence is strong enough to act on?' Talk about sample size, whether the comparison was fair, and the cost of being wrong. 'Tell me about a time you did NOT change your mind and were right' - the mirror question, and worth preparing."),

        Q("behavioral", "Tell me about a time you led without authority",
          "Google calls this EMERGENT LEADERSHIP and scores it explicitly; Amazon reaches it through Ownership and Think Big. WHAT THEY ARE TESTING: as a new grad you will have no title and no direct reports, so the only leadership available to you is the kind people follow voluntarily. Can you create that? THE STRUCTURE: (1) a gap nobody owned - and note that the story is stronger when it was not assigned to you, (2) you stepped in, (3) crucially, HOW you got others to go along, which is the part candidates skip and the part being graded, and (4) you stepped BACK when the right person took over. That last beat is what distinguishes emergent leadership from someone who just likes being in charge, and Google's rubric names it directly. THE INFLUENCE MECHANISMS worth naming explicitly, because 'I convinced them' is not an answer: doing the unglamorous first slice yourself so the idea became concrete rather than a proposal; bringing data so the argument stopped being about opinions; making the change cheap for others to adopt; giving credit publicly. STUDENT-SCALE EXAMPLES that work perfectly: taking over coordination of a stalled group project, organising a study group, setting up CI for a class repo nobody had touched, running a retrospective after a bad hackathon. What does NOT work is a story where you were formally the team lead - that is authority, and the question specifically excluded it.",
          ["behavioral", "leadership", "influence", "googleyness", "star", "ownership"],
          difficulty="Medium",
          frequency="Very commonly asked at Google (emergent leadership is a scored axis) and at Amazon under Ownership.",
          mnemonic="No title, so influence is all you have: do the first slice yourself, bring data, make adoption cheap, give credit away - and STEP BACK when the right owner appears. The step-back beat is what they are listening for.",
          example="SITUATION: Our six-person capstone had no shared way of running experiments - everyone had a notebook, results were screenshots in a chat, and we twice argued about numbers nobody could reproduce. Nobody owned the problem and we had no team lead. TASK: I was not in charge of anything, but we were losing days to it. ACTION: Instead of proposing a process, I spent one evening building the smallest possible version - a script that took a config file, logged metrics to a shared CSV, and printed a comparison table - and I re-ran two people's existing experiments through it so they could see their own numbers come out identical. That made it concrete rather than a suggestion. Then I made adoption free: I converted the two most active notebooks myself so nobody had to do migration work to try it. When a teammate who was better at infrastructure than me offered to add proper experiment tracking, I handed it over and went back to my own module rather than defending my script. RESULT: All six of us were using it within a week, the reproducibility arguments stopped, and the final report had a comparison table we could actually defend to the examiners. She later extended it to log to a database, which was better than what I built.",
          pitfalls="A story where you actually had authority; 'I told everyone we should...' with no mechanism; taking over rather than enabling; never stepping back; a change nobody adopted, with no reflection on why.",
          followups="'What if people had ignored you?' Talk about finding one ally, shrinking the ask, or accepting that the problem was not painful enough yet - not about escalating. 'How did you handle someone who disagreed?' Ideally you incorporated their objection and it improved the thing."),

        Q("behavioral", "Tell me about your most challenging technical project (and how to go deep)",
          "This is the question your loop will spend the most time on, and it is really an ability probe wearing a behavioural costume. WHAT THEY ARE TESTING: technical depth (they will go two or three levels below whatever you say, so every claim must survive), your role specifically (they will separate 'the team built' from 'I built'), and whether you understand the TRADE-OFFS you made rather than just the choices. THE STRUCTURE: 30 seconds of context so they know what the system is, then the specific technical problem that made it hard, then what you tried that did NOT work, then what did and why, then the result with a number, then what you would change. THE 'WHAT DID NOT WORK' BEAT is the one candidates omit and interviewers value most - a project with no failed attempt reads as either trivial or rehearsed. HOW TO PREPARE, and this is the actual work: for your two best projects, write down the answers to 'why did you choose X over Y', 'what was the bottleneck and how did you find it', 'what would break at 100x the load', 'what is the part you are least happy with', and 'what did you measure'. Those five questions cover most follow-ups. CHOOSING THE PROJECT: pick the one where YOU made the hard decisions, not the one with the most impressive title, and never pick something you cannot explain at the level of 'and how does that library actually work?'. For an AI/ML candidate, be ready for the evaluation question - 'how did you know it was any good?' - because a project with no honest evaluation is the fastest way to lose this round.",
          ["behavioral", "technical-depth", "projects", "star", "google", "amazon"],
          difficulty="Medium",
          frequency="Always asked - typically the longest single segment of a new-grad loop.",
          mnemonic="Context (30s) -> what made it HARD -> what failed first -> what worked and why -> a number -> what you would change. Prepare five answers per project: why X over Y, where was the bottleneck, what breaks at 100x, what are you least happy with, what did you measure.",
          example="SITUATION: I built a question-answering system over my university's 400-page course handbook. TASK: The naive version - embed everything, retrieve the top 5, ask the model - was confidently wrong about a third of the time, which is worse than useless for something students would rely on. ACTION: I first assumed the model was the problem and tried a larger one, which barely moved the error rate - that was the wrong hypothesis and it cost me a week. So I built a small evaluation set instead: 60 real questions from the student forum with hand-checked answers, and I measured RETRIEVAL separately from GENERATION. Retrieval recall@5 was 61%, so in nearly 40% of cases the right passage was never in the prompt and no model could have answered. The fix was in the chunking, not the model: I had split on a fixed 1,000 characters, which cut tables in half and separated headings from their content. Chunking on section boundaries with a 15% overlap and prepending the section title to each chunk took recall@5 to 89%. RESULT: End-to-end accuracy went from 68% to 91% on the eval set, with no change of model and about a third of the token cost. What I would change: I built the evaluation set AFTER the first failed week, and it should have been the first thing.",
          examples=[
              "The five questions to prepare per project, which IS the preparation. (1) Why did you choose X over Y? (2) Where was the bottleneck and how did you FIND it - profiling, or guessing? (3) What breaks at 100x the load? (4) What is the part you are least happy with? (5) What did you measure, and against what baseline? Those five cover most follow-ups, and writing the answers down for your two best projects is maybe ninety minutes of work that pays across every loop you sit.",
              "The beat candidates omit: what failed first. A project narrative with no wrong turn reads as either trivial or rehearsed. 'I assumed the model was the problem and tried a larger one, which barely moved the error rate - that cost me a week' is the most credible sentence in the whole answer, because real work looks like that. It also sets up the recovery, which is where the actual skill shows.",
              "Going two levels down, which is what 'depth' means. Say 'I used a vector database' and the follow-up is 'which index, and why?'. Say 'HNSW' and the next is 'what does M control, and what happens if you set efSearch too low?'. There is always another level, and the honest move when you hit your limit is to say so and reason out loud: 'I don't know the internals of the graph construction, but I'd expect a higher M to mean better recall and more memory, because...'. Reasoning from what you do know beats bluffing, and interviewers are testing for exactly that boundary.",
              "For an AI/ML candidate, expect the evaluation question first. 'How did you know it was any good?' A project with no honest evaluation is the fastest way to lose this round, because it suggests you cannot tell whether your own work succeeded. Have the eval set, its size, how you built it, the baseline you beat, and the metric you chose WITH the reason. 'I built 60 hand-checked questions from the student forum and measured retrieval separately from generation' is worth more than any accuracy number.",
              "Separating 'the team built' from 'I built', without diminishing anyone. Interviewers will explicitly probe this, and the clean pattern is: name the scope, then your slice. 'The four of us built the pipeline; I owned retrieval and evaluation.' Then keep every subsequent claim inside your slice. Vague 'we' throughout makes your contribution unscoreable, and claiming the whole thing is worse - it tends to collapse when they ask a detailed question about the part you did not do.",
              "Choosing which project, using a test. Not the flashiest - the one where YOU made the hard decisions and can explain every dependency you name. If you cannot answer 'how does that library actually work?' about something in the story, either learn it before the interview or leave it out. A modest project you understand completely beats an impressive one you assembled from a tutorial, because the interview measures depth of understanding, not the size of the thing you touched.",
          ],
          pitfalls="Choosing the flashiest project rather than the one you understand; 'we' throughout so your contribution is invisible; no numbers; no failed attempt; a claim you cannot defend two levels down (never say 'I used a transformer' if you cannot explain attention); no honest evaluation.",
          followups="'What would break if this had a million users?' Have a real answer - retrieval latency, index size, cost per query. 'What is the weakest part of your design?' Naming it yourself scores far better than being shown it."),

        Q("behavioral", "How do you handle competing priorities and deadlines?",
          "For a student this is coursework versus project versus internship versus job hunting; for a new grad it becomes three teams wanting the same week. WHAT THEY ARE TESTING: do you have a SYSTEM, or do you just work harder until something breaks? And, critically, do you COMMUNICATE early when something is going to slip - because the failure mode that damages a team is not missing a deadline, it is missing it silently. THE STRUCTURE OF A GOOD ANSWER: (1) how you decide what matters - name a criterion, such as impact against effort, what blocks other people (unblocking someone else usually beats making progress alone), and what is genuinely irreversible versus merely late; (2) what you explicitly chose NOT to do, which is the beat that shows you prioritised rather than just worked more hours; (3) who you told, and WHEN - early, with options, not an apology on the deadline; (4) the outcome. THE SENTENCE THAT SCORES: 'I told my supervisor on the Tuesday that the analysis would not be ready by Friday, and offered either a partial result on Friday or the full one on Monday - she took the partial.' That is what a manager wants to hear, because it makes their problem solvable while there is still time. AVOID: 'I just work late', which signals no prioritisation and no sustainability; 'I do everything', which is either false or means everything was done badly; and any story where the person depending on you found out at the deadline.",
          ["behavioral", "prioritisation", "time-management", "communication", "star", "deliver-results"],
          difficulty="Easy",
          frequency="Commonly asked of students and new grads at both Google and Amazon (Deliver Results / Ownership).",
          mnemonic="Have a CRITERION (impact vs effort, who is blocked, what is irreversible), say what you dropped, and escalate EARLY with options rather than late with an apology. 'I worked late' is not prioritisation.",
          example="SITUATION: In one three-week stretch I had a database coursework deadline, the first working demo of our capstone, and an internship assignment my mentor was waiting on. TASK: All three had the same fortnight and honestly could not all be done well. ACTION: I ranked them by who was BLOCKED: my mentor could not start integration until my endpoint existed, so that came first even though it was the smallest piece; the capstone demo had three other people depending on it, so second; the coursework only affected me, and the marking scheme meant losing the top grade band on one assignment cost me very little overall. I messaged my mentor on day two with the date I would have the endpoint, and I told my project group early that I would deliver the model but not the UI, so someone else could pick that up while there was still time. Then I deliberately did the coursework to a good-not-perfect standard and stopped. RESULT: The endpoint landed two days early, the demo worked, and the coursework came in at about 78% rather than the 90% I would have wanted. That trade was the right one, and the important part was that both other parties knew my plan on day two rather than day fourteen.",
          pitfalls="'I work weekends' as the whole answer; claiming you delivered everything perfectly; no criterion, so it sounds like you did whatever was loudest; telling people late; no example of something you deliberately dropped.",
          followups="'What if your manager says all three are top priority?' Present the trade explicitly - 'here is what each costs and what slips; which do you want first?' - and make them choose, which is legitimate and expected. 'How do you estimate?' Break it down, add buffer for the unknown parts, and re-estimate out loud when reality disagrees."),

        Q("behavioral", "Tell me about a time you made a mistake that affected other people",
          "Distinct from 'your biggest failure' because it adds the element that actually tests character: someone else paid for it. WHAT THEY ARE TESTING: whether you disclose fast or hide, whether you fix the CAUSE or just the symptom, and whether you can talk about your own error without either minimising it or wallowing. THE ARC: what you did, how you found out (finding it yourself is better than being told), WHO YOU TOLD AND HOW QUICKLY - this is the beat that matters most, and 'within twenty minutes I told the two people affected' is worth more than any technical fix - what you did to contain the damage, then the fix, then the SYSTEMIC change so the same class of mistake cannot recur. That last part is the difference between an apology and an engineer: 'I added a confirmation step / a test / a check in CI so nobody can do that again' turns your mistake into a permanent improvement for everyone. TONE MATTERS: own it in the first person without a scapegoat, and without excessive self-flagellation, which reads as fragile rather than accountable. CHOOSING THE STORY: it must be a real mistake with real consequences - 'I once worked too hard' is transparent and insulting - but it should not be a catastrophic judgement or integrity failure. Deleting data, breaking a shared build, shipping a bug that cost a teammate a day, a wrong number in a report someone presented: all good. And practise saying the sentence 'that was my mistake' cleanly, because interviewers notice candidates who cannot.",
          ["behavioral", "failure", "ownership", "accountability", "star", "earn-trust"],
          difficulty="Medium",
          frequency="Always asked in some form - at Amazon under Earn Trust and Ownership, at Google as a humility probe.",
          mnemonic="Own it in the first person, disclose FAST, contain, fix, then make the class of mistake impossible (a test, a check, a guard). The systemic fix is what turns a confession into an engineering story.",
          example="SITUATION: During my internship I wrote a migration script to backfill a column and ran it against what I believed was the staging database. TASK: It was production, and it overwrote the column for about 12,000 rows with a default value. ACTION: I noticed within a couple of minutes because the row count in the output did not match staging's size. I did not try to quietly fix it - I told my mentor immediately and, because it was 4pm, I said it out loud in the team channel too so nobody built on the bad data. We restored the column from the previous night's backup within the hour, and I wrote the reconciliation query to confirm every affected row matched the backup. Then I did the part I actually care about: the root cause was that my shell prompt did not show which environment I was connected to, and the script took a connection string with no confirmation. I added an environment banner to the shared setup script and a required --confirm-production flag to the migration tool. RESULT: Total data-loss window was about 50 minutes with no downstream impact, and two other interns later told me the environment banner had stopped them making the same mistake. My mentor's feedback was that telling the channel immediately was the right call, and that is the habit I kept.",
          examples=[
              "The arc, with the beat that actually scores. Ran a backfill against what I believed was staging; it was production, and about 12,000 rows had a column overwritten. Noticed within two minutes because the output row count did not match staging's size. Told my mentor immediately AND said it in the team channel, because it was late afternoon and people were about to build on that data. Restored from the previous night's backup inside the hour and wrote the reconciliation query proving every row matched. The graded moment is not the restore — it is that the disclosure happened before the fix, in public, while it was still embarrassing.",
              "Why the systemic fix is what separates this from an apology. The root cause was that my shell prompt did not show the environment and the migration tool accepted a connection string with no confirmation. So: an environment banner in the shared setup script, and a required --confirm-production flag. Two other interns later said the banner had stopped them doing the same thing. 'I was more careful afterwards' is a resolution; 'I made it impossible for the next person' is engineering, and interviewers hear the difference immediately.",
              "How this differs from the biggest-failure question, since you will likely get both. FAILURE is about judgement: what you got wrong and how your process changed. THIS is about character: how fast you disclosed, whether you hid it, how you rebuilt trust. The same event can serve both, but the emphasis moves — there you spend your time on the wrong decision and the structural fix, here on who you told and when. Decide in advance which of your stories serves which, because reusing the identical telling in one loop is noticeable.",
              "The tone calibration, which is narrower than people think. Deflecting ('the configs were confusingly named') reads as blaming the environment even when true. Wallowing — two minutes of self-criticism — reads as fragile rather than accountable. The calibrated version states the error plainly in one sentence, spends the rest on containment and the fix, and mentions the contributing factor only as the thing you then fixed. Practise saying 'that was my mistake' cleanly; interviewers notice candidates who cannot get the words out.",
              "Choosing a story with real stakes but survivable ones. Good: data loss, a broken shared build, a bug that cost a teammate a day, a wrong number in a report someone presented, force-pushing over a colleague's branch. Bad in one direction: 'I once mislabelled a variable' — no stakes, nothing revealed. Bad in the other: anything involving dishonesty or a judgement failure severe enough to be a hiring risk. Student-scale is completely fine; what matters is that someone else paid for it.",
              "The probes, and what each is checking. 'Who did you tell, and when?' — the whole question in one, and a delay of hours is a different answer from a delay of minutes. 'What did your manager say?' — real feedback makes the story credible; a story where nobody reacted sounds invented. 'Has it happened again?' — should be no, BECAUSE of the systemic fix. 'Why the whole channel rather than just your mentor?' — because others were about to build on the bad data, which shows you thought about blast radius rather than about your own embarrassment.",
          ],
          pitfalls="A fake mistake; blaming the process, the documentation or a teammate; hiding it and fixing it quietly (disqualifying if it comes through in the story); no systemic fix; over-apologising for five minutes; a mistake with no actual consequence.",
          followups="'What did your manager say?' Real feedback makes the story credible. 'Has it happened again?' The answer should be no, because of the systemic fix - and if a related thing did happen, say what you learned the second time."),

        Q("behavioral", "How do you handle a group project where someone is not pulling their weight?",
          "A specifically student-shaped question, asked because it is the closest available proxy for a real team problem - and interviewers know the honest answer is uncomfortable. WHAT THEY ARE TESTING: whether your first instinct is to escalate, to absorb, or to address it; and whether you can distinguish 'will not' from 'cannot'. THE ORDER THAT SCORES: (1) find out WHY before deciding what it is - the most common causes are being stuck and embarrassed to say so, not understanding what was expected, or a genuine personal crisis, and only occasionally is it indifference; (2) talk to them directly and privately, asking rather than accusing; (3) make the work visible and smaller - a shared board with named, small tasks makes drift obvious early and gives a stuck person a rung to grab; (4) adjust the plan honestly if they genuinely cannot deliver, rather than pretending; (5) escalate to the supervisor only after a direct attempt, and framed as 'here is what we tried' rather than as a complaint. THE TRAP: the answer most students give is 'I just did their part so the project would not suffer'. Say that and you have told the interviewer you will silently absorb an underperforming teammate's work, hide the problem from your manager, and burn out - three things a hiring manager specifically does not want. Doing the work is sometimes the right short-term call for a deadline, but only alongside addressing the cause. THE STRONGEST STORIES include a moment where you found out the reason and it changed what you did.",
          ["behavioral", "teamwork", "conflict", "collaboration", "star", "student"],
          difficulty="Medium",
          frequency="Very commonly asked of students and new grads at both companies.",
          mnemonic="Find out WHY before deciding WHAT. Ask privately, make tasks small and visible, replan honestly, escalate only after a direct attempt - and never let 'I just did it myself' be the whole answer.",
          example="SITUATION: In a five-person systems project, one member missed two consecutive integration deadlines and stopped replying in the group chat, with the demo two weeks out. TASK: His component sat between mine and the front end, so nothing could be tested end to end. ACTION: Rather than assuming he had checked out, I messaged him directly and asked if he was okay. He was dealing with a family illness and had been too embarrassed to say anything to four people at once. So we changed the plan honestly instead of pretending: I took over the integration layer since it was on my critical path anyway, we cut one optional feature from his component to shrink it to something he could finish, and I told the supervisor that we were rescoping - not that someone had failed, because that framing would have been both unkind and inaccurate. We also moved to a shared board with small named tasks so nobody could silently drift for two weeks again. RESULT: We demoed on time with one fewer feature, he delivered the reduced scope, and the supervisor's feedback was specifically that the rescoping decision was made early enough to be useful. If I had assumed indifference and escalated, I would have been wrong and the outcome would have been worse.",
          pitfalls="'I did their work' as the entire answer; escalating to the supervisor first; assuming laziness; a public confrontation; no change to how the team worked afterwards, so the same drift could recur.",
          followups="'What if the reason had been that they simply did not care?' Then you address it directly, adjust the plan, and escalate with a factual record - the process is the same, the conclusion differs. 'How would you prevent it next time?' Small visible tasks and short check-ins surface drift in days rather than weeks."),

        Q("behavioral", "Why software engineering, and why AI/ML specifically?",
          "It sounds like small talk and it is not. WHAT THEY ARE TESTING: is your interest specific and durable, or did you pick the field because it is where the jobs are? Interviewers hear the generic version fifty times a week ('I've been passionate about technology since childhood'), and specificity is the entire differentiator. THE STRUCTURE: (1) a concrete ORIGIN - one specific moment or project, not a general love of computers; (2) what you did about it that nobody made you do, because unprompted effort is the strongest evidence of genuine interest; (3) why AI/ML rather than adjacent fields, with a real reason - and 'because it is the future' is not one; (4) what kind of AI/ML work, which is where you show you understand the field has parts. THAT LAST POINT MATTERS MORE THAN CANDIDATES REALISE: saying 'I want to do machine learning' to an SDE interviewer is vague, whereas 'I'm drawn to the engineering side - the serving, evaluation and data quality parts, because in my projects that is where the difficulty actually was' tells them exactly which team you fit and is far more credible from a new grad. IT ALSO PROTECTS YOU: a candidate who claims to want cutting-edge research will be measured against research depth they do not have, while a candidate who says they want to build reliable ML systems is being measured on exactly the skills a new-grad SDE role needs. HONESTY BEATS AMBITION here - a well-argued modest answer outperforms an over-claimed one every time.",
          ["behavioral", "motivation", "career", "ai", "ml", "interview-strategy"],
          difficulty="Easy",
          frequency="Very commonly asked - it opens or closes most new-grad loops.",
          mnemonic="Be SPECIFIC: one concrete origin, one thing you did unprompted, one real reason for AI/ML over adjacent fields, and which PART of AI/ML you want. 'It's the future' and 'passionate since childhood' are the two answers they hear all day.",
          example="'The honest origin is unglamorous. In second year I built a small model to predict which of my college's library study rooms would be free, because I kept walking across campus for nothing. It got 80% accuracy in an afternoon and I was pleased with myself - and then it was wrong every single week of exams, because the pattern it had learned did not exist any more. Nobody had set that as an assignment; I just wanted the rooms. Chasing why it failed is what got me into data drift, evaluation and eventually into the systems side of ML. That is also why I'm interested in ML engineering rather than research: in every project I've done, the modelling was the easy part and the difficulty was data quality, evaluation and keeping the thing working after the first week. I would rather be the person making models reliable in production than the person squeezing out the last point of accuracy, and this team's work on serving infrastructure is exactly that.'",
          examples=[
              "A full answer, with the origin deliberately unglamorous. 'In second year I built a small model to predict which library study rooms would be free, because I kept walking across campus for nothing. It got 80% accuracy in an afternoon and I was pleased with myself — and then it was wrong every week of exams, because the pattern it had learned no longer existed. Nobody set that as an assignment; I just wanted the rooms. Chasing why it failed is what got me into data drift and evaluation, and eventually into the systems side of ML.' A small real story beats a grand claimed one, because it is checkable.",
              "Why the answer must name WHICH PART of AI/ML you want. Saying 'I want to do machine learning' to an SDE interviewer is vague and, worse, invites them to measure you against research depth you do not have. 'I'm drawn to the engineering side — serving, evaluation, data quality — because in my projects that is where the difficulty actually was' tells them exactly which team you fit and is far more credible from a new grad. It also protects you: you are now being assessed on the skills the role needs.",
              "The unprompted-effort test. Interviewers weight what you did that NOBODY ASKED YOU TO DO far above coursework, because coursework is evidence of compliance and side projects are evidence of interest. A course you took is weak; a thing you built because it annoyed you is strong. If your only material is coursework, anchor it to something you then extended beyond the brief — and say that you did.",
              "The two answers they hear all day, and why each fails. 'I've been passionate about technology since childhood' — unfalsifiable, says nothing, and is true of every candidate in the queue. 'AI is the future' — a claim about the industry, not about you, and it is what someone says when they picked the field for the job market. Money and job availability are perfectly legitimate REASONS and terrible ANSWERS; nobody is offended by them, they simply do not distinguish you.",
              "Honesty beats ambition here, which surprises people. A well-argued modest answer outperforms an over-claimed one every time, because the over-claim gets tested. If you say you want to do research, expect 'what's the last paper you read and what did you disagree with?'. If you say you want to build reliable ML systems, expect questions about monitoring and evaluation — which you can actually answer. Claim the thing you can defend two levels down.",
              "The follow-ups to prepare. 'What's the last ML paper or article you read?' — have a real, recent one with an OPINION about it, not a summary. 'Where do you see yourself in five years?' — show a direction, admit uncertainty honestly, and connect it to what this role would teach you. 'Why not a PhD?' — if you are choosing industry over research, have a genuine reason (you like shipping, you want feedback from users) rather than a dismissive one.",
          ],
          pitfalls="'Passionate about technology since I was young'; 'AI is the future'; naming money or job availability as the reason (true, and not the answer); claiming research ambitions you cannot back with reading or projects; being unable to name a single specific thing you did unprompted.",
          followups="'What is the last ML paper or article you read?' Have a real, recent answer with an opinion about it. 'Where do you see yourself in five years?' Show a direction, admit uncertainty honestly, and connect it to what the role would teach you."),

        Q("behavioral", "Building a story bank: six stories that cover thirty questions",
          "The single highest-leverage piece of behavioural preparation, and almost nobody does it. THE INSIGHT: there are not thirty behavioural questions, there are about six story SHAPES, and one well-built story answers several prompts with a shift of emphasis. Preparing per-question means memorising thirty answers badly; preparing per-story means having six you know cold and can re-angle live. THE SIX TO BUILD: (1) a DELIVERY story - you shipped something hard under a real constraint (covers Deliver Results, Ownership, prioritisation, 'most challenging project'); (2) a FAILURE story - you got something wrong and fixed the cause (covers failure, mistake affecting others, Earn Trust, humility, feedback); (3) a CONFLICT story - you disagreed with someone and resolved it (covers difficult teammate, Have Backbone, disagreeing with a manager, collaboration); (4) an AMBIGUITY story - you moved without complete information (covers ambiguity, Bias for Action, Are Right A Lot, incomplete data); (5) a LEARNING story - you taught yourself something hard, fast, because you needed it (covers Learn and Be Curious, new technology, out of your depth); (6) a HELPING story - you made someone else more effective (covers collaboration, mentoring, Hire and Develop the Best, Googleyness). HOW TO BUILD EACH: write it in STAR, keep it under two minutes spoken, and make sure it contains a NUMBER, a DECISION you made, and something you would do differently. Then build the index: list the questions each story can answer and which detail to emphasise for each. THE DELIVERY SKILL that separates good from great: when a question arrives, take two seconds to pick the story and the ANGLE, then start with a one-sentence headline ('This is about a time I shipped a rescoped feature rather than a late complete one') so the interviewer knows where you are going.",
          ["behavioral", "star", "preparation", "interview-strategy", "story-bank"],
          difficulty="Easy",
          frequency="Applies to every behavioural round at every company - this is the preparation method, not a question.",
          mnemonic="Six stories, not thirty answers: DELIVERY, FAILURE, CONFLICT, AMBIGUITY, LEARNING, HELPING. Each in STAR, under two minutes, containing a number, a decision, and a 'what I'd change'. Then index which questions each one answers.",
          example="One story, three angles. A capstone where you rescoped a feature to hit a demo date. Asked about DELIVER RESULTS, emphasise the deadline, the trade you made and the number. Asked about DEALING WITH AMBIGUITY, emphasise that the requirement was unclear, the assumption you wrote down, and the checkpoint. Asked about CONFLICT, emphasise the teammate who wanted to ship it complete and late, how you argued it, and how you converged. Same facts, three different first sentences - and the interviewer never hears a recycled answer because you led with the part they asked about.",
          examples=[
              "The six shapes, and what each one covers. DELIVERY (shipped something hard under a constraint) covers Deliver Results, Ownership, prioritisation, 'most challenging project'. FAILURE (got it wrong, fixed the cause) covers failure, mistake affecting others, Earn Trust, humility, feedback. CONFLICT (disagreed and resolved it) covers difficult teammate, Have Backbone, disagreeing with a manager. AMBIGUITY (moved without complete information) covers Bias for Action, Are Right A Lot. LEARNING (taught yourself something fast) covers Learn and Be Curious. HELPING (made someone else effective) covers collaboration, mentoring, Googleyness. Six stories, about thirty prompts.",
              "One story, three angles - the skill that makes six stories enough. A capstone where you rescoped a feature to hit a demo date. Asked about DELIVER RESULTS: lead with the deadline, the trade, the number. Asked about AMBIGUITY: lead with the unclear requirement, the assumption you wrote down, the checkpoint. Asked about CONFLICT: lead with the teammate who wanted it complete-and-late, how you argued it, how you converged. Same facts, three different first sentences - and the interviewer never hears a recycled answer because you led with the part they asked about.",
              "The headline sentence, which is the delivery skill. When a question lands, take two seconds, pick the story AND the angle, then open with one sentence saying where you are going: 'This is about a time I shipped a rescoped feature rather than a late complete one.' The interviewer now knows the shape and can follow the detail. Without it they spend your first thirty seconds working out which question you think you are answering, which is thirty seconds of your two minutes gone.",
              "What each story must contain, as a checklist to write against. A NUMBER (latency, percentage, days saved, people affected) - without one it is an anecdote. A DECISION you personally made, stated as 'I decided', because a story where things merely happened to you scores nothing. A 'WHAT I'D DO DIFFERENTLY', because it is the most common follow-up in the entire set and 'nothing' is a failing answer. Under two minutes spoken - time yourself, since most first drafts run four.",
              "Why not to memorise word-for-word. A recited answer sounds recited, and it shatters on the first follow-up ('what did your teammate think?') because you rehearsed a paragraph rather than knowing the events. Write each story as five bullets - situation, task, the two or three actions, result with a number, lesson - and speak from the bullets. You will phrase it differently every time, which is exactly right.",
              "Two practical constraints people miss. First, Amazon interviewers COMPARE NOTES afterwards, and each round asks about different principles - so telling the same story in four rounds is visible and reads as a thin CV. Build six, and know which two rounds each is for. Second, do not source all six from one project: 'my final-year project' six times says you have done one thing. Spread them across coursework, an internship, a personal project and a group assignment - and a genuinely non-technical one (a society, a team, a part-time job) is fine and often more memorable.",
          ],
          pitfalls="Memorising word-for-word, which sounds robotic and collapses under a follow-up; six stories from the same project (you will run out and it looks thin); stories with no number; forgetting that Amazon interviewers compare notes, so reusing the identical story in four rounds is visible - vary them; no 'what I'd do differently' prepared, which is the most common follow-up in the set.",
          followups="'Do you have another example?' - the reason you need more than one story per shape. 'What did your team think?' - prepare the other people's perspective for each story, since that is where thin stories fall apart."),

        Q("behavioral", "What questions should you ask the interviewer?",
          "Every interview ends here, it is scored, and 'I have no questions' is a genuinely bad answer - it reads as no curiosity, which at Google is a named rubric item. WHAT THEY ARE TESTING: whether you are evaluating them too, and what you actually care about. Note also that this is often your last few minutes with the person writing your feedback, so it is worth using well. THE FOUR CATEGORIES worth drawing from, one or two each: THE WORK - 'what does a typical week look like for a new grad on this team?', 'what is the project I'd most likely start on?', 'how much of the work is new development versus maintaining what exists?'. THE TEAM AND YOU - 'how does the team decide what to work on?', 'what does the onboarding look like?', 'how do new engineers get feedback in the first six months?'. THEIR EXPERIENCE - 'what surprised you most in your first year here?', 'what is the hardest problem the team is working on right now?' - people enjoy answering these and you learn a lot. THE HONEST ONE, which is the most useful and rarely asked: 'what is the most frustrating part of working on this team?' A candid answer tells you more than everything else combined, and a non-answer tells you something too. WHAT NOT TO ASK: anything answered on the careers page (it shows you did not look), compensation or holidays with an engineer rather than the recruiter, 'how did I do?', or a question so obviously engineered to impress that it is transparent. PREPARE ABOUT SIX, because two will be answered during the interview, and adapt at least one to something the interviewer actually said - that is the part that shows you were listening.",
          ["behavioral", "questions", "interview-strategy", "googleyness", "curiosity"],
          difficulty="Easy",
          frequency="Every interview ends with this, and it is part of the written feedback.",
          mnemonic="Prepare six, expect two to be answered already, and adapt one to something they SAID. Best single question: 'what's the most frustrating part of working here?' Never: nothing, salary-with-the-engineer, or anything on the careers page.",
          example="A strong close: 'You mentioned earlier that the team is moving the feature pipeline off the nightly batch job. What is driving that - latency, cost, or correctness? And what does that mean for someone joining in the next six months: would a new grad be working on the migration, or on what sits on top of it?' It proves you listened, it is technically specific, and the answer tells you exactly what your first year would look like. Contrast with 'What is the company culture like?', which they will answer generically because it is a generic question.",
          pitfalls="Having no questions; asking something the job description answers; asking about compensation, promotion timelines or holidays with the engineering interviewer rather than the recruiter; asking 'how did I do?', which puts them in an awkward position; asking a question you clearly do not care about.",
          followups="If they answer everything during the interview, say so honestly and pivot: 'you covered my main ones - can I ask instead what you'd want someone joining to be good at on day one?' That is a genuine question and it never fails."),
    ]

    return entries
