"""Behavioral interview question bank — 100+ common questions with STAR
model answers, tuned for a senior Technical Program Management / Director
run.

These are ADAPTABLE TEMPLATES, not scripts. The model answers use a small
set of recurring "signature scenarios" (a platform migration, a payments
launch recovery, an operating-model change, a regulated launch, a Sev1
incident, an Eng/Product scope conflict) so they read coherently — swap in
your own experiences and real numbers (the [bracketed] bits) before you
rehearse. The value is the STRUCTURE and the altitude of the answer.

Served read-only by routes/interview_prep.py at /api/interview-prep/questions.
"""

CATEGORIES = {
    "leadership": "Leadership & Ownership",
    "ambiguity": "Ambiguity & Change",
    "conflict": "Conflict & Difficult People",
    "delivery": "Program Delivery & Execution",
    "failure": "Failure & Learning",
    "stakeholders": "Stakeholder & Exec Management",
    "prioritization": "Prioritization & Trade-offs",
    "collaboration": "Cross-functional Collaboration",
    "decision": "Decision-making & Judgment",
    "people": "People & Team Development",
    "strategy": "Strategy & Vision",
    "influence": "Influence Without Authority",
    "risk": "Risk & Crisis Management",
    "communication": "Communication",
    "customer": "Customer & Business Orientation",
    "growth": "Growth, Feedback & Positioning",
}


def _q(cat, q, s, t, a, r, tip):
    return {"cat": cat, "q": q, "s": s, "t": t, "a": a, "r": r, "tip": tip}


QUESTIONS = [
    # ─────────── Leadership & Ownership ───────────
    _q("leadership",
       "Tell me about a time you led a team through a major change.",
       "Our org was migrating a legacy monolith to microservices across [8] teams with heavy skepticism.",
       "As TPM I owned landing the migration without stalling the product roadmap.",
       "I set a phased plan, created a shared scorecard, ran weekly de-risking reviews, and over-communicated the 'why' to every team.",
       "We migrated [80%] of services in [2] quarters with zero customer-facing incidents and lifted deploy frequency [3x].",
       "Anchor on how you carried people through the change emotionally, not just the mechanics."),
    _q("leadership",
       "Describe a time you led without any formal authority.",
       "I was accountable for a cross-org launch but none of the engineers reported to me.",
       "I had to align [5] teams that each had their own priorities and managers.",
       "I built credibility through a clear plan, made their wins visible upward, and removed blockers faster than anyone else could.",
       "Teams started routing decisions through me by choice; we shipped on the committed date.",
       "Emphasize influence earned through trust and usefulness, not title."),
    _q("leadership",
       "Give an example of motivating a demotivated or burned-out team.",
       "After a slipped payments launch, the team was demoralized and attrition risk was rising.",
       "I needed to rebuild momentum and belief without pretending the miss didn't happen.",
       "I ran a blameless retro, cut scope to a winnable milestone, celebrated small wins publicly, and protected the team's focus time.",
       "We shipped the reduced launch in [6] weeks and voluntary attrition dropped to zero that half.",
       "Show emotional intelligence: name the low, then engineer an early win."),
    _q("leadership",
       "Tell me about a time you took ownership of a problem outside your remit.",
       "A recurring data-quality issue was hurting [3] products but sat in nobody's charter.",
       "No single team owned it, so it kept getting dropped.",
       "I volunteered to own it end-to-end, mapped the root cause across teams, and stood up a lightweight governance forum.",
       "Defect rate fell [40%] and the forum became the permanent home for cross-cutting data issues.",
       "Great senior signal — you close ownership gaps instead of pointing at them."),
    _q("leadership",
       "Describe leading a high-stakes initiative with a tight, immovable deadline.",
       "We had a regulatory deadline to ship compliance changes or face fines.",
       "I owned delivery across Eng, Legal, and Ops with no room to slip.",
       "I built a critical-path plan, ran daily standups in the final stretch, pre-cleared decisions with Legal, and tracked risks in a live RAID log.",
       "We shipped [3] days early and passed the external audit clean.",
       "Show your operating cadence tightening as risk rises."),
    _q("leadership",
       "Tell me about a time you made an unpopular decision.",
       "Two teams wanted to keep building parallel internal tools that overlapped.",
       "I had to consolidate onto one platform, which meant sunsetting a team's pet project.",
       "I made the call transparently with the data, gave the losing team a real role on the surviving platform, and owned the message myself.",
       "We saved [~30%] of maintenance cost and the merged team shipped faster.",
       "Own the decision AND the fallout — don't hide behind consensus."),
    _q("leadership",
       "Describe a time you grew someone into a bigger role.",
       "A strong senior engineer wanted to move toward program leadership.",
       "I needed delivery help and they needed a stretch.",
       "I delegated a workstream to them, coached weekly, gave air cover, and made their impact visible to leadership.",
       "They were promoted to lead TPM within [a year] and now own that program.",
       "Senior leaders are measured by who they grow — make that explicit."),

    # ─────────── Ambiguity & Change ───────────
    _q("ambiguity",
       "Tell me about a time you had to make progress with incomplete information.",
       "We had to commit to a launch date before the architecture was fully scoped.",
       "Leadership needed a credible date; engineers wanted more certainty first.",
       "I framed assumptions explicitly, committed to a date with a confidence range, and set checkpoints to re-forecast as we learned.",
       "We hit the date within the stated range and leadership trusted the forecasting model afterward.",
       "Show comfort deciding with 70% information and a plan to close the rest."),
    _q("ambiguity",
       "Describe a project with unclear or constantly shifting requirements.",
       "A new product line had a vague brief and a founder who kept changing scope.",
       "I had to create enough stability for engineers to build.",
       "I drove a lightweight PRD, established a weekly scope-change board, and made trade-offs visible so every 'add' showed its cost.",
       "Churn dropped sharply and we shipped an MVP that validated the bet.",
       "Your job is turning ambiguity into structure others can execute against."),
    _q("ambiguity",
       "Tell me about a time priorities changed suddenly.",
       "Mid-quarter, leadership pulled us onto an urgent competitive response.",
       "I had to re-plan a committed roadmap in days without breaking trust.",
       "I re-sequenced work, renegotiated commitments with impacted stakeholders early, and protected one must-keep deliverable.",
       "We landed the competitive response on time and only slipped [one] non-critical item.",
       "Highlight fast, transparent re-commitment — not heroics."),
    _q("ambiguity",
       "Describe operating in a domain that was completely new to you.",
       "I moved into a payments program with deep regulatory complexity I didn't know.",
       "I had to lead credibly without the domain depth of my team.",
       "I ran a rapid learning plan, paired with SMEs, asked sharp questions, and focused my value on structure and decision-forcing.",
       "I was running the program confidently within [weeks] and caught two risks the team had missed.",
       "Senior leaders add value through judgment and structure, not being the SME."),
    _q("ambiguity",
       "Tell me about a time you created order out of chaos.",
       "A red program had [4] workstreams, no single plan, and constant surprises.",
       "I was brought in to stabilize it.",
       "I built one integrated plan, a single source of truth, a weekly operating rhythm, and a clear RAID log.",
       "Within [a month] the program was predictable and moved from red to green.",
       "This is the classic TPM turnaround — lead with your operating system."),
    _q("ambiguity",
       "Describe a decision that had no clear owner.",
       "A cross-team API contract was stuck because no one felt they owned the call.",
       "The stall was blocking [3] teams.",
       "I named the decision, gathered the trade-offs, proposed a default, and set a 'decide by' date that forced closure.",
       "We unblocked in [days] and I codified a decision-owner rule to prevent repeats.",
       "Show you drive decisions to closure, not just facilitate."),
    _q("ambiguity",
       "Tell me about navigating your team through a reorg or restructuring.",
       "Two teams merged and roles, ownership, and morale were all uncertain.",
       "I had to keep delivery going through the disruption.",
       "I clarified new ownership fast, over-communicated, protected key people, and kept one shared goal front and center.",
       "We held delivery steady and retained every key contributor.",
       "Stability and candor are the leadership signals here."),

    # ─────────── Conflict & Difficult People ───────────
    _q("conflict",
       "Tell me about a conflict with a peer or stakeholder.",
       "A product lead and I disagreed hard on cutting scope to hit a date.",
       "We needed one aligned plan and were running out of time.",
       "I moved the debate to shared data, separated the goal from the positions, and found a middle path that protected the launch-critical scope.",
       "We aligned, shipped on time, and the relationship got stronger from handling it well.",
       "Show you attack the problem, not the person, and reach durable alignment."),
    _q("conflict",
       "Describe a time you disagreed with your manager.",
       "My director wanted to commit to a date I believed was unrealistic.",
       "I had to push back without undermining them.",
       "I brought the risk data privately, proposed a phased alternative, and committed to fully support whatever they decided.",
       "They adjusted to a phased plan and later thanked me for the candid pushback.",
       "'Disagree and commit' — show the private candor and the public support."),
    _q("conflict",
       "Tell me about mediating a conflict between two teams.",
       "Eng and Data teams were blaming each other for a broken pipeline.",
       "The finger-pointing was stalling a fix customers needed.",
       "I got both in a room, focused on the shared customer impact, facilitated a joint root-cause, and split clear ownership of the fix.",
       "The pipeline was fixed in [days] and I set up a shared on-call to prevent repeats.",
       "Neutral facilitation plus a structural fix beats picking a winner."),
    _q("conflict",
       "Describe working with a difficult or resistant stakeholder.",
       "A senior stakeholder repeatedly blocked a change they saw as a threat.",
       "I needed their cooperation to land the program.",
       "I met them 1:1 to understand the real concern, addressed it directly, and gave them a visible stake in the outcome.",
       "They went from blocker to advocate and championed the rollout.",
       "Curiosity about the underlying fear usually unlocks the resistance."),
    _q("conflict",
       "Tell me about a time you received harsh or unfair criticism.",
       "In a review, an exec criticized my program's status as 'too optimistic'.",
       "I had to respond without defensiveness and rebuild confidence.",
       "I listened, acknowledged the valid part, tightened my risk reporting, and followed up with a more rigorous forecast.",
       "The exec's trust recovered and my reporting became the team's template.",
       "Show maturity: take the signal, drop the ego, improve the system."),
    _q("conflict",
       "Describe a time you had to say no to a senior leader.",
       "A VP wanted a feature added late that would have risked the launch.",
       "I had to decline while keeping the relationship intact.",
       "I said no with the trade-off math, offered a fast-follow path, and let them make the final informed call.",
       "They accepted the fast-follow; we launched safely and shipped their feature the next cycle.",
       "A confident, data-backed no with an alternative reads as senior, not obstinate."),
    _q("conflict",
       "Tell me about a disagreement on technical direction.",
       "Two staff engineers disagreed on build-vs-buy for a core component.",
       "As TPM I had to get to a decision without overreaching on tech I didn't own.",
       "I framed the decision criteria, ran a timeboxed spike, and forced a decision against the criteria rather than opinion.",
       "We chose buy, saved [a quarter] of build time, and both engineers backed the call.",
       "Own the decision PROCESS; let the experts own the technical depth."),

    # ─────────── Program Delivery & Execution ───────────
    _q("delivery",
       "Tell me about the most complex program you've delivered.",
       "I led a company-wide platform migration spanning [8] teams and [3] regions.",
       "I owned the plan, dependencies, risks, and the executive narrative.",
       "I built an integrated critical-path plan, ran a tight operating cadence, managed a live dependency map, and escalated early.",
       "We delivered on time, cut infra cost [~25%], and it became the template for future migrations.",
       "Pick your biggest scope-of-impact story and quantify it."),
    _q("delivery",
       "Describe delivering under an aggressive deadline.",
       "We had [10] weeks to launch a feature tied to a partner commitment.",
       "The original scope needed [16] weeks.",
       "I ruthlessly cut to the minimum lovable scope, parallelized workstreams, and pre-cleared decisions to remove wait time.",
       "We launched on the [10]-week date with the core value intact and fast-followed the rest.",
       "Show scope discipline and dependency parallelization, not just overtime."),
    _q("delivery",
       "Tell me about a launch that went really well.",
       "We launched a new checkout flow to millions of users.",
       "I owned the end-to-end launch and rollback readiness.",
       "I ran a staged rollout with clear go/no-go gates, real-time dashboards, and a war room for the first [48] hours.",
       "Zero Sev1s, conversion up [X%], and the playbook was reused for later launches.",
       "Highlight the launch rigor (gates, monitoring, rollback) that made 'went well' non-accidental."),
    _q("delivery",
       "Describe managing a program with many dependencies.",
       "My program depended on [6] other teams' deliverables to land.",
       "Any one slip could cascade into a miss.",
       "I mapped every dependency with owners and dates, tracked them weekly, and negotiated buffers on the riskiest ones.",
       "We absorbed [2] upstream slips without missing our date.",
       "Dependency management is the core TPM craft — show your system for it."),
    _q("delivery",
       "Tell me about how you track and drive a program to completion.",
       "I inherited a program with no reliable status signal.",
       "Leadership couldn't tell if we'd make it.",
       "I stood up a single source of truth, a red/amber/green scorecard, weekly reviews, and clear escalation paths.",
       "Status became trustworthy and we hit every remaining milestone.",
       "Describe your operating mechanisms concretely — that's the senior tell."),
    _q("delivery",
       "Describe a time you cut scope to hit a date.",
       "Halfway through a launch, our burn-up showed we'd miss by [3] weeks.",
       "The date was tied to a marketing moment we couldn't move.",
       "I ranked features by value, negotiated a v1 with stakeholders, and moved the rest to a committed fast-follow.",
       "We hit the date; the trimmed features shipped [3] weeks later with no customer impact.",
       "Show scope as a lever you manage deliberately, with stakeholder buy-in."),
    _q("delivery",
       "Tell me about coordinating a globally distributed team.",
       "My program ran across teams in [3] time zones with little overlap.",
       "Hand-offs were slow and context was getting lost.",
       "I set up async-first updates, a follow-the-sun hand-off ritual, and a couple of anchored overlap meetings.",
       "Cycle time dropped and the teams reported far less rework.",
       "Emphasize async operating design, not just 'we had more meetings'."),

    # ─────────── Failure & Learning ───────────
    _q("failure",
       "Tell me about a time you failed.",
       "I committed to a launch date on optimistic estimates and we missed by [a quarter].",
       "I owned the miss to leadership and the team.",
       "I ran a blameless post-mortem, fixed our estimation process with confidence ranges, and reset expectations transparently.",
       "The next two programs landed on time and my forecasting became a team standard.",
       "Own it cleanly, extract the systemic lesson, prove you changed."),
    _q("failure",
       "Describe a project that missed its deadline.",
       "A dependency-heavy program slipped because I under-managed an upstream risk.",
       "I had to recover the timeline and trust.",
       "I re-baselined honestly, added dependency buffers, and escalated the upstream risk to get it prioritized.",
       "We delivered [3] weeks late but with a plan that prevented the next slip.",
       "Don't hide the miss — show the diagnosis and the durable fix."),
    _q("failure",
       "Tell me about a decision you regret.",
       "I once deferred a tech-debt investment to protect a date.",
       "That debt later caused an incident.",
       "I owned the call, led the remediation, and built a policy to budget tech-debt into every plan.",
       "Incident rate dropped and debt stopped being an afterthought.",
       "Regret + learning + a system change is the arc they want."),
    _q("failure",
       "Describe a launch or release that went wrong.",
       "A release caused a partial outage for [some] users.",
       "I was the incident commander.",
       "I coordinated the rollback, ran clear comms, drove the root cause, and shipped preventive actions.",
       "We restored service in [under an hour] and the follow-ups eliminated that failure class.",
       "Show calm command and the preventive follow-through, not blame."),
    _q("failure",
       "Tell me about the biggest mistake you learned from.",
       "Early on I over-communicated detail and under-communicated the 'so what' to execs.",
       "It cost me influence in a key review.",
       "I learned to lead with BLUF, tailor altitude to the audience, and confirm the ask.",
       "My exec updates started driving faster decisions.",
       "A self-awareness answer lands well if the lesson is specific."),
    _q("failure",
       "Describe a time you had to recover a failing program.",
       "I was pulled into a red payments program slipping [2] quarters.",
       "I had to stabilize it and rebuild confidence.",
       "I re-scoped to a winnable milestone, rebuilt the plan and cadence, cleared the top [3] risks, and reset stakeholder expectations.",
       "We shipped the milestone, moved to green, and delivered the full launch the next quarter.",
       "This is a signature senior story — quantify the turnaround."),
    _q("failure",
       "Tell me about a risk that materialized despite your planning.",
       "A vendor missed a delivery I'd flagged as a risk but under-buffered.",
       "It threatened our launch date.",
       "I triggered a contingency, shifted work in-house temporarily, and renegotiated the vendor timeline.",
       "We protected the date and I tightened vendor SLAs afterward.",
       "Show that even a materialized risk had a contingency ready."),

    # ─────────── Stakeholder & Exec Management ───────────
    _q("stakeholders",
       "Tell me about managing senior/executive stakeholders.",
       "My program had [4] VPs with different definitions of success.",
       "I needed one aligned definition to avoid thrash.",
       "I ran 1:1 pre-reads, surfaced the conflicts explicitly, and drove a single success metric everyone signed.",
       "Reviews got faster and the program stopped getting re-litigated.",
       "Show you align execs BEFORE the room, not in it."),
    _q("stakeholders",
       "Describe delivering bad news to leadership.",
       "We were going to miss a committed date.",
       "I had to tell leadership early without losing their confidence.",
       "I led with the headline, the impact, the options, and my recommendation — no burying it.",
       "Leadership picked an option calmly and trusted my reporting more, not less.",
       "Bad news early + options + a recommendation = senior credibility."),
    _q("stakeholders",
       "Tell me about aligning stakeholders with competing goals.",
       "Sales wanted speed, Eng wanted quality, Legal wanted caution.",
       "I had to find a path all three would back.",
       "I made the trade-offs explicit, tied the decision to the shared business outcome, and got each to own a piece of the plan.",
       "We aligned on a phased launch that met the core of all three needs.",
       "Reframe competing goals against a shared higher outcome."),
    _q("stakeholders",
       "Describe influencing an executive decision.",
       "Leadership was leaning toward a big-bang launch I thought was too risky.",
       "I needed to shift them toward a phased approach.",
       "I brought a crisp risk-vs-reward analysis, a customer-impact scenario, and a concrete phased alternative.",
       "They chose the phased plan, which avoided a likely major incident.",
       "Influence with analysis + a ready alternative, not just concern."),
    _q("stakeholders",
       "Tell me about a difficult status update you had to give.",
       "My program went amber right before a board update.",
       "I had to represent it honestly without triggering panic.",
       "I gave a clear R/A/G with the specific risk, the mitigation, and the date confidence.",
       "The update built confidence and we got the support we asked for.",
       "Precision and a mitigation plan turn a scary update into a confident one."),
    _q("stakeholders",
       "Describe a time you managed up effectively.",
       "My director was going into a review missing context on a key risk.",
       "I needed them to look prepared and make a good call.",
       "I gave them a tight pre-read with the decision, the options, and my recommendation.",
       "They ran the review smoothly and made the right call fast.",
       "Managing up = making your leader effective, not just informed."),
    _q("stakeholders",
       "Tell me about building trust with a skeptical stakeholder.",
       "A skeptical eng director doubted TPM added value to his team.",
       "I needed his partnership to land the program.",
       "I focused on removing his team's blockers, kept commitments precisely, and let results speak before asking for anything.",
       "He became a strong advocate and requested TPM support for his next program.",
       "Trust is earned with delivered small commitments, fast."),

    # ─────────── Prioritization & Trade-offs ───────────
    _q("prioritization",
       "Tell me about handling competing priorities.",
       "I owned [3] programs all demanding the same scarce platform team.",
       "I couldn't fully staff them all.",
       "I ranked by business impact and risk, made the trade-offs transparent to sponsors, and sequenced rather than split thin.",
       "The top program shipped early; the others landed with clear expectations.",
       "Show a crisp framework (impact x effort x risk) and transparent trade-offs."),
    _q("prioritization",
       "Describe a hard trade-off you made.",
       "I had to choose between hitting a date and shipping a nice-to-have feature.",
       "Both mattered to different stakeholders.",
       "I chose the date, backed by customer and revenue data, and moved the feature to a committed fast-follow.",
       "We protected the revenue moment and shipped the feature [3] weeks later.",
       "Name the criteria that made the trade-off objective."),
    _q("prioritization",
       "Tell me about deprioritizing something important.",
       "A well-loved internal tool had to be paused to fund a strategic bet.",
       "The owning team was upset.",
       "I explained the strategic rationale, gave a revisit date, and preserved a minimal maintenance mode.",
       "The strategic bet paid off and the tool resumed the next half.",
       "Show empathy for what you cut and a path back."),
    _q("prioritization",
       "Describe allocating limited resources across demands.",
       "Headcount froze mid-year with [5] programs in flight.",
       "I had to keep the most valuable ones moving.",
       "I zero-based the portfolio, paused two low-ROI efforts, and concentrated people on the highest-leverage work.",
       "Throughput on the top programs actually rose despite the freeze.",
       "Concentration beats spreading thin — show the courage to pause things."),
    _q("prioritization",
       "Tell me about balancing speed versus quality.",
       "Leadership wanted a fast launch; the team feared quality risk.",
       "I had to find the right bar for this launch.",
       "I defined a quality gate that was non-negotiable and let everything above it flex for speed.",
       "We launched fast and clean, with no quality regressions past the gate.",
       "Make 'quality' concrete via a gate rather than a vibe."),
    _q("prioritization",
       "Describe saying no to a feature or request.",
       "A big customer requested a bespoke feature that would fragment the roadmap.",
       "I had to decline without damaging the relationship.",
       "I explained the platform cost, offered a configurable alternative, and escalated the revenue trade-off to the sponsor.",
       "We shipped the configurable path, serving that customer and [others].",
       "A principled no protects the many; show the alternative you offered."),
    _q("prioritization",
       "Tell me about reprioritizing a roadmap mid-flight.",
       "New data showed our top feature wouldn't move the metric.",
       "I had to redirect the team quickly.",
       "I brought the data, re-ranked the backlog with Product, and re-committed dates transparently.",
       "We pivoted to the higher-impact work and hit the metric that quarter.",
       "Show you follow the data even when it means reversing course."),

    # ─────────── Cross-functional Collaboration ───────────
    _q("collaboration",
       "Tell me about a strong cross-functional collaboration.",
       "A launch needed Eng, Design, Legal, Marketing, and Support in lockstep.",
       "I owned making the whole thing move as one.",
       "I built a shared plan with a single timeline, one status source, and a weekly cross-functional sync.",
       "Every function hit its gate and the launch went off without a hitch.",
       "Show the connective tissue you created across functions."),
    _q("collaboration",
       "Describe partnering with a team that was hard to work with.",
       "A partner team was overloaded and unresponsive to our dependency.",
       "I needed their deliverable without more escalation friction.",
       "I met their lead, reshaped the ask to fit their constraints, and traded help on something they needed.",
       "They delivered on a workable date and the relationship reset.",
       "Reciprocity and empathy for their load unlock stuck partnerships."),
    _q("collaboration",
       "Tell me about breaking down a silo.",
       "Two orgs were solving the same problem separately and duplicating work.",
       "I had to get them to collaborate.",
       "I convened a shared forum, surfaced the overlap with data, and proposed a joint roadmap.",
       "They merged efforts and cut duplicated work [~30%].",
       "Data on duplication plus a shared forum is a repeatable silo-buster."),
    _q("collaboration",
       "Describe building a coalition to get something done.",
       "A platform change needed buy-in from [6] team leads with no mandate.",
       "I had to build momentum voluntarily.",
       "I recruited an early champion, showed a quick win, then used that proof to bring the rest aboard.",
       "All [6] adopted within [a quarter] and the platform standardized.",
       "Champion → quick win → snowball is a strong influence pattern."),
    _q("collaboration",
       "Tell me about working with remote or distributed partners.",
       "Key partners were in another region with limited overlap hours.",
       "Collaboration was slow and easy to misread.",
       "I set async-first norms, crisp written decisions, and a small anchored overlap for the hard calls.",
       "Decision latency dropped and trust improved across the timezone gap.",
       "Async operating discipline is the differentiator for distributed work."),
    _q("collaboration",
       "Describe partnering with a vendor or external partner.",
       "A launch depended on a third-party integration with a shaky track record.",
       "I had to de-risk their delivery.",
       "I set clear SLAs, joint milestones, weekly syncs, and an in-house contingency for the riskiest piece.",
       "They delivered on the revised plan and my contingency was never needed but ready.",
       "Show you manage external partners like any critical dependency."),

    # ─────────── Decision-making & Judgment ───────────
    _q("decision",
       "Tell me about a data-driven decision you made.",
       "We debated whether to invest another quarter in a feature.",
       "Opinions were split and expensive.",
       "I pulled usage and funnel data, ran a small experiment, and let the results decide against pre-set criteria.",
       "The data said stop; we redirected the quarter to higher-impact work.",
       "Show the criteria set BEFORE the data, so it's judgment not cherry-picking."),
    _q("decision",
       "Describe a decision you made with imperfect data.",
       "We had to pick an architecture before load patterns were known.",
       "Waiting for perfect data would have blown the timeline.",
       "I made the reversible parts fast, protected the irreversible ones with more analysis, and set a re-evaluation trigger.",
       "The choice held up and the trigger let us adjust cheaply later.",
       "Distinguish one-way vs two-way doors — a classic senior judgment tell."),
    _q("decision",
       "Tell me about a quick decision under pressure.",
       "During a launch, a metric spiked wrong and we had minutes to decide.",
       "I had to call roll-forward vs rollback fast.",
       "I checked the blast radius, weighed the reversible option, and called an immediate rollback.",
       "We avoided customer impact and root-caused calmly after.",
       "Bias to the reversible option under time pressure reads as sound judgment."),
    _q("decision",
       "Describe a time you changed your mind.",
       "I initially pushed build over buy for a component.",
       "New cost and timeline data challenged my stance.",
       "I re-ran the analysis, admitted the new data changed the answer, and switched to buy.",
       "We saved [a quarter] and I modeled that being right matters more than being consistent.",
       "Changing your mind on evidence is strength, not weakness — say so."),
    _q("decision",
       "Tell me about weighing risk versus reward.",
       "A fast-launch option promised upside but carried real incident risk.",
       "I had to size both honestly.",
       "I quantified downside scenarios, added guardrails that capped the risk, and took the upside within those limits.",
       "We captured the upside with zero major incidents thanks to the guardrails.",
       "Show you took smart risk with guardrails, not reckless or timid."),
    _q("decision",
       "Describe a decision with significant consequences.",
       "I recommended sunsetting a revenue-generating legacy system.",
       "Getting it wrong would hit revenue.",
       "I modeled migration paths, de-risked with a pilot, and staged the cutover with rollback at each step.",
       "We retired it cleanly, cut cost [X], and kept revenue flat through the transition.",
       "Match the rigor of the process to the size of the stakes."),

    # ─────────── People & Team Development ───────────
    _q("people",
       "Tell me about developing a team member.",
       "A high-potential PM wanted to grow into program leadership.",
       "I needed to stretch them safely.",
       "I gave them a real workstream, coached weekly, and gradually widened their scope with air cover.",
       "They grew into leading it independently and were promoted.",
       "Concrete stretch + coaching + visible outcome is the arc."),
    _q("people",
       "Describe handling an underperformer.",
       "A team member's delivery was consistently slipping and affecting the program.",
       "I had to address it fairly and fast.",
       "I gave direct, specific feedback, co-created a clear plan with milestones, and supported them closely.",
       "They either turned it around to meet the bar or we managed a respectful transition.",
       "Show candor + support + a clear bar, not avoidance."),
    _q("people",
       "Tell me about building or scaling a team.",
       "A growing program needed a TPM function that didn't exist yet.",
       "I had to build it from scratch.",
       "I defined the roles, hired for complementary strengths, set operating norms, and onboarded deliberately.",
       "The team scaled to [N] and became the delivery backbone for the org.",
       "Talk about the bar you set and the culture you seeded."),
    _q("people",
       "Describe giving someone difficult feedback.",
       "A strong engineer's communication style was alienating partners.",
       "It was limiting their impact and the team's.",
       "I gave specific, kind, timely feedback with examples and a concrete alternative.",
       "Their partner relationships improved and it unblocked a stalled collaboration.",
       "Specific + timely + kind + actionable is the feedback formula."),
    _q("people",
       "Tell me about resolving a team morale problem.",
       "Morale dropped after a reorg left people unsure of their roles.",
       "I had to rebuild engagement while delivering.",
       "I listened in 1:1s, clarified ownership, restored a shared goal, and celebrated early wins.",
       "Engagement recovered and we retained the whole team.",
       "Listen first, then give clarity and a win."),
    _q("people",
       "Describe delegating an important task.",
       "I was overloaded across programs and holding too much myself.",
       "I needed to delegate a critical workstream.",
       "I picked the right owner, set the outcome and guardrails, and resisted micromanaging while staying available.",
       "They delivered it well and I freed capacity for higher-leverage work.",
       "Delegate the outcome, not the steps — and show you let go."),
    _q("people",
       "Tell me about losing a key team member.",
       "A lead engineer left mid-program with critical context.",
       "I had to protect delivery and morale.",
       "I captured their knowledge fast, redistributed ownership, and back-filled while keeping the team steady.",
       "We delivered on time and used the moment to reduce single-points-of-failure.",
       "Show resilience and turning a loss into a systemic improvement."),

    # ─────────── Strategy & Vision ───────────
    _q("strategy",
       "Tell me about setting a vision or strategy for your area.",
       "TPM in my org was seen as project bookkeeping, not strategic.",
       "I wanted to reposition it as a delivery advantage.",
       "I articulated a vision, tied it to business outcomes, and proved it with a flagship turnaround.",
       "TPM became a sought-after partner and the model expanded org-wide.",
       "Vision + a proof point is far stronger than vision alone."),
    _q("strategy",
       "Describe aligning a team to a long-term goal.",
       "A multi-year platform strategy felt abstract to engineers focused on sprints.",
       "I had to make the long game motivating day to day.",
       "I broke the vision into quarterly outcomes, connected each sprint to it, and showed progress on a visible roadmap.",
       "The team stayed motivated and we hit the multi-year milestones on track.",
       "Bridge the long-term to the daily with a milestone ladder."),
    _q("strategy",
       "Tell me about a strategic bet you made or drove.",
       "I pushed to invest early in a platform capability before demand was proven.",
       "It was a risk on limited signal.",
       "I framed it as a reversible pilot with clear success metrics and a kill criterion.",
       "The bet paid off and became a core capability [several] teams now depend on.",
       "Frame bets as measurable, reversible experiments."),
    _q("strategy",
       "Describe influencing the strategy of your org.",
       "Leadership's roadmap under-invested in reliability I saw as a growing risk.",
       "I had to shift investment upstream.",
       "I quantified the incident cost trend, tied it to revenue risk, and proposed a concrete reliability program.",
       "Leadership funded it and incident rate dropped [X%] the next year.",
       "Influence strategy with quantified risk tied to business impact."),
    _q("strategy",
       "Tell me about killing a project for strategic reasons.",
       "A project was progressing but no longer fit the company's direction.",
       "Sunk cost made stopping unpopular.",
       "I made the strategic misfit explicit, proposed redeploying the team to a priority, and owned the decision.",
       "We redeployed to higher-value work and the team ramped fast.",
       "Killing the wrong-but-progressing thing is a senior strength."),
    _q("strategy",
       "Describe connecting your work to business outcomes.",
       "My program was measured on delivery dates, not business impact.",
       "I wanted leadership to see the value, not just the schedule.",
       "I reframed reporting around the revenue and cost outcomes the program drove.",
       "The program's perceived value rose and it secured continued funding.",
       "Always ladder execution up to the business metric it serves."),

    # ─────────── Influence Without Authority ───────────
    _q("influence",
       "Tell me about influencing people you had no authority over.",
       "I needed [5] teams to adopt a shared release process, none reporting to me.",
       "I had to drive adoption voluntarily.",
       "I co-designed it with them, piloted with a willing team, and used the results to pull the rest in.",
       "All [5] adopted and release incidents fell.",
       "Co-creation beats mandates for lasting adoption."),
    _q("influence",
       "Describe persuading someone to your point of view.",
       "An eng lead resisted adding observability I believed was essential.",
       "I needed his team's effort without a mandate.",
       "I connected it to a pain he already felt, showed a low-cost start, and let a quick win prove it.",
       "He adopted it and later expanded it across his services.",
       "Anchor your ask to the other person's existing pain."),
    _q("influence",
       "Tell me about driving adoption of a new process or tool.",
       "A new planning process was met with 'not another process' fatigue.",
       "I had to get real usage, not compliance theater.",
       "I made it lightweight, removed an old step for every new one, and showed the time it saved.",
       "Adoption stuck because it net-reduced overhead.",
       "Adoption sticks when the new thing removes more pain than it adds."),
    _q("influence",
       "Describe getting buy-in across multiple orgs.",
       "A cross-org initiative needed sign-off from [3] VPs with different agendas.",
       "Any one could stall it.",
       "I pre-aligned each 1:1, addressed their specific concern, and brought a unified proposal to the group.",
       "All three signed and the initiative launched on schedule.",
       "Win the room before the room — align individually first."),
    _q("influence",
       "Tell me about championing an unpopular idea.",
       "I pushed to pause features for a tech-debt sprint everyone dreaded.",
       "The short-term optics were bad.",
       "I quantified the velocity drag, showed the payback, and secured a bounded, time-boxed investment.",
       "Post-sprint velocity rose [X%] and the skeptics became advocates.",
       "Make the invisible cost visible and bound the ask."),
    _q("influence",
       "Describe negotiating for resources or headcount.",
       "My program was under-staffed for its committed scope.",
       "I needed more people in a tight budget cycle.",
       "I tied the ask directly to at-risk revenue, offered scope options at each staffing level, and let leadership choose.",
       "I got the headcount for the revenue-critical scope.",
       "Frame resource asks as business trade-offs, not pleas."),

    # ─────────── Risk & Crisis Management ───────────
    _q("risk",
       "Tell me about identifying and mitigating a major risk.",
       "Early in a program I spotted a single-vendor dependency as a critical risk.",
       "A vendor slip would sink the launch.",
       "I logged it, built a contingency, negotiated a buffer, and tracked it weekly as a top risk.",
       "When the vendor slipped, the contingency kept us on date.",
       "Proactive risk logging + a ready contingency is the whole story."),
    _q("risk",
       "Describe managing a crisis or major incident.",
       "A Sev1 took down a core service during peak hours.",
       "I was incident commander.",
       "I established clear roles, ran tight comms, focused on restore-first, then drove root cause and prevention.",
       "We restored in [under an hour] and shipped fixes that closed the failure class.",
       "Calm command, restore-first, then prevention — in that order."),
    _q("risk",
       "Tell me about a security or compliance issue you handled.",
       "An audit flagged a data-handling gap before a regulated launch.",
       "We couldn't ship until it closed.",
       "I mobilized Eng and Legal, prioritized the fix on the critical path, and verified with the auditor.",
       "We closed the gap, passed the audit, and launched on time.",
       "Show you treat compliance as a hard gate, managed like any risk."),
    _q("risk",
       "Describe handling an outage or reliability problem.",
       "Recurring outages were eroding customer trust in a product.",
       "I had to break the pattern.",
       "I stood up an incident-review ritual, tracked action items to closure, and drove targeted reliability work.",
       "Outage frequency dropped [X%] and MTTR halved.",
       "Turn firefighting into a systemic reliability program."),
    _q("risk",
       "Tell me about a contingency plan that saved you.",
       "I'd pre-built a fallback for a risky third-party integration.",
       "The integration failed [days] before launch.",
       "I activated the in-house fallback I'd prepared and re-planned the final stretch.",
       "We launched on date; the fallback bridged the gap seamlessly.",
       "Pre-mortems and contingencies are cheap insurance — show you buy it."),
    _q("risk",
       "Describe escalating a risk at the right time.",
       "An upstream team's slip threatened my launch but they'd deprioritized it.",
       "I couldn't fix it at my level.",
       "I escalated early with the impact and a specific ask, not a complaint.",
       "Leadership reprioritized the upstream work and we held our date.",
       "Escalate early, with impact and a clear ask — that's a skill, not a failure."),

    # ─────────── Communication ───────────
    _q("communication",
       "Tell me about explaining something technical to a non-technical audience.",
       "I had to brief execs on a complex migration's risk.",
       "They needed to decide without the technical depth.",
       "I used a simple analogy, led with the business impact, and offered depth only on request.",
       "They made a fast, informed go decision.",
       "Lead with 'so what', keep depth on tap — don't drown them."),
    _q("communication",
       "Describe a time strong communication changed an outcome.",
       "A program was about to be cut on a misread status.",
       "I had one shot to reset the narrative.",
       "I reframed with a clear BLUF, the real progress, and a credible plan to green.",
       "Leadership kept funding it and it shipped successfully.",
       "A crisp reframing can save a program — practice your BLUF."),
    _q("communication",
       "Tell me about presenting to executives.",
       "I presented a portfolio review to the leadership team.",
       "I had [10] minutes for [5] programs.",
       "I opened with the headline, flagged only the decisions I needed, and kept detail in an appendix.",
       "We closed all decisions in the meeting with time to spare.",
       "Exec time is scarce — decisions first, detail on demand."),
    _q("communication",
       "Describe handling a serious miscommunication.",
       "Two teams built to different assumptions from a vague spec.",
       "The mismatch surfaced late and threatened rework.",
       "I owned the ambiguity, aligned both on a written source of truth, and salvaged the overlap.",
       "We minimized rework and I made written decisions the norm.",
       "Own the miscommunication and fix the system that allowed it."),
    _q("communication",
       "Tell me about tailoring a message to different audiences.",
       "The same launch needed framing for execs, engineers, and support.",
       "One message wouldn't land for all three.",
       "I tailored altitude and emphasis per audience while keeping the core facts consistent.",
       "Each group got what they needed and executed without confusion.",
       "Same truth, different altitude — show you flex the framing."),
    _q("communication",
       "Describe communicating through a period of uncertainty.",
       "During a reorg, my team was anxious and rumor-driven.",
       "I had to keep them steady and focused.",
       "I communicated frequently, was honest about what I did and didn't know, and set a clear near-term focus.",
       "The team stayed productive and trust in me grew.",
       "Frequent, honest 'here's what I know' beats waiting for certainty."),

    # ─────────── Customer & Business Orientation ───────────
    _q("customer",
       "Tell me about a time you championed the customer.",
       "A cost-cutting proposal would have degraded a key customer experience.",
       "I had to defend the customer without ignoring the business.",
       "I brought customer-impact data, proposed a cheaper option that preserved the experience, and won the trade-off.",
       "We cut cost [X] without hurting the experience or churn.",
       "Champion the customer WITH data and a business-viable alternative."),
    _q("customer",
       "Describe balancing customer needs with business constraints.",
       "Customers wanted a feature that was expensive to build broadly.",
       "I had to serve them within budget.",
       "I found a configurable path that met the core need at a fraction of the cost.",
       "We satisfied the customers and stayed within budget.",
       "Reframe 'either/or' into a cheaper 'both' where you can."),
    _q("customer",
       "Tell me about using customer feedback to change direction.",
       "Early feedback showed our planned flow confused users.",
       "I had to act before we over-invested.",
       "I brought the feedback to Product, ran a quick test of an alternative, and pivoted the design.",
       "The revised flow lifted completion [X%] at launch.",
       "Show you let real user signal override internal assumptions."),
    _q("customer",
       "Describe improving a customer experience measurably.",
       "A slow support-resolution path was hurting satisfaction.",
       "I owned a cross-team fix.",
       "I mapped the journey, cut the worst bottlenecks, and instrumented the outcome.",
       "Resolution time dropped [X%] and CSAT rose.",
       "Tie the CX improvement to a hard before/after metric."),
    _q("customer",
       "Tell me about handling a major customer escalation.",
       "A top customer escalated a recurring issue to executives.",
       "I had to resolve it and rebuild confidence.",
       "I owned the comms, drove a fast root-cause fix, and set up prevention plus a follow-up cadence.",
       "The issue was resolved, the account was retained, and trust recovered.",
       "Ownership + fix + prevention + follow-through saves the relationship."),

    # ─────────── Growth, Feedback & Positioning ───────────
    _q("growth",
       "Tell me about a time you received feedback and acted on it.",
       "A mentor told me my updates buried the key decision.",
       "It was limiting my influence in reviews.",
       "I adopted a BLUF-first structure and confirmed the ask every time.",
       "My reviews started driving faster decisions and the feedback stuck.",
       "Show a specific behavior change and its result."),
    _q("growth",
       "Describe learning a new skill or domain quickly.",
       "I had to lead a payments program without payments depth.",
       "I needed to be credible fast.",
       "I built a focused learning plan, paired with SMEs, and applied it immediately on the job.",
       "I was leading confidently within [weeks] and caught risks the team missed.",
       "Show a deliberate, fast learning method — not just 'I figured it out'."),
    _q("growth",
       "Tell me about stepping outside your comfort zone.",
       "I took on an org-wide operating-model change well beyond my prior scope.",
       "It was bigger and more political than anything I'd led.",
       "I leaned on structure, sought coaching, and built coalitions deliberately.",
       "The new model rolled out successfully and expanded my scope permanently.",
       "Stretch + how you de-risked it = growth mindset with judgment."),
    _q("growth",
       "Describe how you improved a process or yourself over time.",
       "Our launch process kept producing avoidable surprises.",
       "I wanted repeatable, boring launches.",
       "I built a launch checklist, go/no-go gates, and a post-launch review loop.",
       "Launch incidents dropped and the playbook became the team standard.",
       "Show continuous improvement as a system, not a one-off."),
    _q("growth",
       "Why this role, and why you? (positioning)",
       "This role sits exactly at the intersection of scale, ambiguity, and cross-org leadership.",
       "I want to drive company-level outcomes, not just program delivery.",
       "My track record is turning around red programs, building TPM functions, and influencing strategy without authority.",
       "That's precisely what a Head-of-TPM mandate needs, and where I do my best work.",
       "Tie your signature strengths directly to THIS role's mandate and scale."),
]
