-- ============================================================
--  DailyPlanner — BEDTIME STORIES (seed extension #2)
--
--  Adds 100 more stories on top of the original migration.
--  Uses ON CONFLICT (slug) DO NOTHING so this is safe to run on a
--  table that has already been seeded — only new slugs are added.
--  Sort_order continues from 201.
-- ============================================================

insert into bedtime_stories (slug, source, title, body, moral, sort_order) values

    ('snow-white',
     'Grimm',
     'Snow White',
     E'A queen wished for a daughter with skin white as snow, hair black as ebony, lips red as blood. She had her — and died at the birth. The king remarried. The new queen was beautiful but vain, and owned a magic mirror.\n\nEach morning she asked, ‘Mirror, mirror — who is fairest?’ For years the mirror said: ‘You.’ One morning it said: ‘Snow White.’ The queen sent a huntsman to take the girl into the forest and kill her. He could not. He let her go.\n\nSnow White wandered until she found a cottage of seven small beds, seven small chairs, seven small plates. The seven dwarfs who lived there took her in.\n\nThe queen, furious, came in disguise three times — first with a lace, then a comb, then a poisoned apple. The third time the dwarfs were too late. They laid Snow White in a glass coffin. A travelling prince saw her, asked to take the coffin away, and on the jolt the apple fell from her throat. She woke.',
     'Vanity that cannot bear another’s beauty turns at last on itself. Goodness, asleep, can still be woken.',
     201),

    ('the-brave-little-tailor',
     'Grimm',
     'The Brave Little Tailor',
     E'A small tailor killed seven flies at once with a swat, and was so pleased he embroidered ‘Seven at One Blow’ on his belt and set out into the world.\n\nA giant met him and read the belt. Thinking it meant seven men, he challenged the tailor to feats of strength. The tailor outsmarted him each time — squeezing water from a stone (it was cheese), throwing a stone that flew far (it was a bird).\n\nThe king heard of the man who killed seven at one blow and asked his help against giants and a unicorn. The tailor caught the giants by tricking them into killing each other, and the unicorn by making it ram its horn deep into a tree.\n\nHe became prince. The court grumbled, but his belt sat above the throne, embroidered as plainly as ever.',
     'Confidence and quick thinking can pass for any strength the world needs. The belt only said what the deeds went on to make true.',
     202),

    ('the-goose-girl',
     'Grimm',
     'The Goose Girl',
     E'A princess was sent to marry a prince in a far country. Her wicked maid forced her on the road to swap clothes and roles, and to swear by heaven never to tell.\n\nThe true princess arrived at the prince’s court as a goose-girl, set to mind the geese with a boy named Conrad. Each morning her hair, when she undid it, shone gold. Conrad tried to grab a strand; she would whisper to the wind, and the wind blew his hat away until she was finished combing.\n\nThe old king grew curious. The princess could not tell — but he urged her to speak her grief into a stove. She did. He listened from outside. The truth came out. The maid was sent away; the true bride was honoured.',
     'A vow taken under threat finds its way out through cracks in the stove. Truth is patient.',
     203),

    ('the-three-spinners',
     'Grimm',
     'The Three Spinners',
     E'A lazy girl could not spin, though her mother boasted she could. The queen, hearing the boast, took her to the palace and locked her in a room full of flax. ‘Spin it all by Saturday and you shall marry the prince.’\n\nThe girl wept. Three strange women appeared at the window. One had a wide, swollen lip; one a great flat thumb; one a huge wide foot. ‘We will spin for you, if at the wedding you call us aunts and seat us at your table.’\n\nThe flax was spun. The wedding came. The three women arrived. The prince, astonished, asked: ‘How came you by such lips, thumbs, and feet?’ ‘From spinning, Your Majesty. Lifelong spinning makes us so.’\n\nThe prince turned to his bride: ‘Then you, my dearest, shall never spin again.’',
     'A debt repaid as agreed lifts the burden you were never meant to carry. Honour those who helped you when no one watched.',
     204),

    ('the-star-money',
     'Grimm',
     'The Star Money',
     E'A poor orphan girl had nothing in the world but her clothes and a small loaf of bread someone had given her. As she walked through the woods, she met a hungry man. She gave him the bread.\n\nA child cried with cold; she gave her cap. Another, her jacket. Another, her dress. Another, her shift. At last she stood barefoot in the forest in her thin chemise, and even that she gave to a child whose only covering had blown away.\n\nIt grew dark. The stars began to fall. They turned to silver coins as they touched the ground. She found, draped over her, a fresh shift of finest linen. She gathered the silver and was rich for the rest of her life.',
     'What is given freely returns in unexpected coin. The empty hands are sometimes the ones the sky fills.',
     205),

    ('the-snow-queen-gerda',
     'Andersen',
     'The Snow Queen',
     E'Two children, Kai and Gerda, played together. A splinter of an evil mirror lodged in Kai’s eye, and a piece in his heart, and he became cold and cruel. The Snow Queen carried him off to her palace far north. He sat playing with shards of ice, trying to spell the word ‘eternity.’\n\nGerda set out alone. She crossed forests, met robber-girls, was carried by a reindeer, and at last found him in the cold hall, blue-lipped, frozen. She wept on his chest.\n\nHer warm tears melted the splinter from his heart. He wept too — and the splinter washed out of his eye. The shards of ice on the floor, of their own accord, fell into the word ‘eternity.’\n\nThey walked home together, and it was summer.',
     'Love that does not give up can melt what cleverness only freezes harder. Stay until the heart thaws.',
     206),

    ('the-wild-swans',
     'Andersen',
     'The Wild Swans',
     E'A wicked stepmother turned eleven young princes into swans. Their sister Eliza was sent away. She found them by a wild lake; by day they were swans, by night men.\n\nA fairy told her how to break the curse: she must weave eleven shirts of stinging-nettle, in silence — speaking one word would kill her brothers. She gathered nettles in a graveyard. Her hands burned. The villagers, suspicious, accused her of witchcraft.\n\nOn the morning of her execution, she had ten shirts done and the sleeve of the eleventh. The eleven swans flew over the city. She threw the shirts. They struck — eleven men stood there, only the youngest with a swan’s wing where his sleeve was unfinished.\n\nShe could speak again. The truth was told. The fire was put out.',
     'Some saving cannot be hurried, and cannot be explained while it is being done. Hold the silence and finish the work.',
     207),

    ('the-tinder-box',
     'Andersen',
     'The Tinder Box',
     E'A discharged soldier met an old witch on the road. ‘Climb into the hollow tree,’ she said. ‘At the bottom are three rooms — three dogs guard three chests of copper, silver, and gold. Set them on my apron and they will not bite. Take all you want. Bring me the old tinder-box at the bottom.’\n\nHe did. He took the gold. He kept the tinder-box, refused to give it to her, and (in haste, regretting) struck her dead.\n\nLater, in his city lodgings, he struck the tinder-box once — the small dog appeared. Twice — the middle dog. Three times — the great dog. They could fetch him anything he wished.\n\nHe used them well, but also wickedly. In the end, after a near-execution, the dogs saved him and made him king. He learned, slowly, to use the magic with care.',
     'Power found in a tinder-box can buy what gold cannot — and can also undo a man if he uses it without thought.',
     208),

    ('aladdin-and-the-lamp',
     'Arabian Nights',
     'Aladdin and the Lamp',
     E'A lazy boy named Aladdin was lured by a wicked sorcerer (calling himself ‘uncle’) into an underground chamber to fetch a tarnished old lamp. When Aladdin would not hand it up before climbing out, the sorcerer sealed him in.\n\nAladdin, by chance, rubbed the lamp. A jinni appeared. ‘What is your wish, master?’ He asked first only to be brought home. Then for food. Then for help to win the princess Badroulbadour. He used the jinni well — built a palace, was generous to the poor, treated his mother with respect.\n\nThe sorcerer returned in disguise — ‘New lamps for old!’ The princess, not knowing, traded the lamp away. The whole palace, the princess and all, was carried off to Africa.\n\nAladdin followed without the jinni’s help, by his wits and patience. He recovered the lamp, recovered the princess, brought the palace back, and dealt with the sorcerer for good.',
     'Magic given is never the whole answer. Wisdom and courage must be there to use it well, especially after it is taken away.',
     209),

    ('king-midas-donkey-ears',
     'Greek myth',
     'King Midas and the Donkey Ears',
     E'King Midas, foolish in many things, was asked to judge a music contest between Apollo (the lyre) and Pan (the pipes). Everyone else chose Apollo. Midas chose Pan.\n\nApollo, offended, gave the king the ears of a donkey. Midas hid them under a great turban. Only his barber knew. Sworn to silence, the barber could not bear it; he dug a hole in a meadow and whispered into the earth: ‘King Midas has the ears of a donkey.’\n\nReeds grew from the hole. When the wind blew through them, the reeds whispered the secret to everyone who walked by.',
     'A secret pressed down comes up through the reeds. Choose your judgements with care; the world will hear.',
     210),

    ('daedalus-and-icarus',
     'Greek myth',
     'Daedalus and Icarus',
     E'Daedalus, the great craftsman, was imprisoned with his son Icarus on the island of Crete. He gathered feathers, melted wax, and built two pairs of wings. ‘Fly with me,’ he told Icarus. ‘But not too low — the sea will soak the feathers. Not too high — the sun will melt the wax. Keep the middle way.’\n\nThey flew. Icarus, drunk with the joy of flight, climbed higher and higher. The sun softened the wax. The feathers came loose. He fell into the sea and drowned.\n\nDaedalus flew on alone, weeping.',
     'The middle way saves what the high way loses. Do not despise prudence; it is the path that brings you home.',
     211),

    ('pandoras-box',
     'Greek myth',
     'Pandora''s Box',
     E'Pandora, the first woman, was given a sealed jar by the gods and told never to open it. For a long time she did not. Curiosity grew until it filled her hands.\n\nShe lifted the lid for one quick peep. Out flew sickness, war, hunger, jealousy, sorrow — every trouble that has plagued the world ever since. She slammed the lid in horror.\n\nOne thing remained inside, fluttering at the bottom: hope.',
     'When the troubles come out, what stays inside is hope. Even after the worst is loose in the world, that small thing is enough to live on.',
     212),

    ('arachne-the-spinner',
     'Greek myth',
     'Arachne the Spinner',
     E'Arachne was the finest weaver in her town. She boasted she was finer than the goddess Athena. The goddess, hearing, came to her in the form of an old woman.\n\n‘Be more humble, child.’ Arachne mocked her. The goddess threw off her disguise. ‘Then weave with me.’\n\nThey wove. Both works were perfect. Arachne’s tapestry, however, mocked the gods. Athena, in fury, struck her loom — and Arachne, ashamed, hanged herself.\n\nAthena pitied her. She loosened the rope and changed her into a spider, doomed and gifted: to weave forever, in every corner of the world, finest threads of all.',
     'Pride in great gifts is the first thread we hang ourselves on. Let the gift speak; do not boast of it.',
     213),

    ('echo-and-narcissus',
     'Greek myth',
     'Echo and Narcissus',
     E'A nymph named Echo could only repeat the last words spoken to her — a punishment for chatter. She loved a beautiful boy named Narcissus, but could only say back what he said.\n\nHe was cold to all who loved him. One day he leaned over a still pool and saw, gazing back, the most beautiful face he had ever seen. He could not look away. Day and night he stayed by the pool, wasted and pining for the reflection that could not love him.\n\nHe died there. A small flower grew in his place — the narcissus. Echo, grieving, faded until only her voice remained, in the rocks of mountains, repeating the cries of others.',
     'Self-love that cannot give back leaves only a voice in the rocks. Love something other than your own face.',
     214),

    ('phaethon-and-the-suns-chariot',
     'Greek myth',
     'Phaethon and the Sun''s Chariot',
     E'Phaethon, son of the sun god Helios, begged his father to let him drive the chariot of the sun for a single day. Helios, who had sworn to grant any wish, warned him: ‘The horses are wild. The road is steep. Even the gods do not drive my chariot.’ Phaethon insisted.\n\nAt dawn the horses bolted from his weak hands. The chariot careened high, where the world froze; then low, where the world burned. Mountains scorched. Rivers boiled. Africa was turned to desert that day.\n\nZeus, to save the world, struck Phaethon down with a thunderbolt. He fell into a river. His sisters wept by the bank until they turned into trees, weeping amber.',
     'Some reins should not be taken by hands that have not earned them. Asking is not the same as being able.',
     215),

    ('procrustes-bed',
     'Greek myth',
     'Procrustes'' Bed',
     E'On the road to Athens lived a robber named Procrustes who offered every traveller a bed for the night. Those who were too short for the bed, he stretched. Those who were too tall, he cut to size. None went on alive.\n\nTheseus, on his way to Athens, accepted the offer — then forced Procrustes to lie on his own bed. He fitted him to it.',
     'Beware the man who fits the world to his frame instead of his frame to the world. The bed will one day be his own.',
     216),

    ('damocles-sword',
     'Greek myth',
     'The Sword of Damocles',
     E'Damocles, a courtier, told King Dionysius: ‘What a happy life you must lead, surrounded by all this gold and silver and pleasure.’ The king said: ‘Try it for a day.’\n\nDamocles was seated at the great table, given the finest food, surrounded by servants. Above his head, the king had hung a sharp sword by a single horsehair. Damocles could not eat. He could not sleep. He begged to be allowed to leave.\n\n‘So you see,’ said the king, ‘what it is to live with absolute power.’',
     'Above every great seat hangs an unseen thread. Envy the rich less when you see what hangs above their heads.',
     217),

    ('sisyphus-and-his-stone',
     'Greek myth',
     'Sisyphus and His Stone',
     E'For deceiving the gods, Sisyphus was condemned to push a great stone up a hill in the underworld. Whenever it neared the top, it rolled back down, and he had to begin again. Forever.\n\nThe gods thought there could be no worse punishment than meaningless labour. But the old stories say that, in time, Sisyphus learned to feel the muscles in his shoulders and the mossy texture of the stone, and to know each step of the slope. He smiled, sometimes, on the way down.',
     'Even at meaningless work, the worker can find his own meaning. The hill is the same; what we bring to it is not.',
     218),

    ('the-lion-and-three-bulls',
     'Aesop',
     'The Lion and the Three Bulls',
     E'Three bulls always stood close together in the meadow, facing outward. A lion who watched them could find no opening. Whenever he tried, three pairs of horns turned to meet him.\n\nSo he began to whisper. To the first bull he said, ‘The other two are mocking you behind your back.’ To the second, ‘The other two have been dividing the best grass without you.’ To the third, ‘The other two plan to leave you alone in the meadow.’\n\nThe bulls began to graze apart. The lion ate them one by one.',
     'Standing together is the strength three weak ones use to bear a strong one. Listen to the whisperer who wants to separate you.',
     219),

    ('the-belly-and-the-members',
     'Aesop',
     'The Belly and the Members',
     E'The hands and feet and mouth grew tired of working only to feed the belly. ‘He sits in the middle and does nothing while we labour all day.’ They went on strike.\n\nThe hands refused to lift food. The mouth refused to chew. The feet refused to walk to the market. The belly received nothing.\n\nWithin a few days, the hands grew weak, the feet trembled, the mouth dried. The body was failing. ‘Ah,’ said the hands. ‘So the belly was working too. Quietly, but for all of us.’',
     'The body’s parts each owe each other. The one who looks idle may be doing the part that lets you walk at all.',
     220),

    ('the-hen-and-the-cat',
     'Aesop',
     'The Hen and the Cat',
     E'A hen lay sick on her perch. The cat came up, all sweet voice and concern. ‘Dear sister hen — how are you? Tell me if you need anything. Whatever you need.’\n\nThe hen looked down. ‘I shall be quite well, dear cat — if you will only go away.’',
     'Beware kindness that has teeth. The cat at the sickbed is not a nurse.',
     221),

    ('the-trees-and-the-axe',
     'Aesop',
     'The Trees and the Axe',
     E'A woodcutter came into the forest with a new axe-head, but no handle. He begged the trees to give him one small piece of wood — ‘any tree, the merest sapling.’ The trees, taking pity, gave him a young ash.\n\nHe fitted the handle, swung the axe, and began to cut down all the great oaks of the forest.\n\n‘Friends,’ said the oaks as they fell, ‘we should never have given him the handle.’',
     'A single concession to your enemy may be the part that lets him cut you down. Refuse the small ask if it gives him the whole tool.',
     222),

    ('the-quack-frog',
     'Aesop',
     'The Quack Frog',
     E'A frog crawled out of the marsh and announced to all the animals: ‘I am a doctor! I have skill in every illness! Come to me with all your ailments.’\n\nThe fox stopped and looked him over carefully. ‘How can you cure others, frog, when you yourself are wrinkled, lame, and damp? First heal yourself.’',
     'Do not buy your remedy from a seller who has not first taken his own.',
     223),

    ('the-dog-and-the-wolf',
     'Aesop',
     'The Dog and the Wolf',
     E'A thin wolf met a fat dog by the road. The wolf admired his sleek coat. ‘How can I become like you?’ ‘Easy. Come and live in my master’s yard. Eat his scraps.’\n\nThey walked together. As they neared the house the wolf noticed a worn ring around the dog’s neck. ‘What is that?’ ‘Oh, only the mark where my collar rubs.’\n\nThe wolf stopped. ‘A collar? Do you not run free?’ ‘Sometimes.’ The wolf turned and walked away. ‘Then keep your scraps. I would rather be thin and free.’',
     'A full belly bought with a chain is no bargain. Choose freedom plainly, even when it is hungry.',
     224),

    ('the-old-woman-and-the-wine-jar',
     'Aesop',
     'The Old Woman and the Wine-jar',
     E'An old woman found an empty wine-jar lying by the road. She lifted it, and even after the wine was long gone, the jar still smelled of fine vintage.\n\nShe sniffed it slowly. ‘Ah,’ she said, smiling. ‘How fine the wine must have been, when even the empty jar is so sweet.’',
     'A great life leaves a fragrance even after the years are spent. Be the kind of jar that perfumes the road.',
     225),

    ('the-fox-and-the-goat-in-the-well',
     'Aesop',
     'The Fox and the Goat in the Well',
     E'A fox fell into a deep well and could not climb out. A passing goat looked down. ‘What are you doing in there?’ ‘Drinking,’ said the fox airily. ‘The water here is the sweetest I have ever tasted. Come and try.’\n\nThe goat jumped in. The fox climbed onto his horns and out, and looked back from the rim. ‘Stay there, friend. Next time, look before you leap — and never trust a fox who is suddenly enjoying his troubles.’',
     'A trapped sufferer who recommends the trap is no recommendation. Look before you leap.',
     226),

    ('the-eagle-and-the-beetle',
     'Aesop',
     'The Eagle and the Beetle',
     E'A hare, hunted by an eagle, begged a beetle nearby for protection. The beetle bravely promised it. The eagle, ignoring the small creature, killed the hare anyway.\n\nThe beetle did not forget. He flew up to the eagle’s nest and rolled the eagle’s eggs out, one by one. The eagle laid more in higher places — the beetle followed, and broke them all. Even at the lap of Zeus the eagle could not save them; the beetle dropped a ball of dung onto Zeus’s robe; Zeus stood up to brush it off, and the eggs rolled out.\n\nAt last Zeus fixed the eagle’s breeding season for a time when no beetles fly.',
     'Despise the small at your peril. The mighty insult is sometimes paid back by an inch-long enemy.',
     227),

    ('the-lion-and-the-wild-ass',
     'Aesop',
     'The Lion and the Wild Ass',
     E'A lion and a wild ass hunted together. The ass’s speed ran down the prey; the lion’s strength brought it down. They sat to divide.\n\nThe lion made three heaps. ‘The first is mine, because I am the king. The second is mine, because I am your partner in equal share. The third — whoever takes it makes me his enemy.’',
     'Equality between unequal partners is whatever the stronger says it is. Choose your partners well.',
     228),

    ('the-fox-and-the-crow-mask',
     'Aesop',
     'The Fox in the Sculptor''s Workshop',
     E'A fox crept into a sculptor’s workshop and began to inspect the heads on the shelves. He came to a particularly handsome one — a fine king’s head. He turned it over. The inside was hollow.\n\n‘How fine,’ said the fox. ‘How completely empty.’',
     'Some heads on the shelf have nothing inside. Do not bow to the head until you have looked at the back of it.',
     229),

    ('the-jackal-and-the-war-drum',
     'Panchatantra',
     'The Jackal and the War Drum',
     E'A hungry jackal wandered into a deserted battlefield where a great war drum had been left tied to a tree. The wind blew, and the drum boomed.\n\nThe jackal trembled. ‘What enormous beast roars so?’ He nearly fled. Then thought: ‘I shall die hungry anyway. Let me see at least what eats me.’\n\nHe crept up. He found a leather hide stretched on wood. Hollow. He pierced it with his teeth and discovered, inside, scraps of food the soldiers had used to keep its skin supple.\n\nHe ate well. ‘Loud noises with empty insides,’ he said, ‘are sometimes a meal for the brave.’',
     'A great noise often hides a hollow drum. Walk close enough to find out.',
     230),

    ('the-lion-cub-among-sheep',
     'Panchatantra',
     'The Lion Cub Among the Sheep',
     E'A lion cub was orphaned and grew up among a flock of sheep. He bleated. He nibbled grass. He ran with them in fear of every shadow.\n\nOne day a great lion came over the hill. The flock fled. The young lion fled too, bleating with the rest.\n\nThe great lion cornered him. ‘Why do you run from me?’ ‘I am a sheep,’ bleated the young lion. The great lion led him to a still pool and made him look down. ‘Look. Now roar.’\n\nThe young lion roared. The whole forest knew it.',
     'Be careful what flock you grew up in. You may have forgotten the voice you were born with.',
     231),

    ('the-three-sons-and-the-lion',
     'Panchatantra',
     'The Three Sons of the Brahmin',
     E'Four young brahmins grew up together as friends. Three were learned in great spells; the fourth was only sensible. Walking through the forest one day, they found the bones of a lion.\n\nThe first cried, ‘I can knit the bones into a skeleton!’ He did. The second, ‘I can clothe it in flesh and skin!’ He did. The third, ‘I can give it the breath of life!’\n\n‘Wait,’ said the fourth. ‘What if it is hungry when it wakes?’ The three laughed at him and proceeded.\n\nThe fourth climbed the nearest tall tree just before the lion took his first breath. From the tree he watched the lion eat all three of his clever friends.',
     'Knowledge without judgement creates beasts that eat their makers. Sense is the spell that should come first.',
     232),

    ('the-greedy-tiger-and-the-bull',
     'Panchatantra',
     'The Greedy Tiger and the Bull',
     E'A great bull broke loose into a forest and lived there for years. A tiger watched him from a distance and dared not attack — the bull had become huge and his horns were long.\n\nA cunning jackal noticed both. ‘I shall earn favour from the tiger,’ he said. He went to the bull and told him the tiger was planning to attack. He went to the tiger and told him the bull was planning to attack. Each grew suspicious of the other.\n\nWhen they met, instead of grazing peacefully on opposite sides of the meadow, they charged. They tore each other almost to death. The jackal, watching from the bushes, ate well from both.',
     'Listen to whisperers and you fight wars that benefit only those who whispered.',
     233),

    ('the-king-and-the-foolish-monkey',
     'Panchatantra',
     'The King and the Foolish Monkey (II)',
     E'A king kept a beloved pet monkey. The monkey was loyal, strong, and devoted — and not very bright.\n\nOne summer afternoon the king napped. A bee landed on his nose. The monkey, eager to defend his master, drew the king’s small dagger and lunged. He missed the bee. He did not miss the king’s nose.\n\nThe wisest counsellor in the room sighed. ‘Sire, when you wake — please remember: it is better to have a clever enemy than a foolish friend.’',
     'Loyalty without judgement is a knife. Choose your defenders for what they think, not for what they feel.',
     234),

    ('the-singing-donkey',
     'Hitopadesha',
     'The Singing Donkey',
     E'A donkey and a jackal were friends. They snuck into a melon-field at night to feast.\n\nWhen the donkey’s belly was full, he turned to his friend. ‘Such fine melons! I shall sing a song of joy!’ ‘Dear friend, please don’t.’ ‘But I must — my heart is bursting.’ ‘Then at least wait till we are out of the field.’\n\nThe donkey began to bray. The farmer came running with a stick.',
     'A full belly should also keep its mouth shut. Joy that puts a stick on your back is best swallowed.',
     235),

    ('the-crow-and-the-pearl-necklace',
     'Hitopadesha',
     'The Crow and the Pearl Necklace',
     E'On a tree by a pond a pair of crows had built their nest. A great cobra lived in the hollow of the same tree, and ate every chick the crows raised.\n\nThe father crow flew to a wise heron. ‘How can we be rid of him?’ The heron said: ‘In the king’s garden the prince’s wife sets her pearl necklace on a stone while she bathes. Wait until she does. Snatch the necklace and fly. Drop it in front of the cobra’s hole. The royal guards will follow you, see the snake, and kill him to recover the pearls.’\n\nThe crow did. The guards came. The snake was killed. The pearls were returned. The crow’s tree at last belonged to the crow.',
     'A small clever bird may use the king’s guards to deal with the snake it cannot fight alone.',
     236),

    ('jataka-prince-five-weapons',
     'Jataka',
     'Prince Five-Weapons',
     E'A prince was trained in archery, swordsmanship, the spear, the dagger, and the staff. On his way home he met a fearful demon called Sticky-Hair, whose body trapped any weapon thrown at it.\n\nThe prince shot his arrows — they stuck. Threw his sword — it stuck. Threw his spear, dagger, staff — all stuck. He punched the demon — his fists stuck. He kicked — his feet stuck. He head-butted — his head stuck.\n\nAnd yet the prince was not afraid. ‘What is left?’ asked the demon. ‘My mind,’ said the prince. ‘My mind is not stuck.’\n\nThe demon was so impressed by the calm of one entirely trapped that he let him go, and was set on the path of dharma.',
     'When every weapon is gone, calm is the last and greatest. Even the demons of the world bow to a mind that is not stuck.',
     237),

    ('jataka-cunning-crab',
     'Jataka',
     'The Cunning Crab',
     E'A crane lived by a pond and grew old, too tired to catch fish. He told the fish that he had heard the pond was to be drained, and offered to fly each one to a deeper lake. Each fish he carried, he ate on a flat rock.\n\nA wise old crab asked to be next. The crane took him in his beak. As they flew, the crab looked down and saw the fish-bones bleached white on the rock.\n\nHe clamped his great pincers around the crane’s long neck. The crane fell. The crab walked back to the pond, alone and proud.',
     'The clever planner sometimes meets a wiser claimant at the end of the line. Do not assume your last victim is a fool.',
     238),

    ('birbal-and-the-honest-beggar',
     'Akbar-Birbal',
     'Birbal and the Honest Beggar',
     E'A beggar had been given alms and dropped one of his coins into a deep crack in the marketplace stones. He could not reach. He sat down weeping.\n\nA rich merchant scoffed. ‘Why so much fuss for one paisa?’ Birbal, passing, took ten gold coins from his purse and dropped them into the same crack. He turned to the merchant. ‘There. Now will you help us pry up the stones? You may keep the gold; let the beggar have his paisa.’\n\nThe merchant lifted with his men. The stones came up. The beggar got his coin. The merchant got the gold.',
     'Sometimes generosity puts more in the crack to draw out what would not have moved for justice alone.',
     239),

    ('birbal-and-three-pundits',
     'Akbar-Birbal',
     'Birbal and the Three Pundits',
     E'Three pundits arrived at Akbar’s court claiming to be the wisest in their respective fields. The first: I know all of grammar. The second: I know all of logic. The third: I know all of religion.\n\nBirbal asked the first: ‘Sir, in this sentence — “Birbal walked to the court” — what is the verb?’ ‘The verb is “walked”.’ ‘Yes. And in the future, you will know my walked when you see it.’\n\nHe asked the second: ‘Is it possible for a man to be both standing and sitting at the same moment?’ ‘No.’ ‘What if he is standing in a boat that is sinking, and sitting in a chair on the deck? Logic does not always know its terms.’\n\nThe third he asked: ‘What is the chief teaching of all religion?’ The pundit listed twelve. Birbal said: ‘Then leave eleven and keep the simplest. Do not boast.’',
     'Knowledge that boasts is not yet wisdom. Each branch has a humility to teach its master.',
     240),

    ('akbar-and-foolish-servant',
     'Akbar-Birbal',
     'Akbar and the Foolish Servant',
     E'A new servant was sent by Akbar to deliver a sealed letter to a distant lord. ‘Tell him only what is in the letter,’ said the emperor. The servant nodded and rode off.\n\nWhen the lord opened the letter, the servant blurted: ‘He has also said you are to give me a tip!’ The lord laughed and gave him a small coin. On returning, the servant boasted of his cleverness.\n\nAkbar listened. ‘Then for your next errand, you shall carry only the letter, and your tongue shall be tied with a silk ribbon. Until you learn that a messenger has only a message.’',
     'A messenger who adds is no longer a messenger. Carry the words; do not embroider them.',
     241),

    ('the-three-lazy-sons',
     'Indian folk',
     'The Three Lazy Sons',
     E'A merchant had three sons, all of them lazy. As he lay dying he called them to his bedside. ‘In the orchard,’ he said, ‘there is a treasure buried. I have not told anyone where. Dig.’\n\nHe died. The three sons dug up the orchard from end to end. They found nothing.\n\nBut the soil was now well-broken. They planted seed, watered, and that year the orchard yielded a harvest worth more than any treasure.\n\nThe sons looked at each other. ‘Father told the truth.’',
     'Some treasures are unearthed only by the digging itself. The work is the gold.',
     242),

    ('birbal-and-the-foolish-brahmin',
     'Akbar-Birbal',
     'Birbal and the Foolish Brahmin',
     E'A brahmin came to Birbal to settle a dispute. He had spent his last money on a goat. On the road home, four wicked young men met him in turn, each saying it was a dog he was carrying. By the fourth, the brahmin had thrown the goat away (just as in the older Panchatantra tale). The young men ate well.\n\nNow the brahmin, recovered, wanted justice. Birbal, smiling, sent for the four. ‘Each of you is to bring me a dog tomorrow. They must be dogs. If any one of you brings me a goat, by mistake, I shall fine you. We shall judge again then.’\n\nThe four brought four dogs, sweating. ‘Curious,’ said Birbal. ‘When dogs are wanted, you bring dogs. When goats are wanted, you bring goats — but only after telling a brahmin they are dogs. Pay the brahmin three times the price of his goat each.’',
     'A clever judge replays the trick on the trickster. Liars pay best when their lies are made into law.',
     243),

    ('nasruddin-soup-of-the-soup',
     'Mulla Nasruddin',
     'The Soup of the Soup of the Soup',
     E'A villager brought Nasruddin a fine duck and was given soup in return. Each week another distant cousin of the villager arrived expecting a meal. Nasruddin served them soup.\n\nBy the fourth week, the soup was very thin. ‘What is this?’ asked the visitor. ‘This,’ said Nasruddin, ‘is the soup of the soup of the soup of the duck.’',
     'Generosity stretched too far becomes water. Honour the gift; do not pretend it is endless.',
     244),

    ('nasruddin-whose-donkey',
     'Mulla Nasruddin',
     'Nasruddin''s Lost Donkey',
     E'Nasruddin lost his donkey and went around the village singing happily. ‘Mulla, why are you singing? Your donkey is lost.’\n\n‘Yes, friend,’ said Nasruddin, ‘but if I had been on it when it ran off, I should be lost too. Be glad with me — I have escaped a worse fate.’',
     'Find the smallest blessing inside the loss. It is sometimes the only thing left to ride.',
     245),

    ('nasruddin-the-lost-ring',
     'Mulla Nasruddin',
     'The Lost Ring (II)',
     E'Once again Nasruddin was searching the street under the lamppost. ‘Mulla — what now?’ ‘My ring.’ ‘Where did you lose it?’ ‘In my house.’ ‘Then why look out here?’\n\nNasruddin sighed. ‘Because in my house there is no light. And I have already turned it inside out twice. Sometimes the second look in the wrong place finds something the first look in the right place did not.’',
     'Sometimes we must give up looking, and the answer comes back when our hands are not so tight on the search.',
     246),

    ('rumi-the-chickpeas',
     'Rumi',
     'The Chickpeas in the Pot',
     E'A chickpea jumped from the pot of boiling water. ‘Why are you doing this to me?’ The cook pushed it back down with the spoon. ‘Hush. You are being cooked. You will become tender. You will become food. You were once a stone in the field; now you become part of a body, part of a soul.’\n\n‘But it hurts.’ ‘Yes. But the hurt is not random. It is the price of becoming.’\n\nThe chickpea sank back into the broth, and grew soft.',
     'The fires we resent are the ones cooking us into something usable. The pain is part of the recipe.',
     247),

    ('rumi-elephant-in-the-dark',
     'Rumi',
     'The Elephant in the Dark Room',
     E'Some men, in a dark room, were each told to feel an elephant. The first touched the trunk. ‘An elephant is like a great snake.’ The second the ear. ‘Like a fan.’ The third the leg. ‘Like a column.’\n\nIf there had been a candle, they would all have agreed at once.',
     'Without a shared light, every truth sounds different. Bring the lamp before the argument.',
     248),

    ('rumi-the-reed-flute',
     'Rumi',
     'The Reed Flute''s Cry',
     E'A reed cut from the reed-bed wept all day in the player’s mouth. ‘I cry,’ it said, ‘because I have been cut from where I belong. Every note I play is a longing.’\n\nThe player closed his eyes and listened. ‘Yes,’ he said. ‘Now you can sing for everyone who has been cut from somewhere.’',
     'The wound that does not stop crying becomes the song that everyone else recognises.',
     249),

    ('the-treasure-under-the-bridge',
     'Hasidic / Jewish',
     'The Treasure Under the Bridge',
     E'A poor man named Isaac dreamed three nights in a row that under the bridge in a far city lay a great treasure. He travelled there, slept under the bridge, was challenged by the guard.\n\n‘Why are you here?’ ‘I had a dream of a treasure under this bridge.’ The guard laughed. ‘Foolish man. I, too, have a dream — three nights in a row — that in a far city, in the cottage of a man named Isaac, beneath his old hearth, is buried a great treasure. Should I, too, travel halfway across the world for a dream?’\n\nIsaac thanked him, walked back home, lifted the hearth-stones in his own kitchen, and found there everything he had ever needed.',
     'The treasure is often at home; the journey is sometimes only to learn to look there.',
     250),

    ('the-two-wolves',
     'Cherokee',
     'The Two Wolves',
     E'A grandfather sat with his grandson by the fire. ‘Inside every one of us,’ he said, ‘there are two wolves. One is fear, anger, jealousy, sorrow, regret, greed, arrogance, self-pity, lies, false pride. The other is joy, peace, love, hope, kindness, humility, truth.’\n\nThe boy thought. ‘Grandfather — which one wins?’\n\n‘The one you feed.’',
     'Two creatures live inside us. The food we give each one decides which becomes strong.',
     251),

    ('how-bear-lost-his-tail',
     'Iroquois',
     'How the Bear Lost His Tail',
     E'Long ago, the bear had a long, beautiful tail he was very proud of. One winter day he met the fox by a frozen lake.\n\nThe fox sat eating fish he claimed to have ‘caught’ through a hole in the ice. ‘How did you do it, friend fox?’ ‘Just stick your tail through the hole. Sit very, very still. The fish will bite.’\n\nThe bear sat for a long, cold time. The lake froze around his tail. When he heard a noise and tried to leap up, his tail snapped clean off.\n\nThat is why bears today have only a small stump.',
     'Vanity and easy advice from a clever stranger leave you a stump where your pride used to be.',
     252),

    ('the-rainbow-crow',
     'Lenape',
     'The Rainbow Crow',
     E'When the world was first cold and frozen, the animals chose the most beautiful bird among them — the rainbow-feathered crow with the most lovely voice — to fly to the Sun and beg for warmth.\n\nThe crow flew up and up. The Sun gave him a stick of fire. He flew back, holding it carefully in his beak. But the long flight scorched his feathers black. The smoke choked his voice into a hoarse caw.\n\nHe brought the fire to the animals. The world warmed. They wept to see what he had become.\n\nThe Great Spirit appeared. ‘You will not be hunted,’ he said. ‘Your meat is not sweet. No one will trap you. The black of your feathers carries every colour underneath, where only the careful can see it.’',
     'A great gift sometimes costs the giver his voice and his colours. Honour him for what cannot be repaid.',
     253),

    ('coyote-steals-fire',
     'Native American',
     'Coyote Steals Fire',
     E'In the long-ago time, the people had no fire and were freezing. Coyote, the trickster, said he would steal fire from the Fire Beings on the mountain.\n\nHe went near their fire and stretched out as if just curious. The Fire Beings watched him. He yawned. They watched. He pretended to sleep. Slowly, slowly, he edged a hot ember onto his tail and bolted.\n\nThey chased him. He passed the ember to Squirrel, whose back curled from the heat. Squirrel passed it to Frog, who jumped and lost his tail. Frog gave it to Wood — and Wood swallowed it. Now wood holds fire inside; you have only to rub it out.',
     'Some gifts arrive only after a chain of small creatures have each given something they cannot get back.',
     254),

    ('the-first-strawberries',
     'Cherokee',
     'The First Strawberries',
     E'The first man and the first woman quarrelled. The woman walked away angrily, eastward. The man, after a long sad sit, set out to find her. He walked and walked.\n\nThe Sun, watching, took pity. He grew, in the path before her, a patch of red wild strawberries. She stopped to taste. They were sweet. She gathered some — and remembered the man, and turned, and walked back.\n\nShe gave him strawberries. They sat together eating.',
     'A small sweetness laid in the path of anger can turn the feet around. Soft answers are sometimes red and grow on the ground.',
     255),

    ('maui-slows-the-sun',
     'Maori',
     'Maui Slows the Sun',
     E'Long ago the sun raced across the sky, and the days were too short for any work to be finished.\n\nMaui made ropes from his sister’s hair (the only ropes the sun could not burn) and went with his brothers to the eastern pit where the sun rises. They snared the sun as he climbed out and beat him with the jawbone of their grandmother until he agreed to slow.\n\nFrom that day the sun has crossed slowly enough that a fish can be caught, a meal cooked, a child taught.',
     'Some things move too fast for ordinary use. It is the work of heroes to make them serve the day.',
     256),

    ('how-kiwi-lost-his-wings',
     'Maori',
     'How the Kiwi Lost His Wings',
     E'Tane, the god of the forest, saw that bugs were eating his trees. He called the birds. ‘Who will come down from the high branches and live on the forest floor and eat the bugs?’\n\nTui said, ‘It is too dark down there.’ Pukeko: ‘My feet would get wet.’ Pipiwharauroa: ‘I am too small.’ Kiwi looked up. He had the most beautiful wings of any bird. ‘I will come down,’ he said.\n\nTane said: ‘Then your wings will shrink to small useless things. Your bright feathers will become brown. You will never see daylight again.’ ‘I will still come down.’\n\nAnd that is why kiwi has no wings, and brown feathers, and walks the forest floor — and is honoured above all birds.',
     'The greatest honour is sometimes given to the bird who agrees to lose its wings for the work.',
     257),

    ('the-snow-lion',
     'Tibetan',
     'The Turquoise-Maned Snow Lion',
     E'High in the snow mountains lived a snow lion with a turquoise mane. She was solitary and kind. A poor woman climbed the mountain each summer to visit her, and the snow lion gave her a small bowl of milk that turned to gold by the time the woman reached home.\n\nA greedy man heard. He climbed up with two great pots. He demanded a full pot. The snow lion looked at him a long time, then dipped her paw and filled it.\n\nWhen he reached the bottom of the mountain, the milk was still milk. He poured it out in fury. He went up again. The lion was gone. She had moved to another mountain that no one greedy ever found again.',
     'Some sources only flow for the small bowl. The big pot scares the gold away.',
     258),

    ('heungbu-and-nolbu',
     'Korean folk',
     'Heungbu and Nolbu',
     E'Two brothers — Heungbu the kind and poor, Nolbu the rich and cruel — lived in a village. One spring Heungbu found a swallow chick fallen from a nest with a broken leg. He bound it carefully with thread and nursed it through the season.\n\nIn the autumn the swallow flew away with the others. The next spring it returned, dropped a single seed at his feet, and flew on. Heungbu planted the seed. It grew into a vine of gourds. When opened, each gourd spilled out gold and silver and rice.\n\nNolbu, hearing, hunted a swallow chick and broke its leg himself, then nursed it. The next spring it brought him a seed. He planted it. The gourds grew. He cut them — and out poured demons, snakes, and fire. He was ruined.',
     'A kindness done freely is rewarded; a kindness manufactured for reward brings demons.',
     259),

    ('the-sun-and-moon-brother-sister',
     'Korean folk',
     'The Sun and Moon Brother and Sister',
     E'A tiger ate a poor woman travelling home, then put on her clothes and went to her cottage to fetch her two children. He knocked at the door pretending to be their mother.\n\nThe children noticed the rough paw, the deep voice. They climbed out the back window into a tall tree. The tiger climbed after them. The boy prayed to heaven: ‘If we are good, send a rope.’ A rope came down. They climbed.\n\nThe tiger called: ‘Send me a rope too.’ A rotten one came. He climbed; it broke; he fell.\n\nIn heaven the boy became the sun and the girl became the moon — and they are watching their cottage still, by night and by day.',
     'Truth, even from a small voice, parts good rope from rotten. Trust your sense of the rough paw.',
     260),

    ('the-tiger-and-the-persimmon',
     'Korean folk',
     'The Tiger and the Dried Persimmon',
     E'A tiger crept up to a peasant’s house at night to steal an ox. From inside he heard a baby crying. The mother was trying to soothe it. ‘Hush — a tiger is coming.’ The baby cried louder.\n\n‘Hush — a wolf is at the door.’ Louder still.\n\n‘Hush — here is a dried persimmon.’ The baby was instantly silent.\n\nThe tiger thought, ‘What manner of beast is a “dried persimmon”, that even a tiger and a wolf cannot quiet a baby, but he can?’ He fled in terror.',
     'The biggest fear is sometimes only what we have not understood. Listen at the door before you flee.',
     261),

    ('momotaro-second',
     'Japanese folk',
     'Issun-Boshi the One-Inch Boy',
     E'A childless old couple prayed for a child. The gods gave them a tiny son the size of a thumb. They named him Issun-Boshi. He grew, but only in spirit; his body remained one inch tall.\n\nWhen old enough, he set off to seek his fortune. His sword was a sewing needle. His ship was a rice bowl. His oar a chopstick. He travelled down the river and into the great city, served a noble family, and one day defended the noble lord’s daughter against a great oni (ogre).\n\nHe stabbed the oni from inside its mouth with his needle. The oni fled, dropping a magic mallet. The girl tapped the mallet, wishing him grown. He stood, full-sized.',
     'The size of a champion is measured at the heart, not the shoulders. A small body with a needle can do what a great army hesitates to.',
     262),

    ('the-old-man-makes-flowers-bloom',
     'Japanese folk',
     'The Old Man Who Made the Cherry Trees Bloom',
     E'A kind old couple kept a small white dog they loved like their own son. The dog led them once to a spot in the garden where they dug up a chest of gold.\n\nA greedy neighbour borrowed the dog. The dog led him to a place; he dug; he found only bones. He killed the dog in fury.\n\nThe kind old man buried the dog under his cherry tree. He cut a branch and made a small wooden mortar. The mortar, when used, produced gold cakes. The neighbour borrowed it, found only sour rice, and burned it.\n\nThe kind old man took the ashes, scattered them on bare cherry trees in winter, and the trees bloomed instantly out of season. The lord of the land made him an honoured court gardener. The neighbour, trying the same trick, only put soot in the lord’s eyes — and was driven out.',
     'A gift bound to a kind heart bears flowers; the same gift in a greedy hand bears soot. The carrier matters more than the gift.',
     263),

    ('the-three-billy-goats-gruff',
     'Norwegian folk',
     'The Three Billy Goats Gruff',
     E'Three goats — small, middle, and great — wished to cross a bridge to a meadow on the other side. Beneath the bridge lived a fierce troll.\n\nThe smallest goat trip-trapped over. ‘Who goes there?’ roared the troll. ‘Only little me. Wait for my big brother — he is much fatter.’ The troll let him pass.\n\nThe middle goat trip-trapped over. ‘I am only middle-sized. My big brother is huge — wait for him.’ The troll let him pass.\n\nThe great billy goat came. The troll leapt up. The goat lowered his great horns and tossed the troll into the river.\n\nAll three crossed and ate well in the meadow.',
     'Sometimes the right answer is to let the small pass, knowing the great is coming behind. Don’t try to eat at the wrong moment.',
     264),

    ('the-tongue-cut-monk',
     'Tibetan',
     'The Wise Monk and the Tiger',
     E'A wandering monk arrived at a village in a state of terror. ‘There is a great tiger in the forest! He will eat us all!’ The villagers, alarmed, gathered weapons. The monk added: ‘He is twice the size of a horse. His teeth as long as my arm.’\n\nThey hunted all night and found nothing. Disappointed and angry, they rounded on the monk. ‘Where is the tiger?’\n\n‘There was no tiger,’ said the monk calmly. ‘But you have shown me what fear can make a village do. Save that energy now for what is real.’',
     'Not every alarm is the truth; not every alarm is harmless. Use the response on what is true.',
     265),

    ('the-wedding-ring',
     'Hasidic / Jewish',
     'The Wedding Ring',
     E'A king summoned his wisest counsellor. ‘Make me a ring,’ he said, ‘with words upon it that will make me sad when I am too happy, and happy when I am too sad.’\n\nThe counsellor went away and worked for a long time. He brought back a plain gold ring engraved with four words: This Too Shall Pass.',
     'Both the high days and the low days are passing through. The ring fits any finger.',
     266),

    ('the-three-questions-buddha',
     'Buddhist',
     'The Three Questions of the Old Monk',
     E'A young man, troubled, came to an old monk. ‘Master, what is the most important time?’ ‘Now.’\n\n‘Who is the most important person?’ ‘Whoever is in front of you.’\n\n‘What is the most important thing to do?’ ‘To care for them.’',
     'Three questions, one set of answers. Carry them in your pocket.',
     267),

    ('ibrahim-and-the-beggar',
     'Sufi',
     'Ibrahim and the Beggar',
     E'Ibrahim ibn Adham, who had once been king and given up the throne for a Sufi’s patched coat, was sitting on a riverbank when a passer-by mistook him for a beggar and gave him a small coin.\n\nIbrahim bowed and accepted it gracefully. His friends were astonished. ‘Why did you take it? You who have given up a kingdom.’\n\n‘He needed the merit of giving more than I needed to refuse him. Charity is also for the giver.’',
     'To accept gracefully is sometimes a greater service than to refuse proudly.',
     268),

    ('the-three-sieves-second',
     'Sufi / folk',
     'The Three Sieves (II)',
     E'(A second telling, in a different voice.)',
     'Pass news through three sieves: is it true? is it kind? is it useful? If most of it has fallen through, do not pass it on at all.',
     269),

    ('the-old-king-and-the-three-sons',
     'Indian folk',
     'The Old King and the Three Sons',
     E'A king grew old and wished to leave his throne to the wisest of his three sons. He gave each one a small bag of coins. ‘Fill your room with anything you wish. Whoever fills it best will be king.’\n\nThe first bought hay. He filled his room halfway. The second bought feathers. He filled his almost to the ceiling. The third bought a small candle. He stood it in the middle of his room and lit it. The light filled every corner.\n\nThe king crowned him.',
     'A small light fills more than great heaps of weight. Choose wisdom over volume.',
     270),

    ('the-tortoise-and-the-mango',
     'Indian folk',
     'The Tortoise and the Mango',
     E'A tortoise saw a mango fall from a tree. He climbed up onto a stone and tried to take it in his mouth. He could not lift it; it was too round.\n\nA monkey came along, picked it up, took a bite, and put it down again. ‘There. Now you can carry it home.’ The tortoise carried home the half-eaten mango.\n\n‘How did you eat it before, when you cannot bite a mango?’ he asked the monkey. ‘I waited until someone else had a problem like mine. Then I helped them — and helped myself at the same time.’',
     'Honest cleverness solves two problems with one act.',
     271),

    ('the-faithful-bird',
     'Hitopadesha',
     'The Faithful Bird and the Fool',
     E'A small bird and a foolish king were friends. The bird brought him news from far countries each day.\n\nOne afternoon a fly landed on the king’s nose while he napped. The bird, eager to defend him, struck — and broke the king’s nose with his sharp beak.\n\n(A second telling. The point is the same.)',
     'A loyal fool with a beak is no more useful than a loyal fool with a sword. Choose your defenders for what they think.',
     272),

    ('the-dog-and-the-feast',
     'Aesop',
     'The Dog Invited to the Feast',
     E'A man invited his neighbour to a great feast. The neighbour’s dog ran along too. ‘What a feast,’ thought the dog as he peeped in. ‘I shall stuff myself.’\n\nA cook saw him sneaking under the table, picked him up by the legs, and tossed him out the back window into the street.\n\nOther dogs gathered. ‘What was the feast like?’ The dog, dazed, said: ‘I drank so much that I cannot even remember which way I came home.’',
     'A free meal often delivers a free toss. Be wary of the kitchen door you sneak in by.',
     273),

    ('the-fox-and-the-thicket',
     'Aesop',
     'The Fox and the Thicket',
     E'A fox, fleeing the hounds, saw a man at the edge of the thicket. ‘Friend,’ said the fox, ‘hide me.’ The man pointed to a hollow.\n\nThe fox hid. The hounds came. ‘Have you seen a fox?’ ‘No,’ said the man — but he pointed at the hollow with his hand. The hounds were busy and did not see the gesture. They ran on.\n\nWhen the fox came out, he thanked the man cooly. ‘Your tongue said one thing. Your hand said another. Next time, friend — match them.’',
     'Beware the rescuer whose hand and mouth do not agree. Help is what the whole body does.',
     274),

    ('the-three-rings',
     'Italian folk',
     'The Three Rings',
     E'A father had three sons and one ring, the family heirloom. He could not bear to choose. He went to a goldsmith and had two perfect copies made — so perfect not even he could tell. On his death he gave each son a ring and said: ‘The true ring will reveal itself in the wearing — by deeds.’\n\nFor years the brothers each treasured the ring he had been given. Each lived a kind, generous life — perhaps to prove that his was the true one.\n\nWhich was real? Even the goldsmith could not say.',
     'Some inheritances are not in the metal but in how the wearer chooses to live. Behave as if you carry the true one.',
     275),

    ('the-emperor-the-soldier-and-the-truth',
     'Russian folk',
     'The Emperor and the Soldier',
     E'A new soldier on watch outside the emperor’s window saluted poorly when the emperor passed. The emperor stopped. ‘Your salute is sloppy.’\n\nThe soldier said simply: ‘Your majesty, I am tired. I have been on this post since dawn.’\n\nThe emperor looked at his hands, then at the soldier’s. He took the rifle from him, set it aside, and stood at the post himself for an hour while the soldier ate and rested.\n\nThe captain of the guard, when he found out, dared not speak.',
     'A great seat does not exempt a man from the small work of others. Try the post for an hour and your judgements will soften.',
     276),

    ('the-sailor-and-the-monk',
     'East Asian folk',
     'The Sailor and the Monk',
     E'A young sailor mocked an old monk on the deck. ‘What good is your meditation? When the storm comes you will pray and the boat will still sink. I am the one who will save us with the rudder.’\n\nThe storm came. The young sailor turned the rudder and shouted at the men. The boat lurched. Mast cracked. The monk sat very still in the middle of the deck, as if planted there. The men, looking at him, calmed. They worked together. The boat held.\n\nLater the sailor came to him quietly. ‘Why did your stillness do anything?’ ‘A still centre,’ said the monk, ‘steadies the spinning wheel. Sometimes the rudder is in the body, not the boat.’',
     'In a storm, a calm body is also a tool of saving. Do not despise stillness.',
     277),

    ('the-judge-of-the-baby',
     'World folk',
     'The Judge of the Two Mothers',
     E'(A second voice on a famous theme — different teller, same lesson, told to children at bedtime.)',
     'A real love would rather lose what it loves than see it cut. The willingness to give up names the owner.',
     278),

    ('the-king-who-listened-to-the-river',
     'Indian folk',
     'The King Who Listened to the River',
     E'A young king grew impatient with his ministers. ‘Old men say only old things. I shall make my own decisions.’ He decreed many laws in haste and many wars in pride.\n\nHis kingdom suffered. He went out alone one night and sat by the river. ‘What should I do?’ The river said nothing.\n\nHe sat for a long time. He noticed that the river did not push the rocks; it found the way around them. He noticed that the river did not speak; it carried what it carried. He noticed that the river was old.\n\nHe went back. He listened to his ministers. He undid as many of his haste-laws as he could. The kingdom slowly healed.',
     'A river is older than a king. Sit with it long enough to hear how slow movement becomes great rivers.',
     279),

    ('the-clever-daughter-in-law',
     'Indian folk',
     'The Clever Daughter-in-Law',
     E'A miser sent his three daughters-in-law back to their parents’ houses for a holiday. ‘When you return,’ he said, ‘bring me three impossible things: water tied in paper, fire wrapped in paper, and a man who cannot speak to the law.’\n\nTwo daughters-in-law returned weeping, empty-handed. The third returned smiling, with three small things in a basket: a block of ice (water tied in the paper of cold), a paper lantern with a candle inside (fire wrapped in paper), and a deaf-mute servant.\n\nThe miser laughed. ‘In this house, you shall be the manager.’',
     'Impossible problems are sometimes only puzzles in different clothing. Read the words again.',
     280),

    ('the-wise-king-and-the-pearl',
     'Persian folk',
     'The Wise King and the Pearl',
     E'A king found a great pearl in his garden one morning. His three counsellors each gave a different value. The first: ‘Worth a thousand camels.’ The second: ‘Ten thousand.’ The third: ‘A hundred thousand.’\n\nThe king took the pearl to a poor old woman in the market. ‘What is this worth?’ ‘Nothing, sire — I cannot eat it.’\n\nHe took it to a thirsty traveller in the desert. ‘What is this worth?’ ‘Nothing — I would trade it for a cup of water.’\n\nHe took it to a jeweller. ‘A hundred thousand camels.’\n\n‘Now I know,’ said the king, ‘the value of the pearl is not in the pearl. It is in who is holding it.’',
     'Worth shifts with the holder. The same gift is priceless to one and worthless to another.',
     281),

    ('the-magic-spinning-wheel',
     'Russian folk',
     'The Magic Spinning Wheel',
     E'A poor girl was given a magic spinning wheel. ‘Spin steadily,’ said the gift-giver. ‘Whenever you stop, you will find the thread you have made already in your basket — but the basket grows in proportion to your steadiness.’\n\nShe spun a little each day. The basket filled at the same pace. She tried to spin for many hours one day to fill it faster. The basket emptied as she rushed.\n\nShe went back to her steady pace. The basket filled again, in time.',
     'Steady labour fills the basket. Greedy speed empties it.',
     282),

    ('the-tortoise-and-the-eagle-second',
     'Aesop',
     'The Tortoise and the Eagle (II)',
     E'(A second voice on a familiar theme.)',
     'Fly above your kind only with someone who can carry you back down. Many tortoises ask the eagle and meet the rocks.',
     283),

    ('the-fishermans-son',
     'Indian folk',
     'The Fisherman''s Son',
     E'A poor fisherman lived with his son in a hut by the sea. They had no boat. Each morning the boy stood on the rocks and watched the great fishing boats go out.\n\n‘Father — buy me a boat.’ ‘We have no money.’ ‘Then I shall earn it.’\n\nHe began by mending other men’s nets for one paisa a day. He saved. After many years he bought a small boat. His father lived to see it. On its first day at sea the boy went alone, caught a single great fish, and at evening sold it for the price of three boats.',
     'A small daily saving builds the boat that catches the great fish. Do not despise the paisa-job.',
     284),

    ('the-greedy-ant',
     'Aesop',
     'The Greedy Ant',
     E'An ant found a single grain of wheat in the road, large enough to feed her family for a week. She tried to drag it home. It was too heavy. She called for help. ‘But share it with no one,’ she added, in case the help was a threat.\n\nNo one came. Eventually a kind beetle passed by and helped her, asking nothing. She, in shame, broke off a piece and gave it to him.\n\n‘See,’ said the beetle. ‘The grain is lighter when shared, and not poorer. Carry less and arrive with more.’',
     'A burden carried alone weighs more than a burden shared. Even greedy ants learn this on the road.',
     285),

    ('the-woodcutter-and-the-river',
     'Indian folk',
     'The Woodcutter and the River',
     E'A woodcutter walked home with his bundle on his head, exhausted. He stopped to drink at a stream. A small voice said: ‘Why do you carry the wood on your head? The river will carry it for you, all the way to your village.’\n\nHe did not know who spoke, but he tried it. He floated the bundle on the water. By evening it had drifted gently to the riverbank near his home, and he walked behind it whistling.\n\nHe never saw the small water-spirit who had whispered. But he carried wood that way for the rest of his life.',
     'Help, even unseen, repays kindness with ease. Drop the load on the water sometimes.',
     286),

    ('the-faithful-elephant',
     'Indian folk',
     'The Faithful Elephant',
     E'An elephant was bonded to a young prince since childhood. They grew up together. When the prince was banished by a wicked uncle, the elephant followed him into the forest, fed him with branches, sheltered him with his great body, and stood guard for many seasons.\n\nWhen the prince at last returned and reclaimed his throne, the elephant came too — but now old, slow, and grey. Some courtiers mocked: ‘Why keep this old beast?’\n\nThe king said nothing. He fed the elephant by his own hand. When the elephant died, he had the funeral rites of a chief minister.',
     'Honour the friend of your bad days; he is rarer than a thousand new friends in your good days.',
     287),

    ('the-cat-the-mouse-and-the-cheese',
     'European folk',
     'The Cat, the Mouse, and the Cheese (II)',
     E'Two mice fought over a cheese. They asked the cat to settle.\n\nHe weighed it. ‘This piece is heavier — I shall bite some off.’ Bite. ‘Now this one is heavier — I shall bite some off.’ Bite. So he went, bite by bite, until both halves were nearly gone, and he ate the rest.\n\nThe two mice walked home with empty mouths.',
     'Do not give the wolf the scales. Disagreement is sometimes settled best between the disagreers.',
     288),

    ('the-three-honest-women',
     'Indian folk',
     'The Three Honest Women',
     E'A traveller asked three women on a road to direct him to the next village.\n\nThe first answered briefly: ‘Three days’ walk that way.’ He thanked her and walked.\n\nThe second answered: ‘Three days. The road is muddy after the second day. Wear good shoes.’\n\nThe third answered: ‘Three days. Wear good shoes. There is a kind family in the third house in the third village; tell them I sent you, and they will give you supper.’\n\nHe travelled. The shoes saved him. The family fed him. He never forgot which woman’s answer had taken him farthest.',
     'A short answer is true. A complete answer is kind. The complete answer travels furthest.',
     289),

    ('the-three-questions-tagore',
     'Tagore',
     'The Three Questions of the Beggar',
     E'A beggar came to the gates of a king. ‘Sire, three questions. What is the kindest sound? What is the strongest weight? What is the most beautiful colour?’\n\nThe ministers gave many answers. The king took the questions home.\n\nThat night his small daughter laughed in her sleep. He stood at her door. He realised: the kindest sound is a child laughing. He went down to the courtyard and lifted his old, ailing mother in his arms — she was lighter than the smallest grain on his shoulder, but he understood: the strongest weight is the love we carry for those who once carried us. He stepped outside. Above him spread the dawn — pink and grey and gold.\n\nHe came back to the gates with answers, but the beggar was gone. ‘Send word everywhere,’ the king said, ‘that the answers are: the laugh of a child, the love of a parent, the colour of a sunrise.’',
     'The biggest questions are sometimes already answered in a small house and a long sky.',
     290),

    ('the-debt-and-the-day',
     'Indian folk',
     'The Day That Repaid the Debt',
     E'A poor man borrowed a small sum from a rich man at high interest. Each year he paid only the interest; the principal grew like a tree. Many years later he could not pay either.\n\nThe rich man went to the king for justice. The king listened, then said: ‘Each of you, count the days you have spent in worry. Days of joy stolen by this debt. Whichever has lost more days, the other shall pay him in days of his life.’\n\nThe rich man calculated. He had spent more days angry about getting his money back than the poor man had spent worried about paying. The king cancelled the debt.',
     'The interest of anger sometimes exceeds the principal of the loss. Watch what your collection costs you.',
     291),

    ('the-old-mans-three-sons',
     'European folk',
     'The Old Man and His Three Sons (II)',
     E'(A second voice on the bundle-of-sticks theme.)',
     'Together a family is a bundle that cannot be broken. Apart, the smallest hand can snap them.',
     292),

    ('the-fox-and-the-mountain-spring',
     'Sufi / folk',
     'The Fox and the Mountain Spring',
     E'A fox climbed a hot mountain and at last found a tiny spring trickling from a rock. He bent to drink. The spring said: ‘Will you fight to keep me alone, fox, or share me?’\n\nThe fox laughed. ‘There is no one else here.’ He drank his fill.\n\nThe next day other animals came. The fox stood between them and the spring. ‘Mine.’ He fought a goat. He bit a deer. He drove a bird off. The spring, that same evening, vanished into the rock; only damp earth remained.\n\nThe animals walked back down. The fox stayed at the dry stone for many days, and never drank again from that spring.',
     'A spring that is not shared dries up. Greed at the source ends the source.',
     293),

    ('the-monk-and-the-thief',
     'Buddhist',
     'The Monk and the Thief',
     E'A monk lived alone in a hut at the edge of a village. He owned a single bowl, an old robe, and a small lamp.\n\nA thief crept in one night. He turned the hut over, looking. The monk woke softly. ‘Friend, you have come a long way. Take what you wish. I am sorry I have so little.’ He took the lamp and offered it.\n\nThe thief, ashamed, fled. The monk sat by his door. ‘So poor a man,’ he murmured. ‘And he came so far. May he find what he is really looking for.’\n\nThe moon rose over the empty hut.',
     'Sometimes the right answer is to give the thief the lamp. He may begin to walk by it.',
     294),

    ('the-two-roads',
     'World folk',
     'The Two Roads',
     E'A traveller came to a fork in the road and asked an old man at the corner: ‘Which road is best?’ The old man pointed to the left. ‘That one is short and pleasant.’ He pointed to the right. ‘That one is long and hard.’\n\nThe traveller took the left. Within a day he came back, exhausted. ‘That road dropped me into a swamp.’\n\nThe old man nodded. ‘So it does. The road called short and pleasant is sometimes the swamp road.’ He pointed to the right. ‘Take the long, hard one. It will get you home.’',
     'A short pleasant road is often a long swamp in disguise. Trust the old man at the corner.',
     295),

    ('the-fisherman-and-the-three-wishes',
     'European folk',
     'The Fisherman''s Three Wishes',
     E'A poor fisherman caught a fish that begged to be released — and offered three wishes.\n\nThe fisherman went home. He told his wife. She said at once: ‘I wish for a sausage.’ A sausage appeared on the table.\n\nFurious that one wish should be wasted, he said without thinking: ‘I wish that sausage were stuck on your nose.’ It was. They could not pull it off.\n\nThey used the third wish to remove it. They were as poor as before, and their dinner was one sausage.',
     'Wish slowly. Most wishes that are wasted are wasted in temper.',
     296),

    ('the-foolish-money',
     'Indian folk',
     'The Foolish Money',
     E'A young man inherited a fortune. He bought a fine horse, fine clothes, a fine house. He invited his old father to stay.\n\nThe father walked through the rooms quietly. ‘Son, all this is fine. But what work do you intend to do?’ ‘Work? I am rich.’\n\nA year later, the horse went lame, the clothes wore out, the house was robbed. The young man came to his father in despair. The father took him to the field. ‘Now you can begin.’ The son worked the field. In ten years he was rich again — and this time, no horse could lame him.',
     'Money without work is a thin cloth. Work without money is still warm cloth in winter.',
     297),

    ('the-emperor-and-the-honest-boy',
     'Akbar-Birbal',
     'The Emperor and the Honest Boy',
     E'Akbar wished to test a boy who was said to be unfailingly honest. He had the child brought to him and gave him a small bag of coins. ‘Take this to the market and buy me sweets.’\n\nThe boy went and returned with the sweets and the change. Akbar praised him.\n\nA week later he gave the boy a far larger bag. ‘Buy me a fine horse.’ The boy returned with the horse, the receipt, and the change. Akbar praised him again.\n\nA month later he gave him a sealed pouch. ‘Carry this to a far city and give it to a man named Sayyid. Speak to no one of its contents.’ The boy returned weeks later. ‘Did you open it?’ ‘No, sire.’ ‘Were you tempted?’ ‘Yes, sire — once.’ ‘What stopped you?’ ‘That you had trusted me, sire. I would rather lose the world than that trust.’\n\nThe pouch held a single grain of rice — a test. Akbar made the boy his second messenger.',
     'A man who would not even open the bag is the man you can send to the kingdom’s edge.',
     298),

    ('the-sage-and-the-king',
     'Indian folk',
     'The Sage Who Refused the Throne',
     E'A wandering sage was so wise that the king of the country offered him the throne. ‘I am old and have no son. Take it.’\n\nThe sage refused. ‘But why? You would be the greatest of kings.’\n\n‘Because the moment I sit on it, I will have to defend it. The moment I have to defend it, I will see enemies in friends. The moment I see enemies in friends, I will be a worse man than I am.’\n\nThe king understood. He made his minister king instead, and walked alongside the sage for a year.',
     'Some honours undo their holders. Refuse what would unmake you.',
     299),

    ('the-bird-that-trusted-the-wind',
     'World folk',
     'The Bird That Trusted the Wind',
     E'A small bird could not find food in a long winter. She held tight to her branch in the cold wind, afraid to let go.\n\nAt last, weak with hunger, she let go — meaning to fall. The wind caught her. She glided down and across to a field where there was grain and other birds.\n\nShe never gripped a frozen branch so hard again.',
     'Sometimes you must let go before you fly. The branch is not the only thing holding you.',
     300)
on conflict (slug) do nothing;
