"""System Design knowledge bank — structured, broad-scope reference.

Powers the in-app "System Design" track on the Interview Prep page and
mirrors SYSTEM_DESIGN_ECOMMERCE_BANK.md. Each entry carries the full
schema: problem it solves, answer/how it works, real example, use cases,
architecture (ASCII), disadvantages, competing technologies.

Static reference content; per-user edits live in system_design_overrides
(see MIGRATION_SYSTEM_DESIGN_OVERRIDES.sql) and are merged at serve time.
"""

CATEGORIES = {
    "core": "Core Building Blocks",
    "data_stores": "Databases & Data Stores",
    "data_platforms": "Data Platforms at Scale",
    "data_analytics": "Data Analytics",
    "data_modeling": "Data Modeling",
    "ecommerce": "E-commerce Scenarios",
}


def E(cat, title, problem, answer, example, use_cases, arch, disadv, competing):
    return {
        "cat": cat, "title": title, "problem": problem, "answer": answer,
        "example": example, "use_cases": use_cases, "arch": arch,
        "disadvantages": disadv, "competing": competing,
    }


ENTRIES = [
    # ─────────── Core Building Blocks ───────────
    E("core", "Load Balancing",
      "A single server can't handle all traffic and is a single point of failure.",
      "A load balancer spreads requests across a server pool (Round Robin, Least Connections, IP Hash, Weighted). L4 balances on IP/port, L7 on HTTP content. Health checks evict dead nodes.",
      "AWS ALB fronts a fleet of catalog instances; sticky sessions pin a user to one node when needed.",
      "Horizontal scaling, high availability, zero-downtime deploys (drain + rotate).",
      "Client -> [Load Balancer] -> {App1, App2, App3}  (health-checked pool)",
      "Itself a potential SPOF (needs redundancy); adds a hop; L7 inspection costs CPU.",
      "NGINX, HAProxy, AWS ELB/ALB/NLB, Envoy, GCP Load Balancing; DNS round-robin (crude)."),
    E("core", "Caching",
      "Recomputing/re-fetching the same data is slow and overloads the database.",
      "Keep hot data in RAM. Patterns: cache-aside, read/write-through, write-back. Eviction: LRU/LFU/TTL. The hard part is invalidation (keeping cache consistent with source).",
      "Product pages cached in Redis with a 5-min TTL; on price change the key is invalidated.",
      "Catalog, sessions, computed feeds, rate-limit counters, hot inventory reads.",
      "Client -> App -> [Redis] --hit--> return; miss -> DB -> populate -> return",
      "Stale data; invalidation is hard; thundering herd on expiry; extra cost.",
      "Redis, Memcached, in-process (Caffeine/Guava), CDN edge, Hazelcast."),
    E("core", "CDN (Content Delivery Network)",
      "Serving static/media from one origin is slow for distant users and hammers the origin.",
      "Geo-distributed edge servers cache content near users; requests hit the nearest PoP. Pull (lazy) or push (pre-load).",
      "Images, CSS/JS, video served from CloudFront edges; origin (S3) hit only on miss.",
      "Images, static assets, video, cacheable API responses.",
      "User(IN)->Edge(Mumbai)-miss->Origin(S3); User(US)->Edge(Virginia)",
      "Cost; invalidation lag for updated assets; not for personalized/dynamic content.",
      "CloudFront, Akamai, Cloudflare, Fastly, GCP CDN."),
    E("core", "Message Queues / Async Processing",
      "Slow or spiky work shouldn't block the user request; services shouldn't be tightly coupled.",
      "Producers push messages; consumers process asynchronously at their own pace. Decouples, buffers spikes, enables retries. Delivery is usually at-least-once (needs idempotency).",
      "On checkout, publish OrderPlaced; email, inventory and analytics consume independently.",
      "Emails/notifications, order pipelines, media processing, decoupling, load leveling.",
      "Checkout -> [Queue] -> {Email, Inventory, Analytics} workers",
      "Eventual consistency; ordering & duplicate handling; another system to run; harder debugging.",
      "Kafka, RabbitMQ, AWS SQS/SNS, GCP Pub/Sub, ActiveMQ, Redis Streams."),
    E("core", "Event-Driven Architecture / Pub-Sub",
      "Many services must react to the same event without the producer knowing about them.",
      "Producers emit events to topics; any number of subscribers consume independently (fan-out). A durable log (Kafka) adds replay and event sourcing.",
      "OrderPlaced fans out to inventory, loyalty, recommendation retraining, seller dashboard.",
      "Microservice choreography, real-time analytics, CDC, audit logs.",
      "Producer -> [Topic] -> {Sub A, Sub B, Sub C}  (independent consumers)",
      "Hard to trace end-to-end; eventual consistency; schema evolution; 'event soup'.",
      "Kafka, AWS SNS+SQS, GCP Pub/Sub, NATS, EventBridge."),
    E("core", "Rate Limiting",
      "Protect services from abuse/bots/spikes and enforce quotas and fairness.",
      "Algorithms: Token Bucket (bursty), Leaky Bucket (smooth), Fixed/Sliding Window counters. Usually a Redis counter keyed by user/IP/API-key.",
      "Add-to-cart capped at N req/s per user in Redis to blunt bots during a flash sale.",
      "API gateways, login/OTP, scraping/bot defense, flash-sale fairness.",
      "Request -> [Redis token bucket per key] -> allow / 429",
      "Distributed counting is tricky (skew, races); false positives block users behind shared NAT.",
      "Redis limiters, Kong/AWS API Gateway, Envoy, Cloudflare."),
    E("core", "API Gateway",
      "Clients shouldn't call dozens of services directly; cross-cutting concerns repeat everywhere.",
      "A single entry point routing to backends, handling auth, rate limiting, TLS termination, aggregation, versioning.",
      "Mobile app -> Gateway (validates JWT, rate-limits) -> catalog/cart/order services.",
      "Microservice front door, BFF, centralized auth.",
      "Clients -> [API Gateway] -> {Catalog, Cart, Order, ...}",
      "Potential bottleneck/SPOF; extra latency; can become a 'god' component.",
      "Kong, AWS API Gateway, Apigee, NGINX, Envoy, Spring Cloud Gateway."),
    E("core", "Microservices vs Monolith",
      "Scaling teams and components independently as a system grows.",
      "Monolith: one deployable, simple, scales as a unit. Microservices: many small independently deployable services owning their data, communicating via API/events.",
      "Split a monolith into catalog, cart, order, payment, inventory, search services.",
      "Large orgs, differing scale profiles, independent release cadences.",
      "Monolith: [ALL]  |  Microservices: {svc}-{svc}-{svc} + events",
      "Distributed complexity (network, partial failure, data consistency), ops overhead. Start monolith, split when justified.",
      "Modular monolith, SOA, serverless functions."),
    E("core", "CAP Theorem & Consistency Models",
      "Reasoning about trade-offs in distributed stores during network partitions.",
      "Under a partition, choose Consistency (block/stale-reject) or Availability (serve possibly-stale). Models: strong, eventual, causal, read-your-writes. PACELC adds latency-vs-consistency when no partition.",
      "Payments choose CP (correctness); catalog/reviews choose AP (always available, eventually consistent).",
      "Picking/tuning databases per workload.",
      "Partition present -> pick C or A; else -> pick Latency or Consistency (PACELC)",
      "No free lunch; 'eventual' surprises users (stale carts).",
      "CP: HBase, Spanner, Zookeeper. AP: Cassandra, Dynamo. Tunable: Cassandra quorums."),
    E("core", "Idempotency",
      "Retries / at-least-once delivery can process the same request twice (double charge/order).",
      "Client sends an idempotency key; server records it and returns the same result on repeats. Or design naturally idempotent ops (upserts, set-state).",
      "'Place order' carries an idempotency key; a retried checkout returns the existing order.",
      "Payments, order creation, any retried/queued write.",
      "Request(key) -> if key seen: return stored result; else execute + store",
      "Must store keys (TTL); concurrent duplicates need a unique constraint/lock.",
      "Stripe-style keys, DB unique constraints, dedup tables, exactly-once frameworks."),
    E("core", "CQRS (Command Query Responsibility Segregation)",
      "Read and write workloads have very different shapes and scale needs.",
      "Separate the write model (normalized, transactional) from the read model (denormalized, query-optimized), synced via events.",
      "Orders written to Postgres; a denormalized 'order history' projected into Elasticsearch for fast reads.",
      "High-read systems, complex reporting, event-sourced systems.",
      "Command -> Write DB -> events -> Read model(s) <- Query",
      "Complexity; eventual consistency between models; more moving parts.",
      "Plain CRUD, materialized views, read replicas."),
    E("core", "Saga Pattern (Distributed Transactions)",
      "No ACID transaction spans microservices, but a business flow (checkout) touches many.",
      "A sequence of local transactions, each emitting an event triggering the next; on failure run compensating transactions. Choreography (events) or orchestration (coordinator).",
      "Checkout saga: reserve inventory -> charge -> create order; on failure, release inventory.",
      "Order fulfillment, bookings, any multi-service transaction.",
      "Order -> reserve -> charge -> confirm ; compensate backwards on failure",
      "Complex to design/debug; eventual consistency; compensations for money are delicate.",
      "2PC (blocking, avoided), Temporal/Camunda orchestration, outbox pattern."),
    E("core", "Consistent Hashing",
      "Adding/removing nodes shouldn't remap almost all keys.",
      "Map nodes and keys onto a hash ring; a key belongs to the next node clockwise. Node changes only move adjacent keys. Virtual nodes even out load.",
      "Distributing cache keys across a Redis cluster; Dynamo/Cassandra partitioning.",
      "Distributed caches, sharded DBs, load balancers.",
      "[hash ring] key -> next node clockwise; +node moves only nearby keys",
      "Uneven load without vnodes; still some remap; more complex than modulo.",
      "Modulo hashing (simple, bad on resize), rendezvous hashing, range partitioning."),
    E("core", "Observability (Logs, Metrics, Tracing)",
      "You can't fix or scale what you can't see, especially across microservices.",
      "Logs (events), metrics (latency/QPS/error time-series), distributed tracing (a request's path via a trace ID). Alert on SLOs.",
      "A slow checkout is traced across cart->payment->inventory to find the bottleneck.",
      "Debugging, capacity planning, SLA/SLO monitoring, incident response.",
      "Services -> {logs, metrics, traces} -> collector -> dashboards/alerts",
      "Telemetry volume/cost; cardinality explosions; noise vs signal.",
      "Prometheus+Grafana, ELK/OpenSearch, Datadog, Jaeger/Zipkin, OpenTelemetry."),

    # ─────────── Databases & Data Stores ───────────
    E("data_stores", "SQL vs NoSQL",
      "Choosing storage for a given data shape, scale, and consistency need.",
      "SQL: structured schema, relations/joins, ACID, strong consistency, vertical scale. NoSQL: flexible schema, horizontal scale, often eventual; families key-value, document, wide-column, graph.",
      "Orders/payments in Postgres (ACID); catalog/cart in DynamoDB (scale); recs graph in Neo4j.",
      "SQL for transactions & complex queries; NoSQL for scale, high write throughput, flexible data.",
      "SQL: rows+joins+ACID  |  NoSQL: KV / doc / wide-column / graph",
      "SQL harder to scale horizontally; NoSQL sacrifices joins/consistency, pushes logic to the app.",
      "Postgres, MySQL, Aurora / DynamoDB, Cassandra, MongoDB, Neo4j; Spanner (NewSQL bridge)."),
    E("data_stores", "Database Indexing",
      "Full-table scans are O(n) and slow for lookups/filters.",
      "An index (B-tree, or hash for equality) maps column values to row locations, making lookups O(log n). Composite indexes serve multi-column queries; covering indexes serve a query fully from the index.",
      "Index on orders(user_id, created_at) makes 'my recent orders' instant.",
      "Frequent WHERE/JOIN/ORDER BY columns, foreign keys, uniqueness.",
      "value -> [B-tree] -> row location (O(log n))",
      "Slows writes; uses storage; too many indexes hurt; unused indexes are pure cost.",
      "B-tree, Hash, GiST/GIN (Postgres), LSM-tree (write-heavy), inverted index (search)."),
    E("data_stores", "Sharding / Partitioning",
      "A single DB can't hold all the data or serve all the traffic.",
      "Split data across nodes by a shard key: hash-based (even, range-queries hard), range-based (range-friendly, hotspot risk), directory-based. Consistent hashing minimizes reshuffling.",
      "Shard orders by hash(user_id) so a user's orders live on one shard.",
      "Very large tables (orders, events, catalog at marketplace scale).",
      "Router/hash -> {Shard1, Shard2, Shard3}",
      "Cross-shard joins/txns hard; rebalancing painful; hotspots on skewed keys; ops complexity.",
      "Vitess (MySQL), Citus (Postgres), native (Mongo/Cassandra), app-level sharding."),
    E("data_stores", "Replication",
      "Availability, read scaling, and durability if a node dies.",
      "Copy data to multiple nodes. Leader-follower: writes to leader, reads from followers (async/sync). Leaderless/multi-leader (Dynamo quorum W+R>N) for write availability.",
      "Postgres primary handles writes; 3 read replicas serve catalog reads; failover promotes a replica.",
      "Read-heavy workloads, HA, geo-distribution, backups.",
      "Writes -> Leader -> async -> {Follower1, Follower2} <- reads",
      "Replication lag -> stale reads; sync replication adds latency; multi-leader conflicts.",
      "Postgres/MySQL replication, Mongo replica sets, Cassandra quorums, DynamoDB global tables."),
    E("data_stores", "TiDB (Distributed NewSQL / HTAP)",
      "Teams want MySQL-compatible SQL and ACID transactions but also horizontal scale and real-time analytics on the same data, without bolting on a separate warehouse.",
      "TiDB is an open-source distributed NewSQL database with a disaggregated architecture: stateless SQL layer (TiDB) + a distributed transactional KV store (TiKV, row-based, Raft-replicated, range-sharded into 'Regions') + a columnar engine (TiFlash) kept in sync via Raft learners. PD (Placement Driver) manages metadata, timestamps (TSO) and auto-rebalancing. It speaks the MySQL protocol, gives strong consistency (Percolator-style distributed transactions), and does HTAP: OLTP on TiKV, OLAP on TiFlash — the optimizer routes each query to the right engine.",
      "A payments/orders system that outgrew a single MySQL: shard-free horizontal scale on TiKV for transactions, while dashboards run analytical queries on TiFlash over the same live data — no ETL to a warehouse.",
      "Horizontally-scaling OLTP that outgrew MySQL, HTAP (fresh analytics on transactional data), multi-region strong consistency, MySQL migration without app rewrites.",
      "App -(MySQL proto)-> [TiDB SQL nodes] -> TiKV (row, OLTP) + TiFlash (columnar, OLAP)\n                                     ^ PD: metadata, TSO, rebalancing",
      "Operationally heavier than a single MySQL (many components); distributed-txn latency vs local; TiFlash adds storage; not ideal for tiny workloads; some MySQL feature gaps.",
      "CockroachDB, Google Spanner, YugabyteDB, Vitess (sharded MySQL), Aurora; Snowflake/ClickHouse for pure OLAP."),
    E("data_stores", "Aerospike (Real-time NoSQL KV)",
      "Applications need single-digit-millisecond reads/writes over terabytes-to-petabytes at very high throughput (100k–millions of ops/sec) with strong reliability and low cost.",
      "Aerospike is a distributed key-value/row store built for speed: a hybrid-memory architecture keeps the primary index in RAM but data on SSD (accessed directly, bypassing the filesystem), so it gets near-in-memory latency at SSD cost/capacity. It shards data with a smart-client + consistent-hash partition map (no proxy hop), replicates synchronously, self-heals, and offers strong-consistency or AP modes. Cross-datacenter replication (XDR) enables global low-latency.",
      "A real-time ad-tech bidder or fraud-scoring service reading a user profile in <1ms during a request; a recommendation feature store serving models at scale.",
      "Real-time bidding/ad-tech, fraud detection, recommendation/feature stores, session stores, any large low-latency KV workload.",
      "Smart client -(partition map)-> {Aerospike node} RAM index + SSD data; sync replica; XDR -> other DC",
      "Data-model is KV/row (not relational, limited joins/queries); operationally specialized; licensing for enterprise features; overkill for small/low-QPS apps.",
      "Redis (in-memory, smaller data), DynamoDB, Cassandra/ScyllaDB, Memcached, Couchbase."),
    E("data_stores", "Redis (In-memory Data Structure Store)",
      "You need microsecond-to-millisecond access to hot data and rich primitives beyond a plain cache.",
      "In-memory store with data structures (strings, hashes, lists, sets, sorted sets, streams, HLL, geo). Single-threaded command execution (atomic), optional persistence (RDB/AOF), replication, and Cluster mode for sharding. Also does pub/sub, Lua scripts, and atomic counters.",
      "Cart/session store, rate-limit token buckets, leaderboards (sorted sets), Redis Streams as a lightweight queue.",
      "Caching, sessions, rate limiting, leaderboards, queues, real-time counters, geo lookups.",
      "App -> [Redis] (RAM) --async--> AOF/RDB persistence; Cluster shards by hash slot",
      "RAM is expensive/limited; persistence is best-effort (can lose recent writes); large datasets need Cluster; not a system of record.",
      "Memcached (simpler cache), Aerospike (bigger-than-RAM), Hazelcast, DynamoDB DAX."),
    E("data_stores", "Cassandra (Wide-Column, AP)",
      "Massive write throughput and always-on availability across regions, with no single master.",
      "Leaderless, masterless wide-column store. Data partitioned by hash of the partition key across a ring; tunable consistency via quorums (W+R>N). LSM-tree storage (fast writes). You model tables per query (denormalized).",
      "Time-series/event data, order history at hyperscale, messaging inboxes.",
      "Write-heavy workloads, time-series, multi-region availability, huge datasets.",
      "Client -> any node (coordinator) -> replicas on ring; tunable quorum reads/writes",
      "No joins; query-first data modeling; eventual consistency by default; tombstone/compaction pitfalls.",
      "ScyllaDB (C++ rewrite), DynamoDB, HBase, Bigtable."),
    E("data_stores", "Elasticsearch (Search / Inverted Index)",
      "SQL LIKE is slow and can't do relevance, typos, or facets.",
      "An inverted index maps terms -> documents; adds tokenization, stemming, BM25 relevance, fuzzy matching, and aggregations/facets. Distributed via shards + replicas.",
      "Product search with typo tolerance, brand/price filters, and relevance ranking; also log analytics.",
      "Product search, autocomplete, log/observability analytics, faceted filtering.",
      "Docs -> [inverted index shards] ; query -> BM25 rank + facets",
      "Eventually consistent with source DB; ops-heavy; not a system of record.",
      "OpenSearch, Apache Solr, Algolia, Typesense, Postgres full-text (small scale)."),
    E("data_stores", "Object / Blob Storage",
      "Databases are wrong for large binary files (images, video, invoices).",
      "Store files as objects with metadata in a flat namespace over HTTP; near-unlimited, cheap, durable. Fronted by a CDN; uploads via pre-signed URLs.",
      "Product images and invoices in S3; the DB stores only the URL/key.",
      "Media, backups, static sites, data-lake storage.",
      "App -> pre-signed URL -> [S3 object] -> CDN edge -> user",
      "Higher latency than block storage; historically eventual consistency; not for frequent small updates.",
      "AWS S3, GCS, Azure Blob, MinIO, Ceph."),
    E("data_stores", "Distributed SQL (Spanner / CockroachDB)",
      "You want relational SQL + ACID transactions that also scale horizontally and survive region failures.",
      "Globally-distributed SQL: data auto-sharded into ranges, each Raft/Paxos-replicated; distributed transactions with synchronized clocks (Spanner's TrueTime) give external consistency. Looks like one SQL DB, scales like NoSQL.",
      "A global orders ledger needing strong consistency and multi-region survivability.",
      "Global OLTP, strong consistency at scale, multi-region resilience, MySQL/Postgres-compatible scale-out.",
      "SQL -> distributed txn coordinator -> Raft-replicated ranges (multi-region)",
      "Higher write latency (consensus + clock bounds); cost; operational complexity; some SQL limits.",
      "Google Spanner, CockroachDB, YugabyteDB, TiDB, Aurora (limited)."),

    # ─────────── Data Platforms at Scale ───────────
    E("data_platforms", "Data Warehouse (OLAP)",
      "Running heavy analytical queries on the production (OLTP) database slows the app and can't handle the scan volume.",
      "A columnar, analytics-optimized store for structured data, loaded via ETL/ELT from source systems. Columnar layout + massively parallel processing (MPP) make aggregations over billions of rows fast. Separates analytics from transactions.",
      "Sales/orders/clickstream loaded nightly (and via streaming) into Snowflake; BI dashboards and analysts query it.",
      "BI dashboards, reporting, ad-hoc analytics, ML feature generation.",
      "OLTP sources -> ETL/ELT -> [Warehouse (columnar MPP)] -> BI / SQL / ML",
      "Data latency (batch); cost at scale; schema rigidity; not for low-latency point lookups.",
      "Snowflake, BigQuery, Redshift, Databricks SQL, Synapse; ClickHouse (real-time OLAP)."),
    E("data_platforms", "Data Lake",
      "Warehouses are expensive and rigid for raw, semi/unstructured, or exploratory data at petabyte scale.",
      "Store raw data of any shape (JSON, logs, images, Parquet) cheaply in object storage, schema-on-read. Decouples storage from compute; many engines can query the same files.",
      "Raw clickstream, logs, images, and CDC dumps land in S3; Spark/Athena query on demand.",
      "Data science, ML training data, cheap archival, staging before the warehouse.",
      "Sources -> [Object storage (raw files)] <- query engines (Spark/Athena/Presto)",
      "Can become a 'data swamp' without governance; slow ad-hoc queries; no ACID/consistency by itself.",
      "S3/GCS/ADLS + Spark/Presto/Athena; vs warehouse (structured) and lakehouse (hybrid)."),
    E("data_platforms", "Data Lakehouse (Medallion Architecture)",
      "Teams don't want to maintain both a data lake (cheap, flexible) and a warehouse (fast, governed) with brittle copies between them.",
      "A lakehouse adds a transactional table format (ACID, schema enforcement, time travel) on top of cheap object storage, so one platform serves BI and ML. The medallion pattern layers data: Bronze (raw) -> Silver (cleaned/conformed) -> Gold (business-level aggregates).",
      "Databricks/Delta Lake: raw events -> Bronze; deduped/typed -> Silver; daily revenue marts -> Gold, all in S3, queried by SQL and Spark ML.",
      "Unified BI + ML on one copy, streaming + batch together, governed lake, cost-efficient scale.",
      "Sources -> Bronze(raw) -> Silver(clean) -> Gold(marts) on object storage (Delta/Iceberg)\n            + ACID table format -> BI & ML engines",
      "Younger tooling; table-format lock-in choices; still needs governance discipline; small-query latency vs a tuned warehouse.",
      "Databricks/Delta Lake, Apache Iceberg, Apache Hudi; vs Snowflake (warehouse) + separate lake."),
    E("data_platforms", "Open Table & File Formats (Iceberg/Delta/Hudi, Parquet)",
      "Raw files in a lake lack ACID, schema evolution, and efficient updates; row formats are slow for analytics.",
      "Columnar file formats (Parquet/ORC) compress well and enable column pruning for fast scans. Table formats (Apache Iceberg, Delta Lake, Hudi) add a metadata layer over those files giving ACID transactions, schema/partition evolution, time travel, and upserts on the lake.",
      "Iceberg tables over Parquet in S3 let multiple engines (Spark, Trino, Flink) read/write consistently with snapshots and rollbacks.",
      "Lakehouse storage, CDC upserts into a lake, multi-engine interoperability, GDPR deletes.",
      "Query engines -> [Table format metadata (Iceberg)] -> Parquet files in object storage",
      "Metadata/small-file management overhead; format wars/interop nuances; compaction needed.",
      "Iceberg, Delta Lake, Hudi (table formats); Parquet, ORC, Avro (file formats)."),
    E("data_platforms", "Data Mesh",
      "A single central data team becomes a bottleneck; centralized pipelines don't scale organizationally across many domains.",
      "A decentralized, organizational approach: domain teams own their data as 'data products' (discoverable, addressable, trustworthy, self-describing), on a self-serve platform, under federated computational governance. Shifts from centralized ownership to domain ownership.",
      "The 'orders' domain publishes a curated orders data product; the 'marketing' domain consumes it without a central team brokering every request.",
      "Large orgs with many domains, scaling data ownership, reducing central-team bottlenecks.",
      "Domain A -> data product | Domain B -> data product | ... on shared self-serve platform + federated governance",
      "Mostly an org/operating-model shift (hard); risk of duplication/inconsistency; needs strong platform + governance; can be overkill for small orgs.",
      "Centralized warehouse/lake team, Data Fabric (more tech-centric), hub-and-spoke."),
    E("data_platforms", "Change Data Capture (CDC)",
      "Downstream systems (search, cache, warehouse, other services) need to stay in sync with a source DB without dual-writes or slow polling.",
      "CDC streams row-level changes by tailing the database's write-ahead log/binlog and publishing insert/update/delete events (often to Kafka). Consumers apply them to keep replicas/indexes/warehouses current in near-real-time.",
      "Debezium reads Postgres WAL -> Kafka -> indexer updates Elasticsearch and loads the warehouse.",
      "Cache/search sync, warehouse ingestion, event-driven microservices, replication, outbox pattern.",
      "Source DB (WAL/binlog) -> [CDC (Debezium)] -> Kafka -> {Search, Cache, Warehouse}",
      "Ordering & schema-evolution handling; initial snapshot cost; exactly-once is hard; log retention.",
      "Debezium, Maxwell, AWS DMS, Fivetran, native logical replication."),
    E("data_platforms", "Batch vs Stream Processing (Spark/Flink)",
      "Some analytics can run on schedules over big datasets; others must react within seconds to live events.",
      "Batch processes large bounded datasets periodically (high throughput, high latency) — Spark/MapReduce. Stream processing handles unbounded events continuously with low latency and windowing/state — Flink/Spark Structured Streaming/Kafka Streams. Lambda architecture runs both; Kappa uses one streaming path.",
      "Nightly Spark job builds revenue marts (batch); Flink computes real-time 'trending products' from clickstream (stream).",
      "ETL/aggregations (batch); real-time metrics, fraud, alerting, personalization (stream).",
      "Bounded data -> [Spark batch] -> marts | Event stream -> [Flink] -> real-time views",
      "Batch: stale data. Stream: complex state/windowing, exactly-once & late-event handling, harder ops.",
      "Spark, Flink, Kafka Streams, Beam/Dataflow, Storm; Lambda vs Kappa architectures."),
    E("data_platforms", "Feature Store",
      "ML features computed ad-hoc drift between training and serving (train/serve skew) and get re-implemented per team.",
      "A central system to define, compute, store, and serve ML features consistently. Offline store (warehouse/lake) for training; online store (low-latency KV like Redis/Aerospike/DynamoDB) for real-time inference; the same definitions feed both to prevent skew.",
      "A 'user_30d_purchase_count' feature is computed once, served from the online store to the ranking model at request time and from the offline store for training.",
      "Recommendations, fraud, ranking, any real-time ML; feature reuse and governance.",
      "Sources -> feature pipelines -> {Offline store (train), Online store (serve)} -> models",
      "Infra complexity; consistency between online/offline; freshness vs cost; another platform to run.",
      "Feast, Tecton, Databricks/Vertex/SageMaker Feature Store; DIY Redis + warehouse."),

    # ─────────── Data Analytics ───────────
    E("data_analytics", "OLTP vs OLAP",
      "One database can't be great at both fast small transactions and heavy analytical scans.",
      "OLTP: many small, low-latency read/write transactions on current data, row-oriented, normalized (the app DB). OLAP: few large aggregation/scan queries over history, column-oriented, denormalized (the warehouse). Keep them separate; move data OLTP -> OLAP via ETL/CDC.",
      "Postgres serves the checkout (OLTP); Snowflake serves 'revenue by category last quarter' (OLAP).",
      "OLTP for the app; OLAP for BI, reporting, data science.",
      "App writes -> [OLTP row store] --ETL/CDC--> [OLAP column store] -> analysts",
      "Two systems to keep in sync; analytics data lags; cost of the pipeline.",
      "OLTP: Postgres/MySQL. OLAP: Snowflake/BigQuery/ClickHouse. HTAP (both): TiDB, SingleStore."),
    E("data_analytics", "Real-time / Streaming Analytics",
      "Batch reports are hours stale; some decisions (fraud, trending, ops alerts) need sub-second data.",
      "Ingest events into a stream (Kafka), process continuously with windowed aggregations and stateful operators (Flink), and serve results from a low-latency OLAP store or cache. Handle late/out-of-order events with watermarks.",
      "Live 'trending now' and real-time GMV dashboards during a sale, computed from the clickstream in seconds.",
      "Fraud, real-time dashboards, trending, anomaly detection, dynamic pricing signals.",
      "Events -> Kafka -> [Flink windows] -> real-time OLAP (Druid/ClickHouse) -> dashboard",
      "Complex state & exactly-once; late-data handling; higher ops cost than batch; harder to debug.",
      "Flink, Kafka Streams, Spark Streaming, Materialize, Apache Druid, Pinot, ClickHouse."),
    E("data_analytics", "BI, Dashboards & the Semantic Layer",
      "Analysts and execs need self-serve, consistent metrics without writing raw SQL or disagreeing on definitions.",
      "BI tools query the warehouse and visualize results. A semantic/metrics layer centralizes metric definitions (e.g., 'active user', 'GMV') so every dashboard computes them identically. Caching/extracts speed up dashboards.",
      "Looker/LookML (or dbt metrics) defines 'net revenue' once; Tableau/Looker dashboards reuse it.",
      "Executive dashboards, self-serve analytics, KPI reporting, consistent metrics.",
      "Warehouse -> [Semantic layer (metric defs)] -> BI tool -> dashboards",
      "Metric sprawl without governance; performance on huge data; extract staleness; tool lock-in.",
      "Looker, Tableau, Power BI, Superset, Metabase; dbt Semantic Layer, Cube, AtScale."),
    E("data_analytics", "ETL vs ELT",
      "Getting source data into an analytics store in the right shape, at scale, reliably.",
      "ETL: Extract, Transform (in a separate engine), then Load — transform before landing (good for constrained targets/compliance). ELT: Extract, Load raw, then Transform inside the powerful warehouse/lakehouse using SQL — the modern default given cheap elastic compute.",
      "Fivetran extracts app data and loads raw into Snowflake; dbt transforms it into clean marts (ELT).",
      "Warehouse/lake loading, data pipelines, analytics engineering.",
      "ETL: Extract -> Transform -> Load | ELT: Extract -> Load(raw) -> Transform (in warehouse)",
      "ETL: rigid, extra engine. ELT: raw sprawl, transform cost in the warehouse, needs governance.",
      "Ingest: Fivetran, Airbyte, DMS. Transform: dbt, Spark. Orchestrate: Airflow, Dagster."),
    E("data_analytics", "Clickstream / Event Analytics Pipeline",
      "Capture billions of user events (views, clicks, add-to-cart) for analytics, personalization, and BI.",
      "Client/edge emits events -> ingestion (Kafka) -> real-time stream processing for live metrics AND a sink to the lake/warehouse for batch. Lambda/Kappa architecture; downstream funnels, A/B, ML features.",
      "Events -> Kafka -> Flink (real-time metrics) + S3 -> warehouse (batch) -> BI + feature store.",
      "Funnels, A/B analysis, recommendation features, real-time dashboards, product analytics.",
      "Client -> collector -> Kafka -> {Flink -> real-time metrics ; Lake -> warehouse -> BI/ML}",
      "Data volume/cost; exactly-once vs at-least-once; schema evolution; late/out-of-order events.",
      "Kafka/Kinesis, Flink/Spark, Snowflake/BigQuery, Segment/RudderStack, Amplitude."),
    E("data_analytics", "A/B Testing & Experimentation Platform",
      "Teams need to measure whether a change actually improves a metric, at scale, without fooling themselves.",
      "Randomly assign users to variants (bucketing by hashed user id), log exposures + outcomes, and compute statistically-sound lifts (with guardrail metrics, sequential-testing corrections). A platform manages assignment, metrics, and analysis consistently.",
      "New checkout flow shipped to 5% behind an experiment; watch-time/conversion measured vs control before ramping.",
      "Feature launches, ranking/rec changes, pricing tests, UX changes.",
      "User -> hash bucket -> variant; exposures+events -> analysis -> lift & significance",
      "Peeking/false positives; interaction effects; network effects; underpowered tests; metric gaming.",
      "Optimizely, LaunchDarkly, Statsig, GrowthBook, in-house (Amazon Weblab / Google-style)."),

    # ─────────── Data Modeling ───────────
    E("data_modeling", "Common Data Model (Canonical Model)",
      "When many apps/services/partners each define 'customer' or 'order' differently, every integration needs custom mapping (N-to-N), and analytics can't join across systems.",
      "A Common (Canonical) Data Model is a shared, standardized schema for core business entities that all systems map to once. Integrations translate to/from the canonical model (N-to-1 instead of N-to-N). Industry CDMs (Microsoft Common Data Model / Dataverse, healthcare's OMOP, retail ARTS) provide ready entity definitions; you can also define your own enterprise canonical model.",
      "An enterprise defines a canonical 'Customer' entity; CRM, billing, and the webshop each map to it, so a unified 360 view and cross-system analytics 'just work'.",
      "Enterprise integration (canonical model in an ESB/iPaaS), master data management, data warehousing conformance, partner/EDI exchange, unifying microservice data for analytics.",
      "System A -> map -> [Canonical Model] <- map <- System B ; consumers read canonical (N-to-1)",
      "Upfront design + governance effort; a rigid canonical model can lag business change; over-generalization; someone must own it.",
      "Point-to-point mapping (simpler, doesn't scale), Microsoft CDM/Dataverse, industry models (OMOP, ARTS, FHIR), MDM tools."),
    E("data_modeling", "Dimensional Modeling (Star / Snowflake Schema)",
      "Normalized OLTP schemas are slow and unintuitive for analytics with many joins.",
      "Model analytics as facts (measurable events, e.g., a sale with quantity/amount) surrounded by dimensions (descriptive context: product, customer, date, store). Star schema = denormalized dimensions around a fact table; snowflake = normalized dimensions. Optimized for slicing/aggregating.",
      "A 'sales_fact' table joins to dim_product, dim_customer, dim_date, dim_store for BI queries like 'revenue by category by month'.",
      "Data warehouses, BI, reporting, cubes.",
      "dim_product \\ \n dim_date  -- [ fact_sales ] -- dim_customer \n dim_store /",
      "ETL to maintain; denormalization duplication; not for OLTP; grain mistakes cause wrong metrics.",
      "Data Vault (more flexible/auditable), One Big Table (wide denormalized), 3NF warehouse (Inmon)."),
    E("data_modeling", "Normalization vs Denormalization",
      "Balancing data integrity/write-efficiency against read/query performance.",
      "Normalization (1NF->3NF) removes redundancy so each fact lives once — great for OLTP integrity and cheap writes, but reads need joins. Denormalization duplicates data to avoid joins — faster reads, but writes must update copies and risk inconsistency. Choose by read/write ratio and consistency needs.",
      "OLTP orders schema is normalized; the analytics/read model and NoSQL catalog docs are denormalized for fast reads.",
      "OLTP (normalize), OLAP/read models/NoSQL (denormalize), caching layers.",
      "Normalized: many small tables + joins | Denormalized: fewer wide tables, duplicated data",
      "Normalized: join-heavy reads. Denormalized: update anomalies, storage, consistency burden.",
      "3NF (Inmon) vs star schema (Kimball) vs Data Vault; NoSQL denormalized docs."),
    E("data_modeling", "Slowly Changing Dimensions (SCD)",
      "Dimension attributes change over time (a customer moves cities); how do you keep history for correct point-in-time analytics?",
      "Techniques to handle dimension changes: Type 1 (overwrite, no history), Type 2 (add a new row with effective dates / current flag — full history), Type 3 (add a 'previous value' column — limited history). Type 2 is the workhorse for auditable analytics.",
      "A customer's address change adds a new SCD-Type-2 row so historical orders still map to the address at purchase time.",
      "Data warehousing, historical/point-in-time reporting, audit, regulatory analytics.",
      "SCD2: cust_key | attrs | valid_from | valid_to | is_current  (new row per change)",
      "Type 2 grows dimension size and complicates joins; Type 1/3 lose history; ETL complexity.",
      "CDC + merge logic, dbt snapshots, Data Vault satellites."),

    # ─────────── E-commerce Scenarios ───────────
    E("ecommerce", "Product Catalog Service",
      "Store and serve millions of products with fast, flexible, read-heavy access.",
      "Read-heavy (~100:1). Document store for flexible attributes; aggressive caching; images via CDN; denormalize for the product page; stream changes to search (CQRS-lite).",
      "Product docs in DynamoDB/Mongo, Redis for hot items, images in S3+CloudFront, CDC to search.",
      "Product detail page, listings, category browse.",
      "Client -> CDN -> API -> {Redis, Catalog DB} ; CDC -> Search index",
      "Cache invalidation on price/stock; eventual consistency to search; denormalization duplication.",
      "DynamoDB / MongoDB / Postgres+JSONB; Redis vs Memcached."),
    E("ecommerce", "Product Search & Autocomplete",
      "Fast, relevant, typo-tolerant search over the whole catalog with filters/facets.",
      "Index products in Elasticsearch (BM25); autocomplete via prefix/edge-n-grams or a Redis Trie; sync via CDC; rank by relevance + business signals (popularity, margin, availability).",
      "Search service consuming ProductUpdated into ES; autocomplete from a Redis Trie of top queries.",
      "Search bar, autocomplete, faceted filtering, 'did you mean'.",
      "Catalog -(events)-> Indexer -> ES ; search -> ES + Redis Trie",
      "Index lag; relevance tuning is ongoing; ES ops cost.",
      "Elasticsearch/OpenSearch, Algolia, Solr, Typesense."),
    E("ecommerce", "Shopping Cart",
      "Persist a user's items across sessions/devices with low latency and near-100% availability.",
      "Favor availability (AP). KV doc keyed by user/session in Redis/DynamoDB with TTL for guests; merge guest cart on login; validate price/stock at checkout, not on every add.",
      "Cart in DynamoDB (user_id -> items[]), Redis in front; guest carts by session cookie (30-day TTL).",
      "Add/remove/update items, cross-device cart, save-for-later.",
      "Client -> Cart API -> Redis -> DynamoDB ; checkout -> validate price/stock",
      "Stale prices/stock until checkout; guest->user merge conflicts; cross-region eventual consistency.",
      "Redis, DynamoDB, MongoDB; session vs persistent store."),
    E("ecommerce", "Checkout & Order Placement",
      "Turn a cart into a paid order reliably across inventory, payment, order — no double-charge or oversell.",
      "Orchestrate a Saga: reserve inventory -> charge -> create order -> confirm; compensate on failure. Idempotency key prevents duplicate orders; outbox pattern publishes events atomically with the DB write.",
      "Checkout orchestrator calls inventory, payment, order; on payment failure releases the reservation.",
      "The core buy flow.",
      "Cart -> Orchestrator: reserve -> charge(key) -> create(outbox) ; compensate on fail",
      "Distributed-transaction complexity; partial failures; eventual consistency; money compensations are delicate.",
      "Orchestration (Temporal/Step Functions) vs choreography; 2PC (avoided)."),
    E("ecommerce", "Payment Processing",
      "Charge customers correctly, securely, and exactly once via external gateways.",
      "Never store raw cards (PCI-DSS) — tokenize. Idempotency keys stop double charges. Payment state machine (initiated->authorized->captured->refunded). Handle async webhooks; reconcile daily.",
      "Stripe/Razorpay PaymentIntent with idempotency key; confirm via webhook; store only tokens.",
      "Card/UPI/wallet payments, refunds, subscriptions.",
      "Checkout -> Payment Svc -> Gateway ; webhook -> state machine + reconcile",
      "External dependency/latency; webhook reliability; fraud/chargebacks; strict compliance.",
      "Stripe, Razorpay, Braintree, Adyen, PayPal."),
    E("ecommerce", "Inventory Management (Avoid Oversell)",
      "Under high concurrency two buyers must not both buy the last unit.",
      "The last-item problem needs strong consistency on the counter: atomic conditional update (UPDATE ... SET qty=qty-1 WHERE qty>0), or reserve-on-add with TTL, or Redis atomic DECR + async DB reconciliation for flash-sale scale.",
      "Reserve stock at checkout via a conditional update; release on payment failure or reservation timeout.",
      "Stock display, reservations, flash sales, multi-warehouse.",
      "Checkout -> atomic: UPDATE stock SET qty=qty-1 WHERE sku=? AND qty>0",
      "Strong consistency caps throughput (hot SKUs); reservation cleanup; multi-warehouse allocation.",
      "SQL row locks, Redis atomic ops, Redlock, event-sourced stock."),
    E("ecommerce", "Order Management & Fulfillment",
      "Track an order through its lifecycle across many services.",
      "Explicit state machine (placed->paid->packed->shipped->delivered->returned) driven by events; orders in an ACID DB (source of truth); project a read model for history/tracking; emit events to warehouse/shipping/notify/analytics.",
      "Order service persists state; each fulfillment step emits an event updating status and notifying the customer.",
      "Order tracking, returns, support, seller dashboards.",
      "Order (Postgres) -> events -> {Warehouse, Shipping, Notify, Analytics} ; projection -> history",
      "Many states/edge cases (partial shipments, cancels); cross-service consistency; audit needs.",
      "Event sourcing vs CRUD state machine; Temporal for long-running workflows."),
    E("ecommerce", "Recommendation System",
      "Surface relevant products to lift engagement and revenue.",
      "Two-stage funnel: candidate generation (collaborative filtering / two-tower embeddings -> ANN, recall) then ranking (deep model on rich features, precision), plus business re-ranking (margin, stock, diversity). Train offline, serve online, evaluate via A/B.",
      "'Customers who bought X also bought Y' (item-item CF); personalized home via embeddings + ranker.",
      "Homepage, PDP related, cart cross-sell, email.",
      "Events -> train ; request -> candidate gen (ANN) -> ranker -> re-rank -> results",
      "Cold start; feedback loops/popularity bias; heavy infra; needs experimentation.",
      "CF, content-based, matrix factorization, two-tower; TF Recommenders, FAISS, AWS Personalize."),
    E("ecommerce", "Notification System",
      "Send billions of transactional and marketing messages reliably across channels.",
      "Async via queues: a service consumes events, renders templates, dispatches to channel providers with retries/rate limits; respects prefs/opt-outs; dedupes; tracks delivery; priority queues split transactional from marketing.",
      "OrderShipped -> queue -> worker renders email -> SES/Twilio/FCM; retries with backoff.",
      "Order updates, OTP, price-drop alerts, marketing campaigns.",
      "Events -> [Queue] -> Notification workers -> {Email, SMS, Push} + prefs/retry/dedupe",
      "Provider limits/failures; deliverability/spam; ordering; cost at scale.",
      "SES/SNS, Twilio, FCM/APNs, SendGrid; Kafka/SQS backbone."),
    E("ecommerce", "Flash Sale / High-Contention Drop",
      "Millions rush a few thousand units in seconds — extreme spike + last-item problem.",
      "Protect the system: waiting-room/queue to admit gradually; pre-warm caches; Redis atomic DECR for stock (stop at 0), reconcile to DB async; aggressive rate limiting + bot detection; idempotent add-to-cart/checkout; graceful degradation.",
      "Limited-drop: virtual queue -> buy token -> Redis atomic stock -> async order persistence.",
      "Flash sales, ticket/limited drops, Black Friday doorbusters.",
      "Users -> waiting room -> rate limiter -> Redis DECR -> token -> async order -> DB",
      "Redis-DB reconciliation; fairness vs bots; huge transient load; over-provisioning cost.",
      "Redis atomic/Lua, queue-based admission, CDN edge logic."),
]
